### ISSUE TITLE
[Bug Report] v-timeline with dense and left attribute not working

### ISSUE THREAD

**Issue by WhiteBookmark** [vuetifyjs/vuetify#9370]
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.132
**OS:** Linux

### Steps to reproduce
Make a simple timeline and add dense property then use the left attribute to make timeline items get oriented in only 1 side.

### Expected Behavior
All items to be on the side I define (left or right)

### Actual Behavior
Attributes (left and right) are not working with dense enabled

### Reproduction Link
<a href="https://codepen.io/rapper/pen/wvvWzqg" target="_blank">https://codepen.io/rapper/pen/wvvWzqg</a>

**Comment by ibrahimBeladi** [comment]
With `dense` you need to use `reverse` to align to the other side.
I am not sure about how Vuetify's team is going to resolve this if it is not as intended. You may keep it open for them to see the issue and share their opinion.

**Comment by WhiteBookmark** [comment]
@ibrahimBeladi  Thanks your solution worked for me but I still think this is a workaround rather than a fix, if this is the actual method then I think this should be a good thing to be mentioned in docs.
