### ISSUE TITLE
[Documentation] Datatable groupby documentation unclear

### ISSUE THREAD

**Issue by dgrootem** [vuetifyjs/vuetify#9374]
### Environment

**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
scroll to documentation about groupby. It lists 2 possibilities for this option:
string | string[]

when using just a string everything works as expected
when using an array, i would expect it to do nested grouping but it doesn't seem to work like that, it seems to be only using the first string in the array

### Expected Behavior
it would be nice if this was documented (how to use this, what to expect, is nested grouping supported...)

### Actual Behavior
only the use of a single string is documented (and used in the example)

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables" target="_blank">https://vuetifyjs.com/en/components/data-tables</a>

### Other comments
maybe this is a bug in the code?
maybe it is just documentation that is not consistent with the code?
atm, it's just not clear what to expect

**Comment by johnleider** [comment]
Maybe we could add a signature for this @nekosaur ?

![image](https://user-images.githubusercontent.com/9064066/72464345-b33f9000-379a-11ea-814a-85909ac9ae26.png)

**Comment by nekosaur** [comment]
currently group-by only supports a single grouping

**Comment by MajesticPotatoe** [comment]
I'll update to the description to mention that 👍
