### ISSUE TITLE
[Bug Report] VTreeNode: Null or Undefined children causing trouble with event bubbling

### ISSUE THREAD

**Issue by GaetanWi** [vuetifyjs/vuetify#9376]
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Open console on the codepen. The exception is happening at `const children = getObjectValueByPath(item, this.itemChildren, [])` (line 200) in the `buildTree` method. 

Messing up the behaviour of the item with `null` or `undefined` children value

### Expected Behavior
Should not crash since it's preventing event bubbling

### Actual Behavior
Crashing causing event bubbling issues since properties are not added to the cache

### Reproduction Link
<a href="https://codepen.io/GaetanWcz/pen/MWWeEGM?editors=1111" target="_blank">https://codepen.io/GaetanWcz/pen/MWWeEGM?editors=1111</a>

### Other comments
Was broken before my modification https://github.com/vuetifyjs/vuetify/pull/9082 and still is. (The intended fix works fine, when every one has no children or an empty children it works fine)

**Comment by GaetanWi** [comment]
Not really sure how an array could be undefined with good backend architecture though.

**Comment by jacekkarczmarczyk** [comment]
Happens only with `null`, `undefined` works fine

**Comment by johnleider** [comment]
It works because undefined is an absence of a reference whereas null is a reference to nothing. That's why the method returns the null which attempts to get iterated.

Use undefined, an array or don't define it.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by JasonLandbridge** [comment]
@johnleider, thanks for the tip!

I'm using an object that has itself as children, but the most deeply nested children would show to be expandable. Even though they shouldn't be and looping over those instances and setting those to undefined fixed those nodes. 

```Typescript
export interface FooObject{
  id: number;
  key: number;
  children: FooObject[];
}

// Api call
response.children.forEach((child) => {
	child.children.forEach((grandChild) => {
		grandChild.children = undefined;
	});
});

```

Any way this "setting to undefined" could be added to: [v-treeview/#load-children](https://vuetifyjs.com/en/api/v-treeview/#load-children)?
