### ISSUE TITLE
[Bug Report] make v-select inside v-navigation-drawer item list position not straight

### ISSUE THREAD

**Issue by jokerrider007** [vuetifyjs/vuetify#9379]
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows

### Steps to reproduce
Make a v-select inside v-navigation-drawer

### Expected Behavior
v-select drop-down list show position straight like this
https://codepen.io/johnjleider/pen/mLbZyP?editors=1010

### Actual Behavior
v-select drop down position is not straight with v-select

### Reproduction Link
<a href="https://codepen.io/1ce1ce/pen/jOOrKLQ" target="_blank">https://codepen.io/1ce1ce/pen/jOOrKLQ</a>

**Comment by KaelWD** [comment]
Menus have a margin against the screen edges so they can always be dismissed without the keyboard.
