### ISSUE TITLE
[Bug Report] Border radius not removed on v-list when using tile prop

### ISSUE THREAD

**Issue by csheppard** [vuetifyjs/vuetify#9380]
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.13.6

### Steps to reproduce
Use `tile` prop on `v-list`

### Expected Behavior
No border radius

### Actual Behavior
`.v-sheet--tile` is CSS not overriding `.v-list` 

### Reproduction Link
<a href="https://codepen.io/ragingsyntax/pen/abbZRXZ" target="_blank">https://codepen.io/ragingsyntax/pen/abbZRXZ</a>

**Comment by dr3tt** [comment]
Temporary fix: wrapping the list with a card (<v-card tile>).

**Comment by SirLamer** [comment]
class "v-list" has "border-radius: 4px" on it and it doesn't need it because "v-sheet" has it that. Just drop this property on v-list and it'll work.

**Comment by johnleider** [comment]
as of v2.3 `v-list` has a default border-radius of 0.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
