### ISSUE TITLE
[Bug Report] v-list-item: Different css-code for debug and release

### ISSUE THREAD

**Issue by Staf4** [vuetifyjs/vuetify#9385]
### Environment
**Vuetify Version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Build app for dev and releace.

Debug:
![2019-10-17_10-54-47](https://user-images.githubusercontent.com/18266121/66989319-d2138500-f0cc-11e9-8835-19ab9e8d945a.png)

Release:
![2019-10-17_10-55-00](https://user-images.githubusercontent.com/18266121/66989324-d5a70c00-f0cc-11e9-9943-7a813ac1caa7.png)

### Expected Behavior
same code and visual appearance.

### Actual Behavior
different code and visual appearance.

### Reproduction Link
<a href="https://jsfiddle.net/none" target="_blank">https://jsfiddle.net/none</a>

**Comment by johnleider** [comment]
This is an active effort and has been mostly resolved.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
