### ISSUE TITLE
[Feature Request] v-avatar to and replace props like v-card

### ISSUE THREAD

**Issue by Akari1987** [vuetifyjs/vuetify#9389]
### Problem to solve
Thanks for awesome framework!

I want to implement twitter style avatar link.
`<v-avatar><router-link :to="other URL"><img :src="avatar.jpg"></router-link></v-avatar>`

With avobe codes, avatar aspect is broken.

### Proposed solution
So, please add to and replace props.

**Comment by johnleider** [comment]
Already possible: https://codepen.io/johnjleider/pen/ExxmveN?editors=1111

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
