### ISSUE TITLE
Button component of `Speed-dial` doesn't display as the same as the doc shows

### ISSUE THREAD

**Issue by JohnPion-Zhang** [vuetifyjs/vuetify#939]
### Versions

version 0.13

### What is expected ?

I copy the code which code of doc without anything modified, and I expect to see <<speed-dial component>> display just like doc show

### What is actually happening ?

I found that button in <<speed-dial>> is not a circle, and it displays or hides without animation. Moreover, I haven't used any custom transition which I defined. It shows just like the picture
<img width="436" alt="screen shot 2017-07-10 at 11 33 33 am" src="https://user-images.githubusercontent.com/25896388/28002012-bf2fc864-6563-11e7-81dc-22e28736dfb5.png">

### Reproduction Link
https://github.com/vuetifyjs/docs/blob/master/examples/fabs/5.vue

**Comment by nekosaur** [comment]
The link you posted is not a reproduction. Please use codepen to recreate your problem.

**Comment by JohnPion-Zhang** [comment]
Thanks, I have known what happened, because of
