### ISSUE TITLE
[Feature Request] More configurable v-data-table-header

### ISSUE THREAD

**Issue by zorn-v** [vuetifyjs/vuetify#9392]
### Problem to solve
Currently table header looks like other data of table. In my opinion there is must be some contrast.

### Proposed solution
Even pass "dark" to header on light theme should be enough at begin

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
