### ISSUE TITLE
[Bug Report] xl override brakepoint is not working in latest versions

### ISSUE THREAD

**Issue by BelTeamProjects** [vuetifyjs/vuetify#9394]
### Environment
**Vuetify Version:** 2.1.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 7

### Steps to reproduce
open link, change sass/main.scss xl point

### Expected Behavior
change container size

### Actual Behavior
is not working in latest versions

### Reproduction Link
<a href="https://codesandbox.io/s/cs-vue-cli-3-u5u7s" target="_blank">https://codesandbox.io/s/cs-vue-cli-3-u5u7s</a>

**Comment by marymar** [comment]
Facing the same issue.
Because we only need 3 of the breakpoints and just one container max width in our project, we override the variables $grid-breakpoints and $container-max-widths with a new settings. while it works good in the past, we have know the same issue.
I think the problem is now, that the !default setting changed from the list to an empty list. So the map-deep-mege has to be used, right?

See: https://github.com/vuetifyjs/vuetify/pull/9311

How is it now possible to overwrite the settings, but also to use minor breakpoints?

Thx

**Comment by skortabeast** [comment]
I solved problem use last sass version and change vue.config to 
` css: {
    loaderOptions: {
      sass: {
        prependData: `@import "~@/sass/main.scss"`,
      },
    },
  },`
but I'm not sure  that it  is rigth

**Comment by frandiox** [comment]
My workaround is like this:

1. Import `@import '~vuetify/src/styles/settings/_variables.scss';`.
2. Copy declarations for `$grid-breakpoints`, `$container-max-widths` and `$display-breakpoints` from that same file (minus the ` () !default` lines, and using `map-merge` instead of `map-deep-merge`).
3. Change values of the copied `$grid-breakpoints`.
4. Import `@import '~vuetify/src/styles/styles.sass'` (everything else that depend on the previous overriden variables)


I think either `$grid-breakpoints` should be moved to a different file so it's easier to modify before dependent variables are generated; or the `() !default` should contain all the breakpoints already so custom breakpoints can be defined before importing this file.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/customization/sass-variables

You don't need the import, but you do need to apply the sass-loader data option somehow.

**Comment by tvld** [comment]
Tried all of the above, but can not get the ``$grid-breakpoints`` changed. Following the documentation does not work. What I tried but has no effect:

variables.scss
```scss
@import '~vuetify/src/styles/styles.sass'; // to allow map-merge function and so on
@import '~vuetify/src/styles/settings/_variables.scss';
$grid-breakpoints: map-merge($grid-breakpoints, (
  xs: 0,
  sm: 476px,
  md: 668px,
  lg: 1000px,
  xl: 1300px
))
```

and in nuxt.config.js :
```js
vuetify: {
    customVariables: ['~/assets/variables.scss'],
    breakpoint: {
      thresholds: {
        xs: 600,
        sm: 960,
        md: 1280,
        lg: 1820, // was 1920
      },
      scrollBarWidth: 24,
    },
  },
```

**Comment by KaelWD** [comment]
> Following the documentation does not work. 

It does. There are a couple of examples of maps and neither of them have map-merge or any imports, if you just define the values you want they will get merged automatically.

**Comment by tvld** [comment]
@KaelWD well... could you tell me what is wrong with what I did above then?

**Comment by KaelWD** [comment]
```diff
- @import '~vuetify/src/styles/styles.sass'; // to allow map-merge function and so on
- @import '~vuetify/src/styles/settings/_variables.scss';
- $grid-breakpoints: map-merge($grid-breakpoints, (
+ $grid-breakpoints: (
  xs: 0,
  sm: 476px,
  md: 668px,
  lg: 1000px,
  xl: 1300px
- ))
+ )
```

**Comment by tvld** [comment]
Well. .that started with of course  ;-)  : in variables.scss
```scss
$grid-breakpoints: (
  xs: 0,
  sm: 476px,
  md: 668px,
  lg: 1000px,
  xl: 1300px
);
```

**Comment by KaelWD** [comment]
Does *anything* you do in that file apply? If not then it isn't being loaded and this is an issue for the nuxt plugin.

**Comment by tvld** [comment]
yes, the file is loaded. I use it to set color variables. customVariables loader works fine:
```js
vuetify: 
    customVariables: ['~/assets/variables.scss'],  // imports fine, I can use the vars
    // does not do anything:
    breakpoint: { 
      thresholds: {
        xs: 600,
        sm: 960,
        md: 1280,
        lg: 1820, // TVld was 1920
      },
      scrollBarWidth: 24,
    },
  },
  /*
```

**Comment by tvld** [comment]
@KaelWD  ok, this is weird. By some conicidence I found that $grid-breakpoints: () only work in my production builds. In development stubbornly will stick to the defaults and ignores all I set in the variables.scss file. Strange... ?

**Comment by KaelWD** [comment]
Nuxt has some really bad default settings, I guess they never did change that one: https://github.com/nuxt-community/vuetify-module/issues/154#issuecomment-529280992

**Comment by tvld** [comment]
ah.. good... so it was a bug, although by Nuxt.... thanks and sorry for reporting here )

**Comment by felek000** [comment]
Is there any options to variables.scss takes effect, or for now every change i have to nuxt build entire app ?

**Comment by tvld** [comment]
I think the bug is that variables.scss only take in effect in the production build. Nothing happens in dev, which makes it unusable. (Talking about nuxt here! )

**Comment by felek000** [comment]
Yes means for now i can override elements using class.  It works, still i prefer change just variables to rebuild element. Cleaner and less code to check. I lost 3 h thinking what im doing wrong. My first time nuxt/vuetify ...... 

So how override vuetify in just vue ? Same bug or its just nuxt ?

**Comment by KaelWD** [comment]
With nuxt you need to set `treeShake` to true: https://github.com/nuxt-community/vuetify-module#treeshake

**Comment by tvld** [comment]
@KaelWD  that's not a real option. For a very small website, 5 pages, on a 2018 model core i7 with 12GB RAM, we get with ``treeShake=true``:

![Screenshot from 2020-01-20 09-29-45](https://user-images.githubusercontent.com/986182/72706980-04b79880-3b68-11ea-85ed-412716f96c10.png)
while without the treeShake enabled:
![Screenshot from 2020-01-20 09-30-29](https://user-images.githubusercontent.com/986182/72707005-17ca6880-3b68-11ea-8a58-024862821ef8.png)

**3 x more compile** time and **6x more memory**: basically useless. And  what if project gets larger same? 
I think for now it is best to admit this is a real bug and that  in Vuetify practical use of variables is impossible when using Nuxt.

**Comment by KaelWD** [comment]
How much of that is from sass rather than js? There's a good chance that even if we implemented some alternative way to do this without loading unpackaged js you'd have the exact same performance.

**Comment by tvld** [comment]
There is no sass at all. ``variables.scss`` is _empty_ except for:
```js
@import '~vuetify/src/styles/styles.sass'; // to allow map-merge function and so on
$grid-breakpoints: map-merge($grid-breakpoints, (
  xs: 0,
  sm: 600px,
  md: 960px,
  lg: 1280px,
  xl: 1820px
));

```

**Comment by KaelWD** [comment]
I mean the sass compiler. With treeShake enabled you're compiling all of vuetify's sass files to be able to apply those changes. I also noticed the nuxt module doesn't use the optimal import so I submitted a pr to fix that: https://github.com/nuxt-community/vuetify-module/pull/267

**Comment by frandiox** [comment]
@KaelWD About that new import, I remember you wrote that on Stackoverflow or something and I tried it. It worked well in development but later in the production build, the CSS order was no the same and some styles were weird because of this. Just mentioning it because perhaps some other people will have the same issue after changing that.

Note that I'm not using Nuxt, just pure Vue CLI app.

**Comment by tvld** [comment]
Ah, well.. we import about 20 typography definitions  by @ import a small .scss file in ``/layout/default.vue``, that is all. We need that import mainly to add some responsiveness that we could not due to the breakpoint issue. Other than that we do all with Vuetify classes.

**Comment by felek000** [comment]
I manage to override some basic styles however i have trouble in colors.
variables.scss
```
$grey:map_merge($grey,(
        'base': #9e9e9e,
        'lighten-5': #fafafa,
        'lighten-4': #f5f5f5,
        'lighten-3': #eeeeee,
        'lighten-2': #e0e0e0,
        'lighten-1': #bdbdbd,
        'darken-1': blue,
        'darken-2': #616161,
        'darken-3': #424242,
        'darken-4': #212121
));
OR
$grey:map-deep-merge((
        'base': #9e9e9e,
        'lighten-5': #fafafa,
        'lighten-4': #f5f5f5,
        'lighten-3': #eeeeee,
        'lighten-2': #e0e0e0,
        'lighten-1': #bdbdbd,
        'darken-1': blue,
        'darken-2': #616161,
        'darken-3': #424242,
        'darken-4': #212121
),$grey);
```
in nuxt.config

```
.....
    customVariables: ['~/assets/styles/variables.scss'],
    theme: {
      dark: false,
      themes: {
        light: {
          primary: colors.grey.darken1
        },
....
```

component
```
<p class="grey--text text--darken-1">test</p>
<q-btn color="primary" label="Primary" />
```

text /button should be blue but its not. That kinda variables should be override   different ?

**Comment by tvld** [comment]
@felek000  problem  also on prod-build or only on dev ?

**Comment by felek000** [comment]
for now i try only on dev.

`"dev": "nuxt",`

also have problems testing it on ie11

my .babelrc

```
{
  "env": {
    "test": {
      "presets": [
        [
          "@nuxt/babel-preset-app",
          {
            "targets": {
              "browsers": "> 0.5%, ie >= 11",
              "node": "current"
            }
          }
        ]
      ]
    }
  }
}

```

in nuxt config
```
...
    script: [
      {
        src:
          'https://polyfill.io/v3/polyfill.min.js?features=default%2Ces2015%2Ces2016%2Ces2017%2CArray.from%2CPromise%2CPromise.prototype.finally%2CEventSource'
      }
    ],
...
```
is there any valid config for supporting ie11 ?

**Comment by tvld** [comment]
Please first try on prod and then set the treeShake parameter.

**Comment by felek000** [comment]
After run nuxt build cant check page.
I run `http-server ./ ` inside of server dir server. All path are wrong. so i have to check config of nuxt how to fix that.

https://www.npmjs.com/package/http-server

**Comment by felek000** [comment]
Sr for late replay i run on build on local server. 
It runs in mode universal.

browserslistrc
```
> 1%
last 2 versions
not ie <= 8
```
babel
```
{
  "env": {
    "test": {
      "presets": ["@babel/env"],
      "plugins": [
        "dynamic-import-node",
        "@babel/transform-runtime"
      ]
    }
  }
}

nuxt config
```
...
  vuetify: {
    treeShake: true,
    customVariables: ['~/assets/styles/variables.scss'],
    theme: {
      dark: false,
      themes: {
        light: {
          primary: colors.grey.darken1
        },
        dark: {
          primary: colors.blue.darken1,
          accent: colors.grey.darken3,
          secondary: colors.amber.darken3,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        }
      }
    }
  },
...
```
I'm not able to run it on ie and override _variables.scss.
However for custom colors just simple switching imports works fine.
`import colors from './assets/styles/modules/colors.js'`
