### ISSUE TITLE
Slider selector

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vuetifyjs/vuetify#94]
Dear Vuetify Team,

it would be nice to add a [slider](https://material.io/guidelines/components/sliders.html) selector.

Cheers,

Francesco

**Comment by johnleider** [comment]
https://github.com/vuetifyjs/vuetify/wiki/Roadmap#v090

**Comment by FrancescoSaverioZuppichini** [comment]
No slider was added.

**Comment by johnleider** [comment]
Correct, but it's on the roadmap and will be. The feature request is part of the MD spec, so it's technically just a request for something that is going to be in the framework before launch.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you ;)
