### ISSUE TITLE
Unknown custom element: <v-card-actions>

### ISSUE THREAD

**Issue by willypuzzle** [vuetifyjs/vuetify#940]
`Unknown custom element: <v-card-actions>`

I got this error, I copied and pasted what I found in the examples. All the others components are found but this not.

**Comment by JohnPion-Zhang** [comment]
Because of your version is still 0.12。I have met the same problem, you're supposed to update to version 0.13. Best wishes to you, guy

**Comment by forteleaf** [comment]
i got, too.
link ... https://jsfiddle.net/Lvfah9qf/29/
is not fix it, yet?

**Comment by nekosaur** [comment]
You've misspelled it. You're missing an `s` on the end. It's `v-card-actions`.

Also please do not comment on closed issues. If you have problems come join our [chat](https://chat.vuetifyjs.com), or create a new issue using the [issue creator](https://issues.vuetifyjs.com).
