### ISSUE TITLE
[Feature Request] Add disable-click-watcher prop to v-navigation-drawer

### ISSUE THREAD

**Issue by nakorndev** [vuetifyjs/vuetify#9400]
### Problem to solve
At this code line only support prop for `stateless` which disable all event to `closeConditional`. it could be useful if there is only `disable-click-watcher` for `<v-navigation-drawer>` because some time I got dialog on top at drawer which if any click event in dialog, drawer will be closed too. Thanks. 👍

https://github.com/vuetifyjs/vuetify/blob/4a84f2a6a1a09cdaf9f1357c9654edcd2cf65512/packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts#L199-L205

### Proposed solution
Add `disable-click-watcher` to support not to be react when click outside element.

**Comment by drascom** [comment]
you can use v-click-outside="" directive to keep navigation drawer.
v-click-outside="onClickOutside" and in methods
` onClickOutside() {
            this.sideBar = true;
        },`

**Comment by drascom** [comment]
add  stateless prop to navigation drawer 
`:stateless="keepOpen"`
than function in methods
` onClickOutside() {
            return true;
        },`
and computed property
` keepOpen(){
            return this.onClickOutside;
        },`

problem solved :)

**Comment by johnleider** [comment]
Since this has a workaround, is changing for v3, and there is no intention to add this in v2, I'm going to mark it as stale and close.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
