### ISSUE TITLE
[Documentation] header-props - Missing "v-data-table-header" component

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#9402]
### Environment

**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
In `v-data-table` component we have `header-props` prop. In docs it is described:

```
Pass props to the default header. See 'v-data-table-header' API for more information
```
![image](https://user-images.githubusercontent.com/17653648/67092600-f1371300-f1af-11e9-8f48-b0fe04f96d37.png)

However component `v-data-table-header` does not exist.

Also in the dropdown for `v-data-table` API docs this component is not listed.

![image](https://user-images.githubusercontent.com/17653648/67092615-fe540200-f1af-11e9-99cc-3a7f4106557a.png)

### Expected Behavior
Docs should describe `v-data-table-header` component.

### Actual Behavior
In docs, there is no information about the `v-data-table-header` component.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#examples" target="_blank">https://vuetifyjs.com/en/components/data-tables#examples</a>

**Comment by yhkl-dev** [comment]
more than one month, this issue is still opening... i met this, OMG

**Comment by JeffreyStevens** [comment]
I need it too, I'd like to tailor the header to have a different background color...

**Comment by Karosuo** [comment]
Same here, need to change the header background color.

**Comment by vmoraru** [comment]
Well, you could try to guess what you could use if you look at the [desktop](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts) or [mobile](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts) version of the header, depending on what you use.

**Comment by Eukki** [comment]
> I need it too, I'd like to tailor the header to have a different background color...

![image](https://user-images.githubusercontent.com/22795768/73739958-e8168580-474f-11ea-828c-32eb73e7a3e2.png)

You can add ```class``` with ```background-color``` in ```headers```

**Comment by preethamrn** [comment]
This is also referenced in the vuetify 1.5 => 2.x migration docs.
https://vuetifyjs.com/en/getting-started/releases-and-migrations/ under `v-data-table`. There's no information about the `header-props` object.

**Comment by amad3v** [comment]
> I need it too, I'd like to tailor the header to have a different background colour...

We really need that information but for now as a workaround I'm using deep styling (values for dark theme):

```
<style scoped>
::v-deep .v-data-table-header {
  background-color: #ccc;
}

::v-deep th {
  color: #000 !important;
}
</style>
```
