### ISSUE TITLE
[Bug Report] v-radio click event is not propagated correctly

### ISSUE THREAD

**Issue by semipro8** [vuetifyjs/vuetify#9408]
### Problem to solve
That way you can fire actions even if the option is selected.

### Proposed solution
Add @click event to v-radio since @change only works if the value is changed.

**Comment by semipro8** [comment]
And adding @click event to the div inside the label slot responds too fast in case you're trying to get the actual value then redirect to another route. It would be nice to have it work like the @change event where it's only if the value is changed, but have @click respond only when/if the value is set.

**Comment by KaelWD** [comment]
<details>
<summary>repro</summary>

```vue
<template>
  <v-container>
    <v-radio-group v-model="radio">
      <v-radio label="1" @click="onClick"></v-radio>
      <v-radio label="2"></v-radio>
    </v-radio-group>
  </v-container>
</template>

<script>
  export default {
    data: () => ({
      radio: null
    }),
    methods: {
      onClick (e) {
        console.log(e)
      }
    }
  }
</script>
```
</details>

---

https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components

> div inside the label slot responds too fast
https://vuejs.org/v2/api/#Vue-nextTick

**Comment by yooneskh** [comment]
I think you can use @click.native
