### ISSUE TITLE
[Bug Report] Text input on dark theme having white background

### ISSUE THREAD

**Issue by TheInvoker** [vuetifyjs/vuetify#9411]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Type something and then refresh page and attempt to type same thing again. This may not work in a code pen though...

### Expected Behavior
Text input background color is dark

### Actual Behavior
Text input background color is white

### Reproduction Link
<a href="https://codepen.io/sneaky666/pen/XWWNmKb" target="_blank">https://codepen.io/sneaky666/pen/XWWNmKb</a>

How it looks on error:
https://imgur.com/YcTLXvw

The css causing it
https://imgur.com/5ow4yWT

**Comment by KaelWD** [comment]
Duplicate of #5269
