### ISSUE TITLE
[Bug Report][Not that important][Gecko?] Flickering Card ripple on leaving page

### ISSUE THREAD

**Issue by ibrahimBeladi** [vuetifyjs/vuetify#9414]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Waterfox 56.2.14 + Firefox Quantom 69.0.3 (64-bit) 
**OS:** Linux x86_64
**Mobile Browsers:**  Firefox 68.1.1 (android 5.0)

### Steps to reproduce
It might take several attempts to happen.
1. Click the card.
### Expected Behavior
No flickering

### Actual Behavior
Flickering

### Reproduction Link
<a href="https://codepen.io/ibrahimbeladi/pen/zYYodjR?editors=1000" target="_blank">https://codepen.io/ibrahimbeladi/pen/zYYodjR?editors=1000</a>

### Other comments
Tested on various browsers. It seems it effects Gecko engine only.

**Comment by bigbadfatman** [comment]
Do you still see the flickering happen when you remove the `href` attribute or change the `href` attribute to `javascript:void()`?
