### ISSUE TITLE
[Feature Request] Adding a bottom margin to native lists (ul, ol, dl)

### ISSUE THREAD

**Issue by sebiniemann** [vuetifyjs/vuetify#9417]
### Problem to solve
Having native lists followed by native paragraphs

```html
<p>
  Lorem ipsum dolor ...
</p>

<ul>
  <li>Something A</li>
  <li>Something B</li>
</ul>

<p>
  Lorem ipsum dolor ...
</p>

```

creates a weird looking content flow, as paragraphs are separated from each other by `margin-bottom: 16px` (by `.v-application p` and as stated in https://vuetifyjs.com/en/styles/content), but lists are not. Any content followed by a native list will always stick to it.

It looks even more weird for pages with headlines followed by a paragraph (nice separation before the headline starts), compared to lists followed by another headline (the headline starts directly below the list).

### Proposed solution
As lists cannot be simply surrounded by paragraphs (since the latter one only accepts phrasing content), also adding a `margin-bottom` rule could be done instead.

On the pro side (of adding a fixed css rule for native lists):
- would be the same solution as used by the material design team
- would be consistent with how its solved for paragraphs and other flow content within vuetify
- avoids adding `mb-x` to every list in user land, in order to emulate this behaviour

On the cons side:
- could be a breaking change
- some components may need an additional reset rule

This issue is actually in contrast with an earlier feature request from me (https://github.com/vuetifyjs/vuetify/issues/6258), where I asked to avoid CSS manipulation of standard HTML elements.

From my point of view, it would help to either consistently pre-style native HTML elements (like adding a bottom margin to every flow content) or to fully avoid it.

**Comment by johnleider** [comment]
I agree. Could this be considered a bug @vuetifyjs/core-contributors @vuetifyjs/core-team ?
