### ISSUE TITLE
[Bug Report] Tab-item's height changes when a new tab added programmatically

### ISSUE THREAD

**Issue by coldze** [vuetifyjs/vuetify#9418]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
In provided codepen click "add tab" or "remove tab" button.

### Expected Behavior
Tab items, when added/removed, are not scaled, height stays the same

### Actual Behavior
Tab item's height is changed, that causes rest of components go back and forth in UI.

### Reproduction Link
<a href="https://codepen.io/coldze/pen/KKKNbpp" target="_blank">https://codepen.io/coldze/pen/KKKNbpp</a>

**Comment by johnleider** [comment]
The issue when adding new items can be resolved by awaiting until the data persists before updating the model: https://codepen.io/johnjleider/pen/XWJPbEx

As far as removing, the element is physically taken out so there is nothing to transition.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
