### ISSUE TITLE
Light property does not affect icons

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#942]
### Steps to reproduce
https://codepen.io/darkside73/pen/OgajWj

### Versions
vue@2.3.4
vuetify@0.13.1

### What is expected ?
Icon with light property applied

### What is actually happening ?
Icon without light property

### Reproduction Link
https://codepen.io/darkside73/pen/OgajWj

**Comment by johnleider** [comment]
According to spec, light theme icons are dark and dark theme icons are light.
