### ISSUE TITLE
[Bug Report] Unable to set VSparkline gradient for type=bar

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#9421]
### Environment
**Vuetify Version:** 2.1.5
**Last working version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Set type=bar.
2. Set gradient.
3. Bar color remain black/white only depending on light/dark theme.

### Expected Behavior
Bar color should be as per gradient.

### Actual Behavior
Bar color remains black/white only depending on light/dark theme.

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/WNNoBqJ" target="_blank">https://codepen.io/andrewspy/pen/WNNoBqJ</a>

**Comment by johnleider** [comment]
Reverted changes made in c5f72bb
