### ISSUE TITLE
DatePicker - clearable prob does not clear data

### ISSUE THREAD

**Issue by bgovi** [vuetifyjs/vuetify#9424]
The clearable option for datepicker will remove the displayed date value, but the underlying data is not changed. Was expecting to be set to null or someother default value.

**Comment by bornakke** [comment]
Dealing with the same problem. How to catch that clearable is clicked.

**Comment by bornakke** [comment]
A simple hack is to use the trigger of clearing to run a function that resets the value manually:
@click:clear="fixDataPickerClearBug('filterToDate')"
