### ISSUE TITLE
[Bug Report] Error on VSparkline auto-draw with less than 2 values

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#9426]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Set `auto-draw`
2. Set `:value="[1]"`

### Expected Behavior
Should check the value count and disable auto-draw

### Actual Behavior
Error in console:

```
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'getTotalLength' of undefined"

found in

---> <VSparkline>
       <VContent>
         <VApp>
           <Root>
```

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/LYYxzba" target="_blank">https://codepen.io/andrewspy/pen/LYYxzba</a>

**Comment by johnleider** [comment]
I'll resolve the underlying issue however it could be debated that if only 1 value was provided, it should display a single point on the canvas. Thoughts @sh7dm ?

**Comment by andrewspy** [comment]
@johnleider Since this is a line chart, I think it can be a horizontal line on a single value.
