### ISSUE TITLE
[Bug Report] Table's scrollbars visible under dialog on mobile firefox

### ISSUE THREAD

**Issue by da3monHunter** [vuetifyjs/vuetify#9428]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1) Create a Simple table with horizontal scrollbar i.e should have enough columns that horizontal scrollbar appear on mobile view
2) pop up a dialog over the table
3) launch in mobile view..

### Expected Behavior
The dialog should hide everything under it.

### Actual Behavior
Not hiding the scrollbars on firefox mobile view

### Reproduction Link
<a href="https://codepen.io/akkhan20/pen/ExxZEva" target="_blank">https://codepen.io/akkhan20/pen/ExxZEva</a>

**Comment by da3monHunter** [comment]
![animation](https://user-images.githubusercontent.com/25948082/67261680-25b21400-f4bb-11e9-9824-1e892c942840.gif)

**Comment by KaelWD** [comment]
Not related to vuetify: https://jsbin.com/gorebuhage
