### ISSUE TITLE
Stepper component's transitions between steps

### ISSUE THREAD

**Issue by Tailzip** [vuetifyjs/vuetify#943]
### Steps to reproduce
Create a stepper with flexible height `<v-stepper-content>` children components.
_In the docs, they have a fixed height set with CSS and it works fine!_

### Versions
0.13.1

### What is expected ?
Transitions between steps should be _smooth_ no matter how tall the `<v-stepper-content>` children components are.

### What is actually happening ?
Step's content is overlapping stepper header when animating.
https://cl.ly/lUTu

### Reproduction Link
https://codepen.io/anon/pen/PjxJdg

**Comment by nekosaur** [comment]
A possible solution for now is to wrap your `v-stepper-content` elements inside a div with `position: relative`

**Comment by johnleider** [comment]
We will be giving this the similar treatment to that of tabs, supplying a content wrapper with the proper positioning.

**Comment by talski** [comment]
it's still happening in 16.9

https://codepen.io/anon/pen/wrLXxw?editors=1010

**Comment by johnleider** [comment]
Do you think it might be because you are missing the new component `v-stepper-items`?

**Comment by talski** [comment]
well, I couldn't find it in docs, found it in release notes, thank you

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/docs/pull/334
