### ISSUE TITLE
[Bug Report] In a Text-field prepend-inner icon break the label

### ISSUE THREAD

**Issue by MrWaip** [vuetifyjs/vuetify#9430]
### Environment
**Vuetify Version:** 2.1.5
**Last working version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
In some version (2.*.*) label had started work incorrect with tooltip in the prepend-inner slot

### Expected Behavior
Label working normal

### Actual Behavior
Label go right so hard

### Reproduction Link
<a href="https://codepen.io/mrwaip/pen/eYYgjeq?editors=1010" target="_blank">https://codepen.io/mrwaip/pen/eYYgjeq?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed in 2.2.15
https://codepen.io/jkarczm/pen/Exjmqzx
