### ISSUE TITLE
[Bug Report] In a Text-field a long label has a layout problem

### ISSUE THREAD

**Issue by parkaran** [vuetifyjs/vuetify#9432]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
By shrinking the browser size

### Expected Behavior
i expected to have the same behavior as the first text field that has a short label

### Actual Behavior
the text field with a big label goes over the components near by

### Reproduction Link
<a href="https://codepen.io/Parkaran/pen/dyyNqOd" target="_blank">https://codepen.io/Parkaran/pen/dyyNqOd</a>

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
