### ISSUE TITLE
[Bug Report] FAB is not at the top (Z axis) of the page

### ISSUE THREAD

**Issue by YanWQ-monad** [vuetifyjs/vuetify#9433]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.0
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Check out the codepen reproduction link, and click the FAB (in the bottom half). 

### Expected Behavior
The button is clicked.

### Actual Behavior
The list item is clicked instead of the button.

### Reproduction Link
<a href="https://codepen.io/YanWQmonad/pen/YzzNOPe" target="_blank">https://codepen.io/YanWQmonad/pen/YzzNOPe</a>

**Comment by johnleider** [comment]
The problem here is that `v-list-item` has a relative positioning. This is required for the pseudo elements we utilize for handling hover states. Nothing we can do about this.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
