### ISSUE TITLE
[Feature Request] vuetify-vscode hidden on Github. Can we get it back?

### ISSUE THREAD

**Issue by bizzclaw** [vuetifyjs/vuetify#9435]
### Problem to solve
the VS Code extension for vuetify is what lead me to actually discover and start using vuetify because the snippets were easy to work with, and the framework is sleek, however with sweeping changes to vuetify (v-row instead of v-layout, ect) this extension is now outdated as it does not reflect these changes.

I understand that the extension may have fallen out of development as there might be more pressing matters, but I don't understand why the github page for it was locked down or deleted

### Proposed solution
Unless the extension is planned to be expanded, unhide it on the github repository so that it can be forked for the time being. Thank you.

**Comment by johnleider** [comment]
Unfortunately the maintainer for that plugin went MIA and we have been unable to replace his position for about a year. As such I have deleted the package, sorry.

**Comment by bizzclaw** [comment]
Ah, I was wondering what happened because I couldn't see any official mention of it anywhere.
I've just been modifying the local copy I have to make it work for the newest version of vuetify.

Either way, Thank you for replying and keep up the vuetiful work!
