### ISSUE TITLE
[Bug Report] data-table mobile view with custom slots

### ISSUE THREAD

**Issue by AshrafBasry** [vuetifyjs/vuetify#9436]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
add custom item slot to data-table

### Expected Behavior
the two table should render the same in mobile view

### Actual Behavior
the table with custom slot column doesn't stack

### Reproduction Link
<a href="https://codepen.io/AshrafBasry/pen/QWWdeML" target="_blank">https://codepen.io/AshrafBasry/pen/QWWdeML</a>

### Other comments
i searched in the data-tables docs for how to make this work but i couldn't find any thing about mobile view.

and why slot items props.index is no longer refer to items index like the previous versions and refer to the visible rows index !!

**Comment by nekosaur** [comment]
The way this is (supposed) to work currently is that you will have to define your own row markup for when table is in mobile view by checking the scoped slot prop `isMobile`, but it does not seem to be available on `item` slot.

(`index` in scoped props referred to the visible rows index in 1.5 as well)

**Comment by AshrafBasry** [comment]
@nekosaur 
> (index in scoped props referred to the visible rows index in 1.5 as well)

in ver 1.5.13 `index` referred to the filtered items not the visible rows

**Comment by nekosaur** [comment]
filteredItems _is_ the visible rows

**Comment by AshrafBasry** [comment]
Sorry , i misunderstood the docs

**Comment by alicjamusial** [comment]
Hi, what is the status of this issue? Is someone currently working on that or planning to solve it?
