### ISSUE TITLE
[Bug Report] VTextField: input event fired twice when clicking on buttons inside input of type number

### ISSUE THREAD

**Issue by silvioiannone** [vuetifyjs/vuetify#9442]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.15.0

### Steps to reproduce
Use the tiny buttons inside the input box in order to change the value.

### Expected Behavior
The value should be increased by 1 on each button click.

### Actual Behavior
The value is increased by 2 on each button click.

### Reproduction Link
<a href="https://codepen.io/Mayonnaise/pen/xxxqWYb" target="_blank">https://codepen.io/Mayonnaise/pen/xxxqWYb</a>

### Other comments
The `input` event from the `v-text-field` component is fired twice.

**Comment by MajesticPotatoe** [comment]
This may be platform specific.
The codepen doesn't reproduce the issue on
`Windows 10 - Chrome 77.0.3865.120 x64`
or
`Windows 10 - Chrome 78.0.3904.70 x64`

Will need some other OSX Catalina users to provide feedback
Does this happen on another browser such as firefox? can you also check if there is the new version of chrome is available on OSX and test it there?

**Comment by silvioiannone** [comment]
I agree, this only happens in Chrome 77.0.3865.120 (on my machine). I tested with Safari and Firefox and no issue.

Additionally the event is fired twice only if using the buttons within the input field. If using the keyboard arrow keys only one event is fired and it works as expected.

**Comment by silvioiannone** [comment]
I just upgraded to Chrome 78 and the issue is gone.
