### ISSUE TITLE
[Bug Report] dialog inside menu

### ISSUE THREAD

**Issue by PaoloGi** [vuetifyjs/vuetify#9445]
### Environment
**Vuetify Version:** 2.1.6
**Last working version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1- click on the image
2- click on the menu button "open dialog"

 

### Expected Behavior
It should open the dialog.

### Actual Behavior
It opens and close instantly when the dialog is fullscreen.
All the screen remains shadowed for a normal dialog

### Reproduction Link
<a href="https://codepen.io/sherman123/pen/OJJpYXL?&editable=true&editors=101" target="_blank">https://codepen.io/sherman123/pen/OJJpYXL?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
You have to stop `v-menu` content from causing the dependency chain to close: https://codepen.io/johnjleider/pen/MWYGeVj?editable=true&editors=101

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by KaelWD** [comment]
Is there any scenario in which you'd *want* a menu to close a child dialog?
