### ISSUE TITLE
[Documentation] V-app is not mentioned in the quick start page of the getting started

### ISSUE THREAD

**Issue by urielfcampos** [vuetifyjs/vuetify#9446]
### Environment

**Browsers:** Firefox 70.0, Mozilla Firefox, Google Chrome, Safari
**OS:** Linux x86_64

### Steps to reproduce
V-app is only mentioned in the CDN usage section
ctrl-f for v-app only shows that mention

### Expected Behavior
I expected such an important information that all vuetify apps need to be wrapped in a v-app component to be listed in the first page of the getting started alongside the installation.

### Actual Behavior
v-app usage is only briefly used in a single section named "CDN usage", that leads new people to think that it's only necessary to use the component in that use case. The actual usage is in the FAQ and then it's only mentioned on the components section under application.

### Reproduction Link
<a href="https://vuetifyjs.com/en/getting-started/quick-start" target="_blank">https://vuetifyjs.com/en/getting-started/quick-start</a>

**Comment by MajesticPotatoe** [comment]
Will make note of it in the quickstart and link to the application page.
