### ISSUE TITLE
[Bug Report] VSkeletonLoader Avatar no longer rounded

### ISSUE THREAD

**Issue by chanlito** [vuetifyjs/vuetify#9447]
### Environment
**Vuetify Version:** 2.1.6
**Last working version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.15.0

### Steps to reproduce
Upgrade Vuetify to 2.1.6 and `avatar` for skeleton loader in no longer rounded.

### Expected Behavior
`avatar` in skeleton loader should be rounded.

### Actual Behavior
It's not rounded.

### Reproduction Link
<a href="https://codepen.io/chanlitohem/pen/oNNWNeX" target="_blank">https://codepen.io/chanlitohem/pen/oNNWNeX</a>

### Other comments
I think it's best to allow modify this via a sass variable.

**Comment by aggarwaldev** [comment]
I can fix this if someone from dev team can confirm this as a bug.

**Comment by DRoet** [comment]
Seems like a valid bug yes

**Comment by jacekkarczmarczyk** [comment]
Broken by https://github.com/vuetifyjs/vuetify/commit/74bc9011152b61b36b636249d38a6b9c367d5e99
