### ISSUE TITLE
[Bug Report] v-chip close icon has wrong font-size of 24px

### ISSUE THREAD

**Issue by haugero** [vuetifyjs/vuetify#9451]
### Environment
**Vuetify Version:** 2.1.4
**Last working version:** 1.5.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.14.6

### Steps to reproduce
How I created the app with node(10.15.3) and npm(6.9.0)
1. vue create my-app (default settings)
2. cd my-app
3. vue add vuetify (default settings)

Replaced code in HelloWorld.vue with:
```
<template>
  <v-chip close>Close</v-chip>
</template>

<script>
export default {
};
</script>
```

Let it run with `npm run serve`

### Expected Behavior
The close icon has a font-size of 18px
As here https://vuetifyjs.com/en/components/chips#api

### Actual Behavior
The close icon has a font-size of 24px

### Reproduction Link
<a href="https://github.com/haugero/v-chip-issue" target="_blank">https://github.com/haugero/v-chip-issue</a>

### Other comments
If you instead use the v-chip component only in App.vue and NOT in HelloWorld.vue as e.g.:
```
<template>
  <v-app>
    <v-app-bar app>
      <v-toolbar-title class="headline text-uppercase">
        <span>Vuetify</span>
        <span class="font-weight-light">MATERIAL DESIGN</span>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn
        text
        href="https://github.com/vuetifyjs/vuetify/releases/latest"
        target="_blank"
      >
        <span class="mr-2">Latest Release</span>
      </v-btn>
    </v-app-bar>

    <v-content>
      <v-chip close>Close</v-chip>
    </v-content>
  </v-app>
</template>

<script>

export default {
  name: 'App',
  components: {
  },
  data: () => ({
    //
  }),
};
</script>
```
The font-size of the close icon is correct: 18px

**Comment by MatthiasDamm** [comment]
Same here. 

**VuetifyVersion** 2.15
**Vue Version** 2.6.1
**Browsers:** Chrome 78.0.3904.87
**OS** Windows 10 OS Version 1809 (Build 17763.805)

**Comment by MatthiasDamm** [comment]
Same effect with chips in v-select (small-chips). Font-size get's overriden by .v-icon.v-icon style which comes along with 24px  font-size.
