### ISSUE TITLE
[Bug Report] v-tree-view: wrong result when using filter function

### ISSUE THREAD

**Issue by cluidold** [vuetifyjs/vuetify#9452]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
1. Open all tree nodes
2. Enter "path" to search field.

### Expected Behavior
When entered "path", the tree should correct filter the elements containing the searchText in the property "text". 
So the result for search query "path" should be:

- root
  - config
     - setup
        - paths
          - pathExe
          - pathTemplates

when i search for "pathE" the result should be

- root
  - config
     - setup
        - paths
          - pathExe

### Actual Behavior
When entered "path" in the search field, the tree only filters to the latest node containg children. So the result is

- root
  - config
     - setup
        - paths
          - pathExe
          - pathTemplates
          - workingDir

In this case, workingDir doesn't contain the search text "path"

### Reproduction Link
<a href="https://codepen.io/cluidold/pen/JjjNYoV?editors=1011" target="_blank">https://codepen.io/cluidold/pen/JjjNYoV?editors=1011</a>

**Comment by khoathanglong** [comment]
Anyone plan to work on this?

**Comment by jacekkarczmarczyk** [comment]
> In this case, workingDir doesn't contain the search text "path"

but `paths` node contains the `path` string, so it would rather be a feature request for specifying whether only leaf nodes should be searched or not

**Comment by KaelWD** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
