### ISSUE TITLE
[Bug Report] Theme colors don't change after mounted

### ISSUE THREAD

**Issue by oanstein** [vuetifyjs/vuetify#9453]
### Environment
**Vuetify Version:** 2.1.6
**Last working version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Linux

### Steps to reproduce
Downgrade repo to vuetify@2.1.5 and mounted color is correct

### Expected Behavior
Mounted color changes

### Actual Behavior
Mounted color does not change and stays as default

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-8tbth" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-8tbth</a>

### Other comments
Might be related to vue-meta changes: https://github.com/vuetifyjs/vuetify/commit/6d829efff05ff6d491a719b21f3ea88f5ce1aeaf

**Comment by oanstein** [comment]
Seems the bug only occurs in combination with Nuxt and vuetify@2.1.6. Here is a working example without Nuxt (and vuetify@2.1.6): 
https://codepen.io/Lowryderch/pen/QWWgWbp

**Comment by oanstein** [comment]
I found a hacky solution if you call this.$meta().refresh() on mounted it shows the colors. But at least in development I have now ugly default colors on the initial loading until it's done loading

**Comment by amritk** [comment]
@oanstein is there an equivalent to setting them on created?

**Comment by oanstein** [comment]
> @oanstein is there an equivalent hack to setting them on created?
> 
> https://codesandbox.io/s/codesandbox-nuxt-vyxu5?fontsize=14&hidenavigation=1&theme=dark
> To avoid that initial flash of red

I mask it with an v-overlay and v-skeleton-loader. Unfortunately I have not found a better solution yet.

**Comment by amritk** [comment]
@oanstein Alright found a new workaround
```typescript
created () {
    // Temporary until it gets fixed
    // https://github.com/nuxt/vue-meta/issues/481
    // https://github.com/vuetifyjs/vuetify/issues/9453
    // https://github.com/vuetifyjs/vuetify/issues/9499
    const theme = 'steel-blue'
    this.$vuetify.theme.themes.light.primary = { base: theme }
    this.$vuetify.theme.themes.dark.primary = { base: theme }
    /* eslint-disable */
    // @ts-ignore
    this.$vuetify.theme.applyVueMeta23()
}

mounted () {
    this.$meta().refresh()
}
```

**Comment by johnleider** [comment]
Anyone able to help with this issue would be appreciated greatly. As I do not actively use NUXT, it would be in better hands for someone who does.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by truesteps** [comment]
Issue still occurs, please let's not close this issue

**Comment by truesteps** [comment]
any updates?
