### ISSUE TITLE
[Bug Report] V-Autocomplete selects wrong item

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#9456]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.5.22
**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
1. Type 1009 into the autocomplete to search
2. Select the entry with 1009 in it
3. The entry with 6 is selected

### Expected Behavior
1. Search for entry 1009
2. Select entry 1009
3. Get entry 1009

### Actual Behavior
Selects the wrong entry.

### Reproduction Link
<a href="https://codepen.io/auspex/pen/YzzVNqP?&editable=true&editors=101" target="_blank">https://codepen.io/auspex/pen/YzzVNqP?&editable=true&editors=101</a>

**Comment by johnleider** [comment]
If you aren't using your own `v-list-item` you don't need to use **attrs** or **on**: https://codepen.io/johnjleider/pen/PowdgEX?editable=true&editors=101

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
