### ISSUE TITLE
[Bug Report] label should fly to the top of the icon

### ISSUE THREAD

**Issue by rveruna** [vuetifyjs/vuetify#9457]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Firefox 72.0
**OS:** Windows 10

### Steps to reproduce
create a form with default fields. When using fields with and without prepended icons, label floating behaviour is different.

### Expected Behavior
Label to float to the left same as with outlined fields

### Actual Behavior
label floats on top of the text, not on top of the icon

### Reproduction Link
<a href="https://codepen.io/rveruna/pen/PoomNvZ" target="_blank">https://codepen.io/rveruna/pen/PoomNvZ</a>

**Comment by johnleider** [comment]
Where in the specification are you seeing this? The default text-field look is the default from MD1, in which the label does not fly over the prepended icon.

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
