### ISSUE TITLE
Carousel improvements 

### ISSUE THREAD

**Issue by swerrie** [vuetifyjs/vuetify#946]
**Look at this codepen:**
- https://codepen.io/anon/pen/mwQLPr

**The following features will be a great addition to the carousel component:**
- Have an option to have a transparent background (the codepen's background is 1x1 transparent pixel).
- Have an option to hide the next / previous buttons.
- The next / previous buttons should follow the dark / light theme (not tested myself).
- Slide on mouse event. ~(Maybe with custom effects).~ Already available.
- The slot is currently center aligned  that is ok-ish, but with the codepen I provided, I would have thought the card was top left aligned.
- The slot content disappears after a while.
- Should have an option to disable the touch event on mobile browsers (currently there is by default a slide right / left binding that switches pages but this is also triggered when the slot has scrollable content, tested on vertical scroll only).

**Comment by guykatz** [comment]
also please remove the requirement for the src property of the carousel item component (could be optional I guess but not required)

**Comment by johnleider** [comment]
- You can now omit the src entirely.
- You can now set ```left-control-icon``` or ```right-control-icon```
- Theme options added to carousel, can be set with ```dark``` or ```light```
- Already available
- I'm not sure what you mean
- Again, don't know what you mean, submit a bug issue
- Something we can maybe add in the future, but for now, I don't think scroll behavior is expected with a carousel
