### ISSUE TITLE
[Bug Report] On v-datatable @pagination not triggered on search filter

### ISSUE THREAD

**Issue by Thibaud-R** [vuetifyjs/vuetify#9460]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3762.0
**OS:** Windows 7

### Steps to reproduce
When updating the number of items per page, or changing page, the pagination event is triggered with an update pagination data.
When adding a search filter, it is not (itemsLength). 
In the example, I just add the standard pagination to see that the pagination values are well updated inside the datatable.

### Expected Behavior
@pagination triggered on search

### Actual Behavior
@pagination not triggered on search
(and itemsLength of external Pagination cannot be updated)

### Reproduction Link
<a href="https://codepen.io/thibaud-r/pen/jOOmwje?editors=1010" target="_blank">https://codepen.io/thibaud-r/pen/jOOmwje?editors=1010</a>

### Other comments
I also tried with pagination.sync, didn't work

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed in 2.2.15
https://codepen.io/jkarczm/pen/ZEGKgPZ
