### ISSUE TITLE
[Documentation] v-footer app sets fixed as true by default

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#9462]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3941.4
**OS:** Windows 10

### Steps to reproduce
Add App to footer tag

### Expected Behavior
Name    Type          Default
fixed      boolean    false

### Actual Behavior
app sets fixed true

### Reproduction Link
<a href="https://codepen.io/joel_rodrigues/pen/yLLboWY" target="_blank"> https://codepen.io/joel_rodrigues/pen/yLLboWY</a>
<a href="https://codepen.io/joel_rodrigues/pen/zYYwdXN" target="_blank"> https://codepen.io/joel_rodrigues/pen/zYYwdXN</a>

### Other comments
I don't know if this is a feature or a bug, since this is not refered in documentation, meanwhile i think that setting app to true, shouldn't override fixed, or should permit to set fixed="false"

**Comment by MajesticPotatoe** [comment]
This is intended. You are permitted to changed it by applying `:fixed="false"`. Will make note of this in the API.

**Comment by joelpro2** [comment]
well, i've tried and it's not working.
https://codepen.io/joel_pro2/pen/WNNjXzM

**Comment by MajesticPotatoe** [comment]
My apologies I think you may be looking for `absolute`
<https://codepen.io/majesticpotatoe-the-bashful/pen/bGGWYOL>

**Comment by joelpro2** [comment]
work like a charm tx

**Comment by alexramsey92** [comment]
![image](https://user-images.githubusercontent.com/6438890/72846710-20599680-3c6f-11ea-8714-9485c48055ff.png)
Absolute isn't really the best fix for this because it just covers content on a scrolling page.
