### ISSUE TITLE
[Bug Report] The type, 'avatar' of <v-skeleton-loader> is always tiled

### ISSUE THREAD

**Issue by jaylee0608** [vuetifyjs/vuetify#9463]
### Environment
**Vuetify Version:** 2.1.6
**Last working version:** 2.1.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.13.6

### Steps to reproduce
https://vuetifyjs.com/en/components/skeleton-loaders#playground

### Expected Behavior
It should be a circle by default.

### Actual Behavior
It's a rounded square.

### Reproduction Link
<a href="https://codepen.io/9e2b065a-daf4-4fb1-88f8-2cbde0b70aa7/pen/gOOWGMy?&editable=true&editors=101" target="_blank">https://codepen.io/9e2b065a-daf4-4fb1-88f8-2cbde0b70aa7/pen/gOOWGMy?&editable=true&editors=101</a>

**Comment by chanlito** [comment]
https://github.com/vuetifyjs/vuetify/issues/9447#issue-511695911

**Comment by DRoet** [comment]
^^ duplicate
