### ISSUE TITLE
[Bug Report] Unable to open context menu for v-treeview on mobile devices

### ISSUE THREAD

**Issue by dukedhx** [vuetifyjs/vuetify#9465]
### Environment
**Vuetify Version:** 2.0.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.13.6

### Steps to reproduce
- long press on the v-treeview item on iOS devices

### Expected Behavior
the context menu should open

### Actual Behavior
nothing happens

### Reproduction Link
<a href="https://codepen.io/anon/pen/QPoYOQ?editors=1010#anon-login" target="_blank">https://codepen.io/anon/pen/QPoYOQ?editors=1010#anon-login</a>

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
