### ISSUE TITLE
[Bug Report] Long text hidden in <v-treeview> cannot emerge when mouse hover on it. 

### ISSUE THREAD

**Issue by yujinghe95** [vuetifyjs/vuetify#9467]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
open link and can see that.

### Expected Behavior
Long text is hidden and can emergy when mouse hover on it, just like the behavior of 'alt' attr of <img/> 

### Actual Behavior
the rest text is hidden and can not emergy

### Reproduction Link
<a href="https://codepen.io/JhinYu/pen/rNNmqVj?editors=1010" target="_blank">https://codepen.io/JhinYu/pen/rNNmqVj?editors=1010</a>

**Comment by rsaleri** [comment]
you can use the v-slot:label to add the title like this:
```html
<template v-slot:label="{ item }">
  <span v-if="item" :title="`${item.name}`">
      {{ item.name }}
   </span>
   <span v-else> loading... </span>
</template>
```
