### ISSUE TITLE
[Bug Report] Wrong positioning for v-card-subtitle in v-dialog

### ISSUE THREAD

**Issue by pverscha** [vuetifyjs/vuetify#9468]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Opera
**OS:** Mac OS 10.15.0, Windows, Linux, Mac OSX

### Steps to reproduce
Use a v-card-subtitle in a v-card that's embedded in a v-dialog. There are specific style-rules that change the positioning of a v-card-title when used in v-dialogs, but these do not exist for the v-card-subtitle, causing it to be positioned too far to the left.

### Expected Behavior
The v-card-subtitle should be positioned as far from the left as the v-card-title when used in a v-dialog.

### Actual Behavior
The v-card-subtitle is positioned more to the left than the v-card-title when used in a v-dialog.

### Reproduction Link
<a href="https://codepen.io/pverscha/pen/gOOWBxJ" target="_blank">https://codepen.io/pverscha/pen/gOOWBxJ</a>

### Comments
As can be seen in this file: https://github.com/vuetifyjs/vuetify/blob/63f128fb6315a5660a54dfed1fbbfe5b3f2b673d/packages/vuetify/src/components/VDialog/VDialog.sass there's a special rule for v-card-title that overrides it's padding when being used in a v-dialog. This rule should also exist for v-card-subtitle.

**Comment by pverscha** [comment]
I forked the repo and I'm currently in the process of fixing this issue myself.

**Comment by WORMSS** [comment]
Oh good, I thought this was me who did something wrong. :)
