### ISSUE TITLE
[Bug Report] Unable to scroll in a multi-select element in v-dialog in Mac Safari browser

### ISSUE THREAD

**Issue by rpankaj** [vuetifyjs/vuetify#9470]
### Environment
**Vuetify Version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Safari 13.0.2
**OS:** Mac OS 10.13.6

### Steps to reproduce
Create a v-dialog element.
Add a multiple select html element inside the body of v-dialog.
Try to scroll in Mac Safari browser. User is not able to scroll the options of select element using mouse. It just hangs up there.

### Expected Behavior
We should be able to scroll inside select element in the dialog using mouse scroll as well.

### Actual Behavior
Unable to scroll inside select element in the dialog.

### Reproduction Link
<a href="https://codepen.io/rpankaj/pen/RwwVdgW?editors=1010" target="_blank">https://codepen.io/rpankaj/pen/RwwVdgW?editors=1010</a>

**Comment by KaelWD** [comment]
Ugh. `window.getComputedStyle(selectElement).overflowY` is `'scroll'` in every sane browser, but safari has to be different and make it `'visible'`.

Workaround is to add `overflow-y: auto` to the select's style. idk if we want to add a special case for this.

**Comment by rpankaj** [comment]
Thanks @KaelWD for workaround
