### ISSUE TITLE
[Bug Report] v-color-picker - 'value': 'TypeError: Cannot read property 'hasOwnProperty' of null'

### ISSUE THREAD

**Issue by jvbianchi** [vuetifyjs/vuetify#9472]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Linux x86_64, Windows

### Steps to reproduce
Use a v-color-picker with v-model set to null

### Expected Behavior
Not have this error

### Reproduction Link
<a href="https://codepen.io/jenaxi/pen/BaaRXyJ?editors=1012" target="_blank">https://codepen.io/jenaxi/pen/BaaRXyJ?editors=1012</a>

**Comment by Deluze** [comment]
Same thing here, works perfect when input is `undefined`. I'm using Vuetify 2.1.7 and this still occurs.

**Comment by dcastrili** [comment]
It worked for me by following the sample code https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/color-pickers/simple/model.vue
