### ISSUE TITLE
[Bug Report] Stuttering loading animation in treeview

### ISSUE THREAD

**Issue by marceloavf** [vuetifyjs/vuetify#9475]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Using treeview normally, when your response take longer to load, you can see the loading animation stuttering.

![gif](https://i.gyazo.com/d29d75b6557ec0924b948f60b1afb3c0.gif)

### Expected Behavior
Flow normally

### Actual Behavior
It's stuttering on the end of the animation, something related to `v-treeview-node__toggle--loading` class

### Reproduction Link
<a href="https://codepen.io/marceloavf/pen/BaaZagm?editors=1010" target="_blank">https://codepen.io/marceloavf/pen/BaaZagm?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
Reduced repro https://codepen.io/jkarczm/pen/vYYzQdo?editors=1010

Workaround https://codepen.io/jkarczm/pen/eYYLQMV?editors=0110
