### ISSUE TITLE
[Bug Report] Editable VOverflowBtn vertical & top horizontal divider behavior

### ISSUE THREAD

**Issue by stuft2** [vuetifyjs/vuetify#9477]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Mac OS 10.15

### Steps to reproduce
Use `editable` attribute on the `v-overflow-btn` in conjunction with `rounded`, `outlined`, or `dense` and hover over the button with the mouse.

### Expected Behavior
With `editable` & `rounded attributes`: the top bar should not extend past the top horizontal edge of the button because it looks funny when you hover over it.
With `editable` & `outlined` attributes: the top bar should be hidden in the case because it makes the top of the overflow button oddly thick. Also, the vertical divider should only be the full height of the button.
With `editable` & `dense` attributes: The vertical bar should only be the height of the button and not overflow on the top or the bottom.

### Actual Behavior
With `editable` & `rounded` attributes: the top bar extends past the top horizontal edge of the button.
With `editable` & `outlined` attributes: the top bar makes the button oddly thick on the top. Also, the vertical divider does not quite reach the top of the button.
With `editable` & `dense` attributes: The vertical divider overflows the top and the bottom button edges.

### Reproduction Link
<a href="https://codepen.io/spencertuft/pen/eYYRzQQ?&editable=true&editors=101" target="_blank">https://codepen.io/spencertuft/pen/eYYRzQQ?&editable=true&editors=101</a>

**Comment by lioneaglesolutions** [comment]
This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
