### ISSUE TITLE
[Bug Report] File input validation - bug with error message

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#9479]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Click clip icon to upload a file.
2. A window with file selection will pop up. Close it.
3. Now file input is red and "f" validation message pops up.

### Expected Behavior
Validation message should display 'File is required' 

### Actual Behavior
Validation message displays 'f' 

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/OJJgjeB" target="_blank">https://codepen.io/mikilll94/pen/OJJgjeB</a>

**Comment by jacekkarczmarczyk** [comment]
`:rules="fileRules"`
