### ISSUE TITLE
[Bug Report] File input validation - error message pops up too early

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#9480]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Click clip icon to upload a file.
2. A window with file selection will pop up and in the same time file input is marked red and validation message pops up.

### Expected Behavior
When selecting a file, validation error should not pop up. We should give the user an opportunity to select a file. Validation error should be displayed when the user closes the window with file selection.

### Actual Behavior
When opening the window with file selection the validation is triggered.

### Reproduction Link
<a href="https://codepen.io/mikilll94/pen/OJJgjeB" target="_blank">https://codepen.io/mikilll94/pen/OJJgjeB</a>

### Other comments
Validation should be triggered when the user closes the window with file selection.

**Comment by jacekkarczmarczyk** [comment]
`:rules="fileRules"`

**Comment by yiyasha15** [comment]
so is this fixed?

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
