### ISSUE TITLE
[Documentation] Text Field Masks Codepen is Busted

### ISSUE THREAD

**Issue by nmummau** [vuetifyjs/vuetify#9482]
### Environment

**Browsers:** Chrome 78.0.3904.70
**OS:** Linux x86_64

### Steps to reproduce
Go to the reproduction link and view the codepen

### Expected Behavior
codepen works

### Actual Behavior
codepen doesn't work

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/text-fields#masks-using-vue-the-mask" target="_blank">https://vuetifyjs.com/en/components/text-fields#masks-using-vue-the-mask</a>

**Comment by paulodiogo** [comment]
They removed the mask feature from v2.0

**Comment by MajesticPotatoe** [comment]
> They removed the mask feature from v2.0

@paulodiogo this is true, however we added support for `vue-the-mask`. However I'm not sure if we can even get a codepen for this to work given how its implemented.

**Comment by andreixk** [comment]
the 3rd party mask plugins don't work properly as vuetify 1.5 used to. this feature removal is the only reason our company cannot upgrade. if we do, it'll be to a different front-end framework, since it'll require rewriting a lot of logic.

**Comment by MajesticPotatoe** [comment]
This example was removed. Masks are planned to return in v3 in some capacity.
