### ISSUE TITLE
[Bug Report] Unable to use native event in v-calendar in @click:more event

### ISSUE THREAD

**Issue by slash006** [vuetifyjs/vuetify#9485]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
1) set event @click:event="eventClicked" and add eventClicked({ nativeEvent, event })
both parameters are defined and work properly
2) set event @click:more="clickedMore" and add clickedMore({ nativeEvent, event })
nativeEvent is undefined

### Expected Behavior
@click:more will provide native JS and vue events. 

### Actual Behavior
native event is undefined

### Reproduction Link
<a href="https://codepen.io/slash006/pen/KKKvPqw" target="_blank">https://codepen.io/slash006/pen/KKKvPqw</a>

**Comment by Suhasnama** [comment]
Hi @ClickerMonkey , i had experienced the same with `@click:day` event 

```
<v-calendar
   ref="calendar"
   @click:day="dayEvent"
></v-calendar>
```
## Type 1
```
<script>
export default {
methods: {
dayEvent({nativeEvent, event}) {
console.log("nativeEvent ", nativeEvent)
console.log("nativeEvent ", event)
}
}
</script>
```
The above code resulted in following output.
```
nativeEvent  undefined
event  undefined
```

## Type 2
```
<script>
export default {
methods: {
dayEvent(nativeEvent, event) {
console.log("nativeEvent ", nativeEvent)
console.log("nativeEvent ", event)
}
}
</script>
```
The above code resulted in following output.
```
nativeEvent  {date: "2020-10-11", time: "", year: 2020, month: 10, day: 11, …}
event  undefined
```

I think the `nativeEvent` is missing for `@click:day` event  also.

**Comment by mattnathan** [comment]
(if you would prefer a separate issue for this, just let me know)

This issue also applies to the mouse* events (mousemove:time for example). I was attempting to recoginise modifier keys while dragging calendar events but without the native event passed into my callback this is very difficult.

What would the implications be for adding this functionality to all events via the `mouse.ts#getMouseEventHandlers` method. I feel it could be added quite easily just before the `$emit` call is issued, not sure of the side effects though.

**Comment by Flomp** [comment]
Is there any update on this? I would like to open a context menu below the day of the month link via `@click:date`. However I cannot set the activator of the menu as I do not have access to nativeEvent property. Is there any way I can do this?

**Comment by chrislo7** [comment]
Any updates or workarounds to this issue? Also need to set an activator.
