### ISSUE TITLE
[Bug Report] <v-list tile> doesn't apply tile styles

### ISSUE THREAD

**Issue by depsimon** [vuetifyjs/vuetify#9487]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.15.0

### Steps to reproduce
Add a v-list component.
Use the `tile` property.
Use the `dark` property (easier to see the border radius)

### Expected Behavior
The border radius of the v-list should be set to 0.

### Actual Behavior
The border radius of the v-list stays.

### Reproduction Link
<a href="https://codepen.io/simondepelchin/pen/qBBXdrX?&editable=true&editors=101" target="_blank">https://codepen.io/simondepelchin/pen/qBBXdrX?&editable=true&editors=101</a>

### Other comments
It seems like the tile property is not taken into consideration. The `v-sheet--tile` is added to the HTML element, but it's properties are not applied because overriden by `v-list` class.

**Comment by MajesticPotatoe** [comment]
duplicate #9380
