### ISSUE TITLE
[Bug Report] Infinite loop with v-autocomplete

### ISSUE THREAD

**Issue by esynaps** [vuetifyjs/vuetify#9489]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Create an autocomplete and set its items to an array of objects as a result of a search.

### Expected Behavior
The search method should be called once

### Actual Behavior
Its is called infinitely

### Reproduction Link
<a href="https://codepen.io/Alex83690/pen/RwwZGvL" target="_blank">https://codepen.io/Alex83690/pen/RwwZGvL</a>

### Other comments
To avoid this problem, the event "@update:search-input" must not be triggered when the input changes because the user has selected an option

**Comment by esynaps** [comment]
The temporary solution that I use and that I do not like:

```
search(term) {
    let match =   this.item && this.selected ? this.items.find((item) => { return item.id === this.selected }) : null
    if((match && match.text === term)) {
        return
    }

    // Start the search
}
```

**Comment by esynaps** [comment]
Any news for this problem?

**Comment by KaelWD** [comment]
A simpler workaround is to use `:search-input.sync` and set a watcher on the data property instead of using the update method directly.

**Comment by Shinigami92** [comment]
I've been struggling with this error for about 3 hours now 😕
And I can't find a workaround that solves my problem
