### ISSUE TITLE
[Bug Report] VImg re-loads each time it enters/leaves viewport

### ISSUE THREAD

**Issue by daniandl** [vuetifyjs/vuetify#9490]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Mac OS 10.14.6

### Steps to reproduce
- Open console / network tab (with cache disabled)
- Scroll up and down
- See image loads / makes requests every time it goes in and out of viewport

### Expected Behavior
The image is loaded once and doesn't request it again

### Actual Behavior
The image gets requested each time it leaves or enters the viewport

### Reproduction Link
<a href="https://codepen.io/daniandl/pen/yLLbZro" target="_blank">https://codepen.io/daniandl/pen/yLLbZro</a>

### Other comments
From the little research I did, it seems the Intersection Observer has something to do with this.

**Comment by Webifi** [comment]
I'm only seeing this if cache is disabled in Chrome's inspector.

**Comment by daniandl** [comment]
> I'm only seeing this if cache is disabled in Chrome's inspector.

The console.log is gone too if you enable cache?
For me the console message is present even with DevTools closed.

**Comment by Webifi** [comment]
Good catch.  I do see it logged in the console with cache enabled, just not in network activity.
