### ISSUE TITLE
[Bug Report] error-messages XSS

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [vuetifyjs/vuetify#9491]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.75
**OS:** Linux x86_64

### Steps to reproduce
Add user input to the :error-messages array.

### Expected Behavior
That the user input is cleaned.

### Actual Behavior
Html / scripts are rendered / executed. 

### Reproduction Link
<a href="https://codepen.io/SingleCore/pen/NWWvpaM" target="_blank">https://codepen.io/SingleCore/pen/NWWvpaM</a>

### Other comments
As a developer we can filters this ourselves, but I assume since v-html exists this shouldn't work.

**Comment by ssipos90** [comment]
How is this a fix? How would someone do XSS in there?
It's a breaking change..

**Comment by johnleider** [comment]
The fix was documented as a BREAKING change. How a user input would get there is besides the point.
