### ISSUE TITLE
[Documentation] text labels display ids in new docs / missing translations

### ISSUE THREAD

**Issue by davidhernandeze** [vuetifyjs/vuetify#9496]
### Environment

**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Enter directly to this page, all the labels are IDs

### Expected Behavior
See spanish labels

### Actual Behavior
See internal Ids for labels 

### Reproduction Link
<a href="https://vuetifyjs.com/es-MX/" target="_blank">https://vuetifyjs.com/es-MX/</a>

![image](https://user-images.githubusercontent.com/22482495/67730832-ddfc2280-f9bb-11e9-9232-277f22d8f2fb.png)

**Comment by MajesticPotatoe** [comment]
Note: not limited to es-MX. we need to do an update to/from crowdin as there were some file restructuring that has caused this.

**Comment by davidhernandeze** [comment]
Yes, I noticed it later, I hope it solves quickly

**Comment by MajesticPotatoe** [comment]
One thing that may also help is to do a cache clear, and see if that fixes it.
