### ISSUE TITLE
[Documentation] part of zh-Hans documentation not rendering text properly 

### ISSUE THREAD

**Issue by b2nil** [vuetifyjs/vuetify#9497]
### Environment

**Browsers:** Chrome 76.0.3809.132, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
1. open the reproduction link.
2. you should see that the page is showing some property names like `GettingStarted.BrowserSupport.ie11Header` instead of the actual text.
3. check the side navigation, there are more cases like this.

### Expected Behavior
The localized texts should render properly.

### Actual Behavior
Text not redered properly, instead, the following is displayed:
> Browser support
> GettingStarted.BrowserSupport.heading
> 
> GettingStarted.BrowserSupport.headingText

> GettingStarted.BrowserSupport.ie11Header
> 
> GettingStarted.BrowserSupport.ie11Text1

### Reproduction Link
<a href="https://vuetifyjs.com/zh-Hans/getting-started/browser-support" target="_blank">https://vuetifyjs.com/zh-Hans/getting-started/browser-support</a>

### Other comments
Looks like there are no Chinese localization for these texts for the time being. In this case, the original English texts should be rendered, instead of some property names.

**Comment by MajesticPotatoe** [comment]
duplicate #9496
