### ISSUE TITLE
Keyboard Navigation?

### ISSUE THREAD

**Issue by jeromu** [vuetifyjs/vuetify#95]
Any plan to add keyboard navigation support for desktop?  For example, close drop down when pushing ESC, among other things...

**Comment by johnleider** [comment]
I have not considered it but it is a good idea. Potentially something for post 1.0 release. .

**Comment by johnleider** [comment]
After thinking this over, this functionality is something the dev could implement if they wanted to, but not something I think I'll implement as part of the core package.
