### ISSUE TITLE
[snackbar]timeout doesn't work if snackbar is visible defaultly

### ISSUE THREAD

**Issue by Tang-RoseChild** [vuetifyjs/vuetify#950]
### Versions
vue:2.3.3
vuetify:0.13.1

### What is expected and actually happened?
because some times, need to notify some thing after enter a new page.when i show snackbar defaultly, the property "timeout" doesn't work.

And i think the watch doesn't work.source code below:
https://github.com/vuetifyjs/vuetify/blob/master/src/components/snackbars/Snackbar.js#L54
```

watch: {
isActive () {
 clearTimeout(this.activeTimeout)
  
if (this.isActive && this.timeout) {
  this.activeTimeout = setTimeout(() => (this.isActive = false), this.timeout)
}
}
}
```

**Comment by johnleider** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
