### ISSUE TITLE
[Feature Request] add loading for v-edit-dialog when click the save button

### ISSUE THREAD

**Issue by ly525** [vuetifyjs/vuetify#9502]
### Problem to solve
If the save action of the v-edit-dialog is an asynchronous action, I could not add a loading indicator to tell the user that the action needs time to finish  

### Proposed solution
add save-loading prop for v-edit-dialog

**Comment by skortabeast** [comment]
Use dialog loader and check Loading state in asych method, show dialog with message and after success set Loading to false and hide dialog

**Comment by johnleider** [comment]
This component is going away for v3 and won't be revisited in v2.x.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
