### ISSUE TITLE
[Feature Request] DataList 'Vuetify Style'

### ISSUE THREAD

**Issue by Paulsky** [vuetifyjs/vuetify#9507]
### Problem to solve
I'm looking for a 'Vuetify style' HTML5 datalist component. Please see the HTML 5 specs of 'datalist' here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

So it's pretty similar as the `<v-autocomplete />` component, but the difference is (just like the native HTML element) it accepts custom input value, if the value is missing from the list.

For example; if you look at this W3schools example: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist. When you for example type in 'Brave Browser' in the input field and submit it, that value is also accepted.

### Proposed solution
Maybe we could provide a  'list' attribute for `<v-text-field />` component, or add an 'accept-custom' attribute to the `<v-autocomplete />` component, to accept custom input.

**Comment by Webifi** [comment]
Isn't that what [v-combobox](https://vuetifyjs.com/en/components/combobox) is all about?

**Comment by Paulsky** [comment]
@Webifi thank you! You are right, I misunderstood the `<v-combobox />` component.
