### ISSUE TITLE
[Bug Report] v-treeview-node

### ISSUE THREAD

**Issue by vanillamasonry** [vuetifyjs/vuetify#9508]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
Just run the codepen and watch the browser console

### Expected Behavior
No console error

### Actual Behavior
"[Vue warn]: Error in created hook: 'TypeError: this.nodes[e] is undefined'

found in

---> &lt;VTreeviewNode&gt;
       &lt;VTreeview&gt;
         &lt;VApp&gt;
          &lt;Root&gt;"

### Reproduction Link
<a href="https://codepen.io/Paul_1001/pen/YzzrKoO" target="_blank">https://codepen.io/Paul_1001/pen/YzzrKoO</a>

**Comment by johnleider** [comment]
This is not a public component. It requires a treeview to inject in order to work.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
