### ISSUE TITLE
[Documentation] Vee-validate example is outdated and it is not working

### ISSUE THREAD

**Issue by Mikilll94** [vuetifyjs/vuetify#9509]
### Environment

**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
1. Scroll page to the vee-validate example.
2. Click on "name" field and then click somewhere else.
3. **Validation is not triggered although "name" field is required.**
4. Click "< >" icon to show "code".
5. **As you can see this example uses "v-validate" directive which was removed in "3.x.x"**
6. Click on "Documentaion" link above the example.
7. **It points to an incorrect website. Here is the correct website:**
https://logaretm.github.io/vee-validate/

### Expected Behavior
Vee-validate example should work and it should use the latest version (3.x.x). Also, the link to the documentation should be correct

### Actual Behavior
Vee-validate example is not working. The example uses the older version of vee-validate (2.x.x). Also, the link to the documentation is not correct.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/forms#forms" target="_blank">https://vuetifyjs.com/en/components/forms#forms</a>

**Comment by MajesticPotatoe** [comment]
Duplicate #8714
