### ISSUE TITLE
[Bug Report] v-checkbox, v-switch initial value=true doesn't work

### ISSUE THREAD

**Issue by mathe42** [vuetifyjs/vuetify#9510]
### Environment
**Vuetify Version:** 2.1.7
**Last working version:** In 1.x it worked not shure about 2.x
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
just open codepen link

### Expected Behavior
v-switch, v-checkbox should be shown as active

### Actual Behavior
v-switch, v-checkbox not shown as active

### Reproduction Link
<a href="https://codepen.io/mathe42/pen/jOOGVmR" target="_blank">https://codepen.io/mathe42/pen/jOOGVmR</a>

**Comment by Webifi** [comment]
I think it's more of a documentation error.   I believe it's "input-value" instead of "value", or use v-model.

See:
https://codepen.io/webifi/pen/bGGogqd

**Comment by mathe42** [comment]
Oh thanks...

**Comment by jacekkarczmarczyk** [comment]
> I've often wondered why many of the Vuetify components switched over to "input-value" in 2.x.

Which components? Selection controls are using input-value in 1.x as well

**Comment by Webifi** [comment]
Were they?  Maybe it's just the v-chip that changed from "selected"?  I seem to remember changing more as I was transitioning to 2.x, but I guess my imperfect memory is betraying my age.

**Comment by ekosynth** [comment]
Just got caught out by this. Don't really understand the difference between value and input-value in this context.
