### ISSUE TITLE
[Bug Report] Data Table Sorting Wrong

### ISSUE THREAD

**Issue by 24jr** [vuetifyjs/vuetify#9515]
### Environment
**Vuetify Version:** 2.1.7
**Last working version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Safari 13.0.2
**OS:** Mac OS 10.14.6

### Steps to reproduce
Just sort the columns from header

### Expected Behavior
Sorts high negative to zero to high positive. Also scientific notation sort by actual values not the leading scientific notation value

### Actual Behavior
sorts low neg to high neg then low pos to high pos

### Reproduction Link
<a href="https://codepen.io/24jr/pen/BaawddR" target="_blank">https://codepen.io/24jr/pen/BaawddR</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/43adae8591f9b48b05c022e1f7c93abeddc76a4f

**Comment by Aramis13** [comment]
Sure. I'm on it.
Which branch to work on?

**Comment by nekosaur** [comment]
master

**Comment by Aramis13** [comment]
👍

**Comment by Aramis13** [comment]
So after some research theirs a few issues:

- Intl.Collator _numeric_ does not take in to account negative numbers and has troubles with decimal numbers.

- The isNaN() or Number.isNaN() functions does not work with number formats except 0-9. 

- Intl.Collator _numeric_ does manage to sort according to locale (Excluding negative and decimal numbers), but i didn't found any off the shelf solution for detecting if unique locales string isNaN.

Possible solutions:

1. Revert to use Number(sortA) - Number(sortB), This solution wont take in to consideration number formats except 0-9.

2. Implement some util function that convert unique locale numeric formats to 0-9 format.

Any thoughts?

**Comment by nekosaur** [comment]
My initial thought is to revert to the old behavior for numbers, since it's been in place for a long time without issue.

**Comment by timothymarois** [comment]
I found this issue too and updated from `2.1.9` to `2.1.11` and the sorting has been fixed.
