### ISSUE TITLE
[Bug Report] input field in v-autocomplete should be autocomplete="off" instead of disabled

### ISSUE THREAD

**Issue by samuelba** [vuetifyjs/vuetify#9516]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Linux x86_64

### Steps to reproduce
Write many many times e.g. "Comboboxes" and after a while Google Chrome gives you a second "dropdown" with "Comboboxes" this is because the input field is like this:

```
<input id="input-4" type="text" autocomplete="disabled">
```

but should be rather like this:

```
<input id="input-4" type="text" autocomplete="off">
```

### Expected Behavior
no extra dropdown from Chrome

### Actual Behavior
second overlaying dropdown from Chrome

### Reproduction Link
<a href="https://codepen.io/samuelba/pen/eYYGGeN" target="_blank">https://codepen.io/samuelba/pen/eYYGGeN</a>

**Comment by melbahja** [comment]
Yes are right, yesterday chrome show me the autofill menu, and i think the same issue exists in v-select too. I will open a new PR to fix this later today :smile:

**Comment by melbahja** [comment]
About disabling autocomplete on MDN:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
