### ISSUE TITLE
[Bug Report] $vuetify.goTo is broken in IE11

### ISSUE THREAD

**Issue by mrkswrnr** [vuetifyjs/vuetify#9517]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.8
**Browsers:** Internet Explorer
**OS:** Windows

### Steps to reproduce
Call `$vuetify.goTo(0)` in IE11

### Expected Behavior
Scroll to top

### Actual Behavior
Nothing happens - no error reported

### Reproduction Link
<a href="https://codepen.io/mrkswrnr/full/OJJxQVQ" target="_blank">https://codepen.io/mrkswrnr/full/OJJxQVQ</a>

### Other comments
You have to explicitly pass the container element for it to work in IE11:
```javascript
$vuetify.goTo(0, {container: document.documentElement})
```

This is because IE11 does not know document.scrollingElement but defines document.body (which is only the default scrollingElement in quirks mode). Therefore this [line](https://github.com/vuetifyjs/vuetify/blob/b7f3c4eb43bda731907c57d69d604713a3158727/packages/vuetify/src/services/goto/index.ts#L21) in GoTo Service uses the wrong element for scrolling.

As a workaround we are using [scrollingElement Polyfill](https://github.com/mathiasbynens/document.scrollingElement) as it appears to be quite complex to find the appropriate element.

**Comment by sh7dm** [comment]
@DRoet do you use Windows? If not, just unassing yourself. Could you please investigate and try to fix this?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
