### ISSUE TITLE
minor styling issue on scrollable v-tabs

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#952]
there is a small styling issue on scrollable v-tabs if they are displayed in mobile view:
* click to the right to show other tabs
* click to the left and then the left icon is gone but it cuts off the tab-item
<img width="375" alt="screen shot 2017-07-11 at 13 58 03" src="https://user-images.githubusercontent.com/489221/28053091-3e496654-6641-11e7-8449-308b6ebba336.png">

**Comment by nekosaur** [comment]
@dohomi Can you post your specific markup, and the window width?

**Comment by dohomi** [comment]
@nekosaur let me do some more testing.. somehow I think it belongs to the outside padding which affects the tab header

**Comment by nekosaur** [comment]
Reopen this if the issue still persists
