### ISSUE TITLE
[Documentation] online documents does not show deprecated components

### ISSUE THREAD

**Issue by nadihighlander** [vuetifyjs/vuetify#9520]
### Problem to solve
According to this page "v-toolbar" is deprecated in version 2.0 :
https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0-beta.0

But it is not mentioned in online document :
https://vuetifyjs.com/en/components/toolbars

if it is deprecated, "DEPRECATED" state must be clearly shown in online documents.
Or I'm missing something ?

### Proposed solution
"DEPRECATED" state be clearly visible in online documents.

**Comment by MajesticPotatoe** [comment]
`v-toolbar` is not deprecated. As a part of 2.0 some of its functionality (namely app related functions) were moved a new component `v-app-bar`, which extends `v-toolbar`. The component itself still function in every other aspect.

You should also be referring to official release notes for 2.0 and the upgrade guide. Betas are known to change and dont always reflect official release (and there was 9 betas).
<https://vuetifyjs.com/en/getting-started/releases-and-migrations>
