### ISSUE TITLE
[Bug Report] role="button" attribute no longer give 'cursor: pointer' style

### ISSUE THREAD

**Issue by engyii** [vuetifyjs/vuetify#9521]
### Environment
**Vuetify Version:** 2.1.7
**Last working version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Mac OS 10.15

### Steps to reproduce
add role="button" to any html tag. 

### Expected Behavior
[role="button"] selector in styles/generic/_reset.scss should match the attribute

### Actual Behavior
role="button" don't match the selector from styles/generic/_reset.scss. A comma is missing after [type="submit"] in the selector definition.

https://github.com/vuetifyjs/vuetify/blob/3a9fdc292af97c98be91c014bde1fac40a96e865/packages/vuetify/src/styles/generic/_reset.scss#L146

### Reproduction Link
<a href="https://codepen.io/engyii/pen/VwwMBaB" target="_blank">https://codepen.io/engyii/pen/VwwMBaB</a>

**Comment by mattgreenfield** [comment]
@engyii - may I ask why you don't just use a `<button>`?

**Comment by engyii** [comment]
Sometimes you add click events to diverse Elements, not just buttons (a v-row, v-col or another custom components) and want them to have a cursor: pointer style to signal it’s clickable.. 

I could have added a class and a cursor:pointer manually but saw that role=“button” in vuetify css was just doing that (And it’s makes sense, the elements takes the role of a button) so I used it... it then broke in vuetify migration from stylus to sass... and that’s a bug if I’m not mistaken :)
