### ISSUE TITLE
[Bug Report] The rows per page dropdown in the data table footer does not display properly in IE 11

### ISSUE THREAD

**Issue by vincent-hould** [vuetifyjs/vuetify#9527]
### Environment
**Vuetify Version:** 2.1.4
**Last working version:** 1.5.19
**Vue Version:** 2.6.10
**Browsers:** Internet Explorer
**OS:** Linux x86_64

### Steps to reproduce
* Open the data table documentation page on Internet Explorer 11.
* Look at one of the example widgets.
* Check the "Rows per page" selector dropdown.

### Expected Behavior
The selected number of items per page is displayed and when clicked the list of available page sizes appears.

### Actual Behavior
The input only contains the arrow icon, without any value. When clicked, the dropdown list is displayed but the items are just empty space.

### Reproduction Link
<a href="https://codepen.io/Zheios/pen/zYYEQrY" target="_blank">https://codepen.io/Zheios/pen/zYYEQrY</a>

### Other comments
From what I have seen, it is an issue with the input width for the selected item. The value does not appear as the overflow is set to hidden and the element is too narrow to fit the text. Since the width comes from the parent elements, I'm guessing IE must compute the size of the elements differently than other browsers.

For the dropdown list, the issue seem to come from the padding applied to the items of the list, which moves the texts to the right, outside the boundaries of the dropdown box itself.

**Comment by jacekkarczmarczyk** [comment]
@vincent-hould can you provide a screenshot of the issue?

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
