### ISSUE TITLE
[Bug Report] Clear causing error when using v-date-picker with v-text-field

### ISSUE THREAD

**Issue by hopefeda** [vuetifyjs/vuetify#9529]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Linux x86_64

### Steps to reproduce
Create a vDatePicker with range=true in menu using a clearable vTextField as explained in the docs. Select any date/range and the click the clear button in the vTextField 

### Expected Behavior
vTextField clear button should set the target v-model to an emtpy array [ ] to prevent array errors when target v-model is an array

### Actual Behavior
vTextField clear button sets the target v-model to null which causes the error. This works fine for a vDatePicker without range property because target v-model is not an array, nor does the vDatePicker itself expect an array

### Reproduction Link
<a href="https://codepen.io/hope_feda/pen/abbVdoj" target="_blank">https://codepen.io/hope_feda/pen/abbVdoj</a>

### Other comments
I tried setting the target v-model to an empty array [ ] using the click:clear event. However, this did not work because apparently click:clear doesn't override the default behaviour of setting the target v-model to null.
I'm not sure if the solution is that the clear event should set the target v-model to an empty array if its an array originally(null when not an array), or if click:clear event should override default behaviour so we can customize how its cleared.

**Comment by EvgenTN** [comment]
The same issue. Is there any solution?

**Comment by jacekkarczmarczyk** [comment]
Range date picker could accept an undefined as en empty value, for now you can just avoid using v-text-field to clear v-date-picker's value
https://codepen.io/jkarczm/pen/MWYGrNB

**Comment by KaelWD** [comment]
I'd consider this a bug, range shouldn't split a string to an array like that.
