### ISSUE TITLE
can't use synchronous ajax with ssr

### ISSUE THREAD

**Issue by miyalee** [vuetifyjs/vuetify#953]
hey there,
`$ vue init vuetifyjs/webpack-ssr` 
I run this to init a project, I have some code like this:
```
<span>{{ text || 'abc'}}</span>
......
data() {
    return {
        text: null
    }
},
mounted() {
    $.ajax({
         type: 'get',
         async: false,
         url: '/api/to/url/path',
         success: function(data) {
               if(data.code === 0) {
                    self.text = 'def'
               }
         }
    })
}
```

then I get a not match warn:
<img width="1098" alt="2017-07-11 2 01 41" src="https://user-images.githubusercontent.com/18900447/28053518-6fa17af0-6643-11e7-9940-f67d00aea85a.png">
`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

is it not support sync ？

( I think this is a problem of vue-ssr, but I can't found a correct repository )

**Comment by chriswa** [comment]
https://github.com/vuetifyjs/webpack-ssr

**Comment by miyalee** [comment]
@chriswa  3q~!

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Vuetify is fully SSR and async compatible. Please direct all questions to the official [gitter](https://gitter.im/vuetifyjs/Lobby/~chat#).
