### ISSUE TITLE
[Feature Request] show-items-per-page

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#9531]
### Problem to solve
user can't hide items-per-page option in v-data-footer

### Proposed solution
add new props 
name:  show-items-per-page,
type: boolean,
default: true

**Comment by ibrahimBeladi** [comment]
I would suggest changing it to: hide-items-per-page with a default value of false. So that the usage is `hide-items-per-page` instead of `:show-items-per-page="false"`

**Comment by jacekkarczmarczyk** [comment]
Just pass the `footer-props` with `itemsPerPageOptions` set to 1-element array (or empty array if you want to display all items)
https://codepen.io/jkarczm/pen/JjovMzq?editable=true&editors=101
