### ISSUE TITLE
[Feature Request] 关于data-table组件固定表头的建议

### ISSUE THREAD

**Issue by ltlwill** [vuetifyjs/vuetify#9537]
### Problem to solve
data-table 组件的表头能固定，不随body滚动

### Proposed solution
data-table 组件的表头不能固定，设置了height属性固定表格的高度之后，出现滚动条时表头会随着body一起滚动，如果能固定表头就更好了

**Comment by ltlwill** [comment]
The header of the data-table component cannot be fixed. After the height attribute is set to the height of the table, the header will scroll with the body when the scroll bar appears. If the header can be fixed, it is better.

**Comment by ltlwill** [comment]
![{3A933D06-B34C-4459-A0BE-252B254502D0}_20191101180059](https://user-images.githubusercontent.com/16695334/68017343-7a326c00-fcd1-11e9-91d6-0e3495e8e0d6.jpg)

**Comment by KaelWD** [comment]
Please use the bug report template and english.
