### ISSUE TITLE
[Feature Request] dismissable event

### ISSUE THREAD

**Issue by RSpeekenbrink** [vuetifyjs/vuetify#9538]
### Problem to solve
When you add the dismissable prop to an Alert or Snackbar the only way to know if the form has been dismissed is by checking the model value. It would be nice to know if the user actually dismissed it themselves by adding a dismissed event when the dismiss button has been clicked.

### Proposed solution
Add a dismissed event for when the dismiss button has been clicked for Alerts and Snackbars.

**Comment by Estradiaz** [comment]
isn't this already implemented? https://github.com/vuetifyjs/vuetify/blob/392d49817554070f2d958899fd24427fba287267/packages/vuetify/src/mixins/toggleable/index.ts#L28

**Comment by RSpeekenbrink** [comment]
Is it missing in the docs then? Or does it fire the input event?

**Comment by MajesticPotatoe** [comment]
`@input` does fire when using dismiss button is clicked

**Comment by RSpeekenbrink** [comment]
It's kind of a misleading name tbh. Maybe an idea to change that to ```@active``` or ```@show``` for these components?

**Comment by Estradiaz** [comment]
IMO changing this might break tons of apps - as a workaround one can either extend this component and override the `toggable` mixin with a new call of `toggleable factory` in mixin option or `watch` the `v-model` value - it is common that `v-model` triggers `input` event

**Comment by ggedde** [comment]
We still need an event on v-snackbar though when the timeout fires.

**Comment by RSpeekenbrink** [comment]
> IMO changing this might break tons of apps - as a workaround one can either extend this component and override the `toggable` mixin with a new call of `toggleable factory` in mixin option or `watch` the `v-model` value - it is common that `v-model` triggers `input` event

true about breaking a lot of apps. For the workarounds the only one that works for my use-case is to override the toggable mixin. The point is that I want to know if the component got dismissed by user-action so the watch method doesn't provide that assurance. As other `workaround` I can just use ```@input``` for now, it's just kind of a misleading name on one hand, but on the other it's about user input so if you look at it that way ```@input``` is correct.

**Comment by MajesticPotatoe** [comment]
> timeout

`@input` fires when `v-snackbar` times out

**Comment by MajesticPotatoe** [comment]
To sum up this thread: as it stands now here are your current options:
**`v-alert`**: `@input` or use `close` slot with btn click handler
**`v-snackbar`**: `@input` for timeout + btn click handler for user

chances of us renaming `@input` are slim (and then it wouldn't be till at least next major) as its an event used across many components and would be a breaking change.

**Comment by jacekkarczmarczyk** [comment]
You can distinct snackbar whether it was closed by user or timeouted if you control the button (https://codepen.io/jkarczm/pen/zYYWbzO?editors=1010) but i don't see the way to do it for dismissable alert

@MajesticPotatoe I don't think the renaming of `@input` is necessary, there could be just additional events

**Comment by ggedde** [comment]
@MajesticPotatoe Thanks, I think it just needs to be added to the documentation.

**Comment by MajesticPotatoe** [comment]
> @MajesticPotatoe Thanks, I think it just needs to be added to the documentation.

d177c3b

**Comment by MajesticPotatoe** [comment]
Closing as both `@input` and clickable events are enough to suffice for this
