### ISSUE TITLE
[Feature Request] v-calendar event slot

### ISSUE THREAD

**Issue by jappyjan** [vuetifyjs/vuetify#9539]
### Problem to solve
Right now, if a provided event has a start-date including a time, a prefix to the event-name will be displayed in the calendar view. 

e.g. the start is '2019-09-10 13:00:00' and the name is 'test-event', the displayed name will be "1p test-even"

this is fine for some applications (as long as they are english localized).
but for some others there should be an option to format the prefix by ourself.

### Proposed solution
make the prefix an optional property of v-calendar so we can provde a function or string as a replacement.

**Comment by Estradiaz** [comment]
Isn't this implemented? https://github.com/vuetifyjs/vuetify/blob/392d49817554070f2d958899fd24427fba287267/packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts#L99

**Comment by jappyjan** [comment]
oh i'm sorry. didn't look up the source code.
i only looked at the documentation of v-calendar.
