### ISSUE TITLE
[Bug Report] V-icon CSS rule for visibility has a lag

### ISSUE THREAD

**Issue by maratumba** [vuetifyjs/vuetify#9541]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Mac OS 10.14

### Steps to reproduce
Use CSS `visibility` property and `:hover` selector to hide / show `v-icon`.

### Expected Behavior
Icons should disappear and appear instantly based on hover state.

### Actual Behavior
There is a significant delay in hiding the icon after hover state changes.

### Reproduction Link
<a href="https://codepen.io/gulyamani/pen/LYYeEmo" target="_blank">https://codepen.io/gulyamani/pen/LYYeEmo</a>

**Comment by chridmeister** [comment]
You can "fix" this by removing the vuetify transition - add the style "transition: none;" to the v-icon:   https://codepen.io/chridmeister/pen/XWWOMWR

**Comment by jacekkarczmarczyk** [comment]
or
```css
.v-icon {
  transition: .3s cubic-bezier(.25,.8,.5,1), visibility 0s;
}
```
to disable just `visibility` transition
