### ISSUE TITLE
[Bug Report] VStepper animation bug on iOS 9 Safari

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#9542]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Since Codepen does not work with iOS 9, I could not provide a reproduction link. You will need to create a simple app using a stepper with a few steps.

### Expected Behavior
When changing steps, the old step should close using an animation and the new step should open using an animation.

### Actual Behavior
When changing steps, the old step closes instantly without any animation and the new step opens using an animation then closes using an animation then opens again using an animation.

### Reproduction Link
<a href="https://codepen.io/ChrisLandowski/pen/OJJzNYE?&editable=true&editors=101" target="_blank">https://codepen.io/ChrisLandowski/pen/OJJzNYE?&editable=true&editors=101</a>

### Other comments
The stepper animations work fine on all newer versions of iOS Safari.

**Comment by lioneaglesolutions** [comment]
### Stale Issue

This issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).
