### ISSUE TITLE
[Documentation] V1.x documentation seems to be broken

### ISSUE THREAD

**Issue by juanesarango** [vuetifyjs/vuetify#9543]
### Environment

**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.14.6

### Steps to reproduce
Try to browse documentation from version v1.x. Or just click the example link https://v1.vuetifyjs.com/en/components/grids#grid-system

### Expected Behavior
It should display the docs v1.x

### Actual Behavior
It shows 404 Error

### Reproduction Link
<a href="https://v1.vuetifyjs.com/en/components/grids#grid-system" target="_blank">https://v1.vuetifyjs.com/en/components/grids#grid-system</a>

**Comment by MajesticPotatoe** [comment]
proper link is `https://v1.vuetifyjs.com/en/layout/grid`
