### ISSUE TITLE
[Documentation] Stepper page not showing any steppers under iOS 9

### ISSUE THREAD

**Issue by ChrisLandowski** [vuetifyjs/vuetify#9544]
### Environment

**Browsers:** Safari
**OS:** iOS

### Steps to reproduce
Visit the steppers page using iOS 9 Safari.

### Expected Behavior
Steppers should appear.

### Actual Behavior
Steppers do not appear.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/steppers#steppers" target="_blank">https://vuetifyjs.com/en/components/steppers#steppers</a>

**Comment by johnleider** [comment]
Looks correct to me.

![image](https://user-images.githubusercontent.com/9064066/72546125-d415ed00-384f-11ea-96a0-1f3453bd6bb9.png)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
