### ISSUE TITLE
[Feature Request] Stubs for shallowMount

### ISSUE THREAD

**Issue by Stoom** [vuetifyjs/vuetify#9547]
### Problem to solve
Some vuetify components use slots which are not rendered by default with `shallowMount`

### Proposed solution
Include stubs that only render the slots.

```javascript
const wrapper = shallowMount(CustomComponent, {
    store, localVue, vuetify, stubs: {
        VTextField: '<v-text-field-stub><slot name="prepend"></slot></v-text-field-stub>',
    },
});
```

**Comment by johnleider** [comment]
Can you provide an example of what this would help?

**Comment by Stoom** [comment]
I actually think this may be addressed with this PR https://github.com/vuejs/vue-test-utils/issues/1261

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
