### ISSUE TITLE
[Feature Request] Add slot for (.v-counter) in inputs like (v-text-field)

### ISSUE THREAD

**Issue by x0911** [vuetifyjs/vuetify#9548]
### Proposed solution
```vue
<template v-slot:counter="{ current_length, max }">
  <custom-element>
    {{ current_length }}
    <custom-separator></custom-separator>
    {{ max }}
  </custom-element>
</template>
```
> Developers might also use this slot to display some messages in the other corner beside the (**.v-messages**) slot.

Thank you :)

**Comment by jacekkarczmarczyk** [comment]
See also https://github.com/vuetifyjs/vuetify/pull/8802

**Comment by x0911** [comment]
> 
> 
> See also #8802
--
Not alike.
![image](https://user-images.githubusercontent.com/31364936/68529769-a9b52a00-030a-11ea-94eb-1d5adb9da1ee.png)

Using a slot will offer more customization.

**Comment by jacekkarczmarczyk** [comment]
I know, I didn't say that that PR solves your issue, slots are mentioned there in comments though

**Comment by Shinigami92** [comment]
My PR solves most problems and was easy to implement
A slot for counter would need much more to do and needs also discussions about what you can do with them 
Because potentially you could break out of material design guidelines with them

**Comment by jelle-eastground** [comment]
An extra slot for the counter text would be great. The proposed solution would be perfect for me.
