### ISSUE TITLE
[Feature Request] on method for expansion-panel-header slots

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#9551]
### Problem to solve
Right now, clicking anywhere in the content of `v-expansion-panel-header` toggles `v-expansion-panel-content`. If you want only a specific button within the header to trigger this behavior, this is not possible right now.

### Proposed solution
Similar to the `v-tooltip` slots, provide a `on` parameter to both, the `default` and the `actions` slot to make this customizable.

**Comment by johnleider** [comment]
This is now possible in Vuetify 3

```html
<v-expansion-panel-title>
  This is a test of <v-btn @click.stop="model = 1">Click me</v-btn>
</v-expansion-panel-title>
```

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
