### ISSUE TITLE
[Documentation] Install Vuetify on Laravel

### ISSUE THREAD

**Issue by upathissa** [vuetifyjs/vuetify#9553]
### Problem to solve
It is extremely difficult to install vuetify on laravel at this moment.

### Proposed solution
Update documentation for Laravel as well.

**Comment by upathissa** [comment]
I'm trying to install Vuetify on the Laravel 6 project. But it doesn't work as usual while I'm following the steps in documentation under "Webpack install" section. It shows a tons of errors on console like
 `"app.js:41253` [Vue warn]: Unknown custom element: <v-app> - did you register the component correctly? For recursive components, make sure to provide the "name" option."`

But after changing `import Vuetify from 'vuetify/lib'` to `import Vuetify from 'vuetify` it renders the page without any js errors. But it didn't load styling correctly.

(Actually, I didn't follow the "webpack.config.js" configuration step. It is a little bit difficult thing to do it on laravel for me.)

**Comment by DRoet** [comment]
FYI this is a pretty good starter-project that works with vuetify 2.x

https://github.com/nekosaur/laravel-vuetify

**Comment by nicomoya123** [comment]
i am using it on my laravel project, i can upload a basic template if you want

**Comment by rajhaq** [comment]
put this in plugins/vuetify.js

import 'vuetify/dist/vuetify.min.css'

**Comment by Nothing-Works** [comment]
@upathissa do you want to try this.
I create a [package](https://github.com/Nothing-Works/vuetifyjs-mix-extension). It does everything for you.

You can try it, and let me know if it's working for you.

And here is [laravel setup](https://github.com/Nothing-Works/vuetifyjs-mix-extension/blob/master/laravel.md)

It's also on [laravel-mix.com](https://laravel-mix.com/extensions/vuetifyjs-mix-extension)

**Comment by MajesticPotatoe** [comment]
@Nothing-Works Would say laravel instructions can be added to quick start if you are looking to help provide the docs. Seems pretty straight forward, install laravel, laravel-mix package, configure, and then bootstrap vuetify like normal.

**Comment by Nothing-Works** [comment]
@MajesticPotatoe yes, I would like to help. just one thing there are some overlapping steps between `laravel` and `webpack` install like:
```js
// src/plugins/vuetify.js

import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify)

const opts = {}

export default new Vuetify(opts)
```
and

```js
// src/main.js

import Vue from 'vue'
import vuetify from '@/plugins/vuetify' // path to vuetify export

new Vue({
  vuetify,
}).$mount('#app')
```
Also for font install. Do you think that It's ok to duplicate these? Or do you have some recommendations? Thanks.

**Comment by MajesticPotatoe** [comment]
For those you could simply refer to the already existing steps or just reuse the snippet

**Comment by denise92** [comment]
I have same issue, laravel is only work with vuetify, 
when I try to use  vuetify-loader, it's showing (`Unknown custom element: <v-app>`)
and this is work with vuetify-loader to me~

```
// webpack.mix.js

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   
mix.webpackConfig({
       plugins: [
           new VuetifyLoaderPlugin({
               options: {}
           }),
       ]
   })
   .version()
   .sourceMaps()
```

**Comment by Hazard4233** [comment]
I have read your articles carefully.
I have same problems for integrating vuetify on laravel 7
Please send me correct way for vuetify and laravel
thanks

**Comment by Nothing-Works** [comment]
@Hazard4233 check https://github.com/Nothing-Works/vuetifyjs-mix-extension and https://github.com/Nothing-Works/vuetifyjs-mix-extension/blob/master/laravel.md
