### ISSUE TITLE
[Documentation] Pre-made layouts - Google contact popup dialog styling error

### ISSUE THREAD

**Issue by upathissa** [vuetifyjs/vuetify#9554]
### Environment

**Browsers:** Opera 64.0.3417.83
**OS:** Linux x86_64

### Steps to reproduce
(On the documentation)Getting started -> pre-made layouts -> Google Contact
click on "+" icon on the bottom right corner
the popup dialog has some padding issues.

### Expected Behavior
Should have some space around the dialog box

### Actual Behavior
It hasn't enough space around the form and dialog outlines

### Reproduction Link
<a href="https://vuetifyjs.com/en/examples/layouts/google-contacts" target="_blank">https://vuetifyjs.com/en/examples/layouts/google-contacts</a>

### Other comments
Without this space, its looks like very odd.

**Comment by MajesticPotatoe** [comment]
`v-app-bar-nav-icon` just needs to moved outside of the `v-toolbar-title` and source links need to be fixed.
