### ISSUE TITLE
[Bug Report] Vuetify textarea mishandling null/undefined input on SSR (Nuxt)

### ISSUE THREAD

**Issue by perezd** [vuetifyjs/vuetify#9559]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Linux x86_64

### Steps to reproduce
Set text area to a value of null/undefined and render component using SSR mode.

### Expected Behavior
Would expect null/undefined values to be not stringified and set as internal value.

### Actual Behavior
null/undefined values appear to be stringified and set as initial value in SSR mode.

### Reproduction Link
<a href="https://codesandbox.io/s/codesandbox-nuxt-vdcv8" target="_blank">https://codesandbox.io/s/codesandbox-nuxt-vdcv8</a>

### Other comments
This is limited to how Vue is interacting w/ Nuxt SSR from what I can tell, originally I thought this was a Nuxt issue but they told me it isn't and to file it here instead. (https://github.com/nuxt/nuxt.js/issues/6639)

If I wrap the v-textarea component in client-only the problem disappears, definitely a SSR issue.

**Comment by KaelWD** [comment]
This seems like https://github.com/vuejs/vue/issues/9231 but with domProps instead of style

**Comment by KaelWD** [comment]
Opened https://github.com/vuejs/vue/issues/10803
