### ISSUE TITLE
[Bug Report] v-treeview with computed items

### ISSUE THREAD

**Issue by Chellhooo** [vuetifyjs/vuetify#9561]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.3

### Steps to reproduce
Set items with computed variable, which mentions the values of component.
See codepen in the reproduction link and then select the root node.

### Expected Behavior
The component is in leaf selection style and the values should be the children of root node.

### Actual Behavior
The values contains all nodes including parent nodes.

### Reproduction Link
<a href="https://codepen.io/chellhoo/pen/NWWyxwN?&editable=true&editors=101" target="_blank">https://codepen.io/chellhoo/pen/NWWyxwN?&editable=true&editors=101</a>

**Comment by xrkffgg** [comment]
Just define `items` in `data`

**Comment by Chellhooo** [comment]
> Just define `items` in `data`

Thanks for answer, but computed items will not be supported in the future?  If i want to disable some nodes when values change, computed items may be helpful.

**Comment by xrkffgg** [comment]
@Chellhooo delete `let values = this.selection` in you code

**Comment by Chellhooo** [comment]
@xrkffgg Actually, that's what i want to do:  I want to compute items with the selection. For example, i want to lock others nodes base on selection.

**Comment by xrkffgg** [comment]
感觉这个 `computed` 里，你就在 `this.selection` 取值的时候，也触发进行了计算，反正感觉就是互相影响，一般  `computed` 都只放一些简单的计算。

如果是我做，我会在 v-select 选择的时候，来更改 items 的值，放到 methods 里，或者就是 watch 监控 `selection` 的值。不会采用 `computed`

**Comment by Chellhooo** [comment]
@xrkffgg  猴，谢谢~ : )

**Comment by johnleider** [comment]
You cannot edit computed properties, they are only functions that return getters. If you define a manual setter you can accomplish this behavior. https://vuejs.org/v2/guide/computed.html#Computed-Setter
