### ISSUE TITLE
[Documentation] The currently used code should be output below the playground

### ISSUE THREAD

**Issue by AGDholo** [vuetifyjs/vuetify#9564]
### Problem to solve
You may need this code when using the playground. For example, in the documentation for v1.x grids, there will be output to output the current code, but I don't know why v2.x is canceled.

### Proposed solution
Same with v1.x docs "output"
The following is just a sample link that I hope will work in all areas
https://v15.vuetifyjs.com/en/framework/grid#layout-playground

**Comment by MajesticPotatoe** [comment]
Docs for grids (and docs as a whole) in 2.x were rewritten.
We are in the process of updating playground examples for all components to a new format ( eg: [alerts](https://vuetifyjs.com/en/components/alerts#usage) ), We can look into possibly adding this into the new format.

**Comment by wysman** [comment]
+1

**Comment by MajesticPotatoe** [comment]
This is available in current docs that use the new usage examples.
