### ISSUE TITLE
[Bug Report] component data-table->slot headers -> properties "someItems" "everyItem" be non-reactive

### ISSUE THREAD

**Issue by businka** [vuetifyjs/vuetify#9568]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
check items.

### Expected Behavior
the checkbox in the header slot will be the same as in the named header slot

### Actual Behavior
 checkbox in slot-headers not changed

### Reproduction Link
<a href="https://codepen.io/businka/pen/qBBxXBp?editors=1010" target="_blank">https://codepen.io/businka/pen/qBBxXBp?editors=1010</a>

**Comment by nekosaur** [comment]
`someItems` and `everyItem` are both found inside `props` object.

**Comment by businka** [comment]
then it is an error in the documentation for the component slot. these properties in the documentation are specified outside
