### ISSUE TITLE
[Bug Report] v-time-picker's AM/PM mode doesn't show 12 hr time

### ISSUE THREAD

**Issue by Webifi** [vuetifyjs/vuetify#9572]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Select "PM" on time picker, notice the time displayed is hour + 12

### Expected Behavior
PM Time displayed should be in 12 hour format 

### Actual Behavior
PM Time displayed in 24 hour format 

### Reproduction Link
<a href="https://codepen.io/webifi/pen/bGGLjMz?&editable=true&editors=101" target="_blank">https://codepen.io/webifi/pen/bGGLjMz?&editable=true&editors=101</a>

**Comment by Webifi** [comment]
Note: Works correctly if you use ampm-in-title, though that's not the default.
https://codepen.io/webifi/pen/YzzeOKv?&editable=true&editors=101

**Comment by jacekkarczmarczyk** [comment]
Should it display am/pm in the title or just 12 hour time?

**Comment by Webifi** [comment]
I would think it should display 12hr format in the title if the format prop is set to 'ampm' (the default).

AM/PM should be displayed in the title the ampm_in_title prop is set.

**Comment by jacekkarczmarczyk** [comment]
> I would think it should display 12hr format in the title if the format prop is set to 'ampm'

That's obsvious and what the issue is about ;)
Maybe my question wasn't clear enough - I'm just thinking that without ampm-in-title prop the "am/pm" indicator (the one below the clock) may be too far from the time and lead to confusing UI

**Comment by Webifi** [comment]
I see. Yeah, it's probably more intuitive to always have it on in the title, but if ampm_in_title is set, then don't show the additional selector in the body.

Does the Material guidelines give any guidance here?

**Comment by jacekkarczmarczyk** [comment]
They have only date picker unless i'm blind

This looks ok for me
![image](https://user-images.githubusercontent.com/15625235/72994522-d4068600-3e29-11ea-84da-d2767e434117.png)

**Comment by Webifi** [comment]
I think it looks fine. 

So, in this case, if "ampm_in_title" isn't set, the am/pm shown in the title is for display only, not selection, correct?

**Comment by jacekkarczmarczyk** [comment]
Yes, alternatively it could be renamed to `hide-clock-ampm`

**Comment by Webifi** [comment]
Probably something more like "pick-ampm-in-title" may be more accurate, if not too verbose.

As Phil Karlton once said:
_There are only two hard things in Computer Science: cache invalidation and naming things._
