### ISSUE TITLE
[Bug Report] Dark theme colors not applying when dark:false + dark prop

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#9573]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
Set up custom dark theme
Leave dark:false on theme config
Use dark prop on something like a toolbar

### Expected Behavior
The toolbar should use the custom dark colors

### Actual Behavior
The toolbar uses default dark colors

### Reproduction Link
<a href="https://github.com/waszqba/vuetify-theme-example" target="_blank">https://github.com/waszqba/vuetify-theme-example</a>

### Other comments
Original (closed) issue https://github.com/vuetifyjs/vuetify/issues/7084

**Comment by KaelWD** [comment]
It's `dark` not `isDark`

**Comment by mrodal** [comment]
@KaelWD could you not close the issue like that? im forced to open yet another issue if you dont answer closed issues. Look at this repro link https://codepen.io/mrodal/pen/OJJvyer
