### ISSUE TITLE
[Bug Report] Too much space between list item icon and list item title

### ISSUE THREAD

**Issue by yooneskh** [vuetifyjs/vuetify#9574]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Linux x86_64

### Steps to reproduce
add a list item with icon and title

### Expected Behavior
I think there should be less space between icon and title. I give the "me-2" class to list-item-icon and it seems better visually.

### Actual Behavior
Too much space.

### Reproduction Link
<a href="https://codepen.io/yooneskh/pen/abbqxJV?editors=1010" target="_blank">https://codepen.io/yooneskh/pen/abbqxJV?editors=1010</a>

**Comment by johnleider** [comment]
The specification is for a minimum of 24 width with margin. When you use a small v-icon, that width is still honored while the icon takes up less space. This is something you will have to take care of in userland.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by J-Sek** [comment]
Workaround:
- `slim` prop - drops to 20px
- or `.v-menu .v-list-item__spacer { width: 12px !important; }`
- or Sass variable `$list-item-icon-margin-end` (defaults to 32px)

I acknowledge it is a pain. We will have more control over it once #20616 gets merged.
