### ISSUE TITLE
[Bug Report] Characters cut off in VSelect (Open Sans)

### ISSUE THREAD

**Issue by nlien** [vuetifyjs/vuetify#9576]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Ubuntu undefined

### Steps to reproduce
This happen when I use "Open Sans" as default font. 

* Open referenced CodePen
* Notice the CSS; Open Sans is set as default font
* Select "Guggenheim" from the selection list
* Notice the 'g' characters are "cut off"; not entirely visible.
* Select "Pretty" from the selection list
* Notice the 'y' character is not entirely visible

### Expected Behavior
Expected that the font will not be partly hidden

### Actual Behavior
Some characters in the font are not entirely visible

### Reproduction Link
<a href="https://codepen.io/nilslien/pen/NWWyZaE" target="_blank">https://codepen.io/nilslien/pen/NWWyZaE</a>

**Comment by MajesticPotatoe** [comment]
```
.v-select__selections {
  line-height: 20px;
}
```

**Comment by nlien** [comment]
That helps in Chrome, but it's not sufficient in Firefox.
I found out that the following CSS helps when displaying the selected items:
```
  .v-select__selection--comma {
    overflow: visible;
  }
```
However, I don't know if this will break the VSelect UI otherwise...
Also, notice some characters (specifically 'y' and 'g') in the label are cut off in Firefox, regardless of the above CSS.

**Comment by bromix** [comment]
Same here,  I had to do the following:

```css
.v-select__selection--comma {
    overflow: unset;
}

.v-list-item__title, .v-list-item__subtitle {
    overflow: unset;
}
```
Otherwise the values in the select component are cut of at the bottom.

**Comment by johnleider** [comment]
Everything is developed with the use of Roboto. If you are implementing a custom font, you may need to update the `$line-height-root` sass variable`. This should be resolved in userland.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
