### ISSUE TITLE
[Feature Request] dense property levels (xs, s, m, l) 

### ISSUE THREAD

**Issue by ibanlaya** [vuetifyjs/vuetify#9579]
### Problem to solve
We are developing a business application using value and vuetify, we are very comfortable working with both, but we need to have different application sizes (By default beautify is very big). We have seen the dense property in some components, but we need to have different density levels (xs, s, m, l).

To do it, we add a dynamic css property in the component (: class="[dense]") and css classes. Example: https://codepen.io/IbanLaya/full/KKKoPBR.
We don't like this solution. ¿ Are you going to add different density levels?

### Proposed solution
dense property has to support different values (xs, s, m, l)

**Comment by KaelWD** [comment]
No. The grid gutter sizes can be changed with sass variables, the input styles are from the material design specification and have no reason to be more delineated.

**Comment by escapedcat** [comment]
Just an info for other people who search for this:  
It's `$grid-gutter` in the global `$vuetify` Sass variables

**Comment by KaelWD** [comment]
This has also been added to v3 as `density="comfortable"` and `density="compact"`
