### ISSUE TITLE
[Bug Report] VFileInput prepend slot doesn't work

### ISSUE THREAD

**Issue by Aukemid** [vuetifyjs/vuetify#9580]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.15.1

### Steps to reproduce
See reproduction link.
Add a ```<template v-slot:prepend>``` to a ```<v-file-input>```.

### Expected Behavior
The set prepend slot should be used instead of the default value '$file' of the prepend-icon prop.

### Actual Behavior
The prepend slot appears to be ignored completely.

### Reproduction Link
<a href="https://codepen.io/Aukemid/pen/gOOXNGZ" target="_blank">https://codepen.io/Aukemid/pen/gOOXNGZ</a>

### Other comments
It seems impossible to use the prepend slot in a v-file-input. You can remove the default icon by giving the prepend-icon an empty string value, but setting a custom prepend slot has no effect. It does work for prepend-inner, append and append-outer.

**Comment by PabloRN** [comment]
Still happening. For me I can use the `v-slot:prepend-inner` but I need to also add prepend-icon="".

Q: In my case I added a button as a v-slot:prepend but when I click on it no open dialog (trigger click on input) is showing. Is this part of the issue or a normal behavior?

**Comment by pate313373** [comment]
Still a problem..... :(

**Comment by jonatan-mobal** [comment]
Any status on this? Still a problem in 2.6.10

**Comment by Inasyah** [comment]
This bug still persists in vuetify 3.2.1 in the following form:

### Steps to reproduce:
Add a `<template v-slot:prepend> <v-icon> {{ some icon }} </v-icon></template>` to a `<v-file-input>`.

### Expected outcome:
Icon inside the v-slot:prepend should replace the default prepend icon.

### Actual outcome:
The v-slot:prepend icon is placed next to the default prepend icon (both are visible).

### Reproduction link:
[play.vuetifyjs.com](https://play.vuetifyjs.com/#eNqlUctOwzAQ/BXjS0CqbaC3KFTlxh9waHpIkw0Y/JLtBKEq/47thNDXoRI37+zszOx6s8fPxtC+A5zjwoM0ovKwKhVCRU8qY9IzFbLiaqpS3XIBhCvT+Rkt/SyBeuKE9rmxYEA1MyWResJrrVay4aSuJNiqYBP0RyvYUZoRuuAawTlaLMbQR+OhdLXlxiMHvottLo22Hu2RhRYNqLVaoixcIYvkEMR5JN0beor92+wFhNDoVVvR3GR3UXyUC0J4gUetEMLQD6dVOOQ+ZimnhitxjhISseAR6xK/e29czljdqDDWgOC9pQo8U0aydaAx2ynPJZBGy/WSLuk92YGv6CNruPOHXQpOkp3VXw5s0Crx4sDN8/b7CseJGYwe6cPoMEFEVDsXLc6kWfDrwRIbPhgs2GsXOxm7sNwJ42zBGGIo1RCuL7j6dCeHr106+uY36782T2JRaRsNhwU+jBsCpDm8/QEcThe6)

### Other comments:
The prepend slot is referenced in the [documentation](https://vuetifyjs.com/en/api/v-file-input/#slots-prepend).

**Comment by jlucloran** [comment]
This is still an issue in 2.6.15. Is there a fix for this issue that is planned on being released?
@johnleider
