### ISSUE TITLE
[Documentation] Add input event for snackbars

### ISSUE THREAD

**Issue by coyotte508** [vuetifyjs/vuetify#9582]
### Problem to solve
I want to know how to know when the snackbar is autodimissed. 

### Proposed solution
Add an "input" section in the events for the snackbar, like for v-select.

**Comment by MajesticPotatoe** [comment]
duplicate of #8658

**Comment by coyotte508** [comment]
But the event already exists. It's the input event.

This issue is just for the documentation to be added, not a feature request for a new event
