### ISSUE TITLE
[Bug Report] i18n: Some translation key are missing

### ISSUE THREAD

**Issue by dpetit62** [vuetifyjs/vuetify#9583]
### Environment
**Vuetify Version:** 2.1.9
**Last working version:** 2.0.4
**Vue Version:** 2.6.10
**Browsers:** Chrome 76.0.3809.100
**OS:** Linux x86_64

### Steps to reproduce
- Install 2.1.9
- Set vuetify languages:
```javascript
import '@mdi/font/css/materialdesignicons.css';
import Vue from 'vue';
import Vuetify from 'vuetify/lib';
import fr from 'vuetify/src/locale/fr';
import en from 'vuetify/src/locale/en';
Vue.use(Vuetify);
export default new Vuetify({
  lang: {
    locales: {
      fr, en
    },
    current: 'fr'
  },
  icons: {
    iconfont: 'mdi'
  }
```

### Expected Behavior
All fields are supposed to be translated correctly (like it was in 2.0.4)

### Actual Behavior
Some fields are not translated. for example : `[Vuetify] Translation key "dataFooter.pageText" not found, falling back to default` so in french it is still displayed '1-10 of13' instead of '1-10 de 13'

### Reproduction Link
<a href="https://codepen.io/dpetit62/pen/gOOeMee" target="_blank">https://codepen.io/dpetit62/pen/gOOeMee</a>

### Other comments
Sorry I didn't find how to intall other language in the code pen

**Comment by johnleider** [comment]
I'm not sure if you can change the language within codepen. I've tested this locally and it is working as expected.

![image](https://user-images.githubusercontent.com/9064066/69346447-62973500-0c38-11ea-9aed-73e589883d44.png)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by adrielwerlich** [comment]
I´m also having the same issue here. What´s the solution?
