### ISSUE TITLE
[Bug Report] Date Range picker display '2 selected' instead of displaying the total number of dates (the difference between 2 dates)

### ISSUE THREAD

**Issue by mr-mad-e** [vuetifyjs/vuetify#9586]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Linux x86_64

### Steps to reproduce
1. Open a date range picker
2. Pick a date
3. Pick another date (more than 2)
4. It will display 2 selected 

### Expected Behavior
It should display the total number of dates

### Actual Behavior
It will display '2 selected' instead of displaying the total number of dates 

### Reproduction Link
<a href="https://codepen.io/mahammad8564-the-animator/pen/zYYWwgQ?&editable=true&editors=101" target="_blank">https://codepen.io/mahammad8564-the-animator/pen/zYYWwgQ?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
IMHO it should rather display the first and last date instead of number of days between them

**Comment by engyii** [comment]
I +1 that the current behavior with an huge '2 selected' above the calendar is kinda confusing to the end user and provide no useful information as the range is already visible when two date are selected. I think i'm gonna hack it to hide it in our current project. (it's that bad :) )

Change the default to the actual range duration or the two dates are fine solution to me. a range-label properties to customise it would be cool too.

**Comment by mahammad8564** [comment]
@engyii range-label is a good solution, is there something I can help you with? I want to contribute.

**Comment by YipingRuan** [comment]
> IMHO it should rather display the first and last date instead of number of days between them

Let me first add from ~ to dates style, latter add the total days count

**Comment by Nastradoomus** [comment]
Meanwhile:

`
const dateTitle = (this.$refs.datePicker as Vue).$children[0].$children[0].$el.getElementsByClassName("v-picker__title__btn v-date-picker-title__date")[0];
`

I know that You should not but it is tempting...
