### ISSUE TITLE
[Feature Request] disabled-class for components

### ISSUE THREAD

**Issue by d3radicated** [vuetifyjs/vuetify#9589]
### Problem to solve
Override the applied class for disabled components.

### Proposed solution
Add a `disabled-class` prop for applicable components (ex. `v-list-item`)

**Comment by KaelWD** [comment]
Why

**Comment by d3radicated** [comment]
So that you can freely override or remove the used class when a component is disabled.

**Comment by KaelWD** [comment]
That doesn't really answer the question. All disabled does is apply a class, so you should just apply your own class instead of using disabled. This would also be different behaviour from active-class, which is additive instead of replacing the built-in one.

**Comment by d3radicated** [comment]
Sorry for the misunderstanding. I created the issue with components that have other functionalities in mind like `<v-list-item>` with a `@click` handler.

**Comment by KaelWD** [comment]
Disabled disables the click handler by applying a class, if you were able to overwrite that then it wouldn't be disabled any more.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
