### ISSUE TITLE
[Bug Report] v-calendar Event Layout : Event is blocked behind other events

### ISSUE THREAD

**Issue by blexxed** [vuetifyjs/vuetify#9591]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Mac OS 10.15.0

### Steps to reproduce
Check reproduction link. The red event is the one that is blocked.

### Expected Behavior
Event should not be blocked behind other events

### Actual Behavior
Event is blocked behind other events

### Reproduction Link
<a href="https://codepen.io/blexxed/pen/wvvmxYE?&editable=true&editors=101" target="_blank">https://codepen.io/blexxed/pen/wvvmxYE?&editable=true&editors=101</a>

**Comment by d3radicated** [comment]
Might be a duplicate of #8565.
