### ISSUE TITLE
[Feature Request] Upper / lower boundaries in v-slider

### ISSUE THREAD

**Issue by eggnaube** [vuetifyjs/vuetify#9593]
### Problem to solve
The user can choose a value between a lower and upper boundary. The slider shows a value range from 0% to 100%, the minimum value the user can chose is e.g. 20% and the maximum is e.g. 75%. This two boundaries need a label to display the value.

### Proposed solution
Add lower / upper boundaries property. Pass value and label. Track from 0 to lower and upper to end boundary is disabled. If given, the label is shown below the track as mark, can be modified via slot if required.

**Comment by HunderlineK** [comment]
This would be quite easy to implement in user land if the slider was controlled i.e. if I could force a specific value even if the user was trying to move the slider.

**Comment by KaelWD** [comment]
Models are controlled in v3 so you can do this with `:ticks="[20, 75]"` and
```js
const _model = ref(20)
const model = computed({
  get: () => _model.value,
  set: val => _model.value = Math.max(20, Math.min(75, val))
})
