### ISSUE TITLE
Menuable positioning rewrite

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#9597]

**Comment by velly** [comment]
Is this issue  same to mine? if true, i will not create a new issue;

I  use v-menu to wrap the 'Locale Swticher'  to a component like below: (suppose this component would be used in AppHeader)

<template>
  <div
    class="tw-h-10 tw-w-10 tw-grid tw-content-center tw-place-content-center tw-p-3"
  >
    
    <v-menu
      open-on-hover
      transition="scale-transition"
      v-model:model-value="showLocales"
    >
      <template v-slot:activator="{ props }"
        ><v-btn
          rounded="0"
          icon="mdi-translate"
          size="small"
          variant="tonal"
          v-bind="props"
          class="dark:tw-bg-gray-400"
        ></v-btn
      ></template>

      <v-list>
        <v-list-item
          v-for="(item, code) in supportedLocales"
          :key="code"
          class="hover:tw-bg-gray-300 dark:hover:tw-bg-gray-600 hover:tw-cursor-pointer"
          @click="onSelectLocale(code)"
        >
          <v-list-item-title>{{ item.name }}</v-list-item-title>
        </v-list-item>
      </v-list>
    </v-menu>
  </div>
</template>
<script lang="ts" setup>
import { supportedLocales } from "@/config/locale";
import useLocale from "@/stores/locale";
import { useLocale as useVuetifyLocale } from "vuetify";
import { useI18n } from "vue-i18n";
import { ref } from "vue";

const { current } = useVuetifyLocale();
const { locale } = useI18n({ useScope: "global" });
const localeStore = useLocale();
const showLocales = ref(false);

const onSelectLocale = (code: string): void => {
  if (code !== localeStore.curLocale) {
    showLocales.value = false;
    localeStore.setLocale(code);
    current.value = code;
    locale.value = code;
  }
};
</script>

-----

I found the dropdown menu item jumps away when I show the menus after resized the page.
The dropdown menu should be always shown under the trigger button(v-btn)?

**Comment by KaelWD** [comment]
No, this was done as part of 3.0
