### ISSUE TITLE
Dialog transitions can't be disabled

### ISSUE THREAD

**Issue by chriswa** [vuetifyjs/vuetify#960]
### Steps to reproduce
Create a dialog with <v-dialog :transition="false">, destroy it, observe that content continues to be displayed after the component is destroyed.
https://codepen.io/anon/pen/ZyVBgB?editors=1010

### Versions

vue@2.3.4
vuetify@0.13.1
Google Chrome 58.0.3029.110 (Official Build) (64-bit)
Windows 10

### What is expected ?

As per the docs: "Defines show/hide transition. Set to false for no transition". When set to false, the dialog should appear and disappear instantly.

### What is actually happening ?

The dialog remains visible for a few hundred millsecs after being destroyed.

### Reproduction Link

https://codepen.io/anon/pen/ZyVBgB?editors=1010

**Comment by johnleider** [comment]
You're like the dialog ♕, thanks for keeping this framework great!
