### ISSUE TITLE
[Bug Report] Outlined autocomplete's prefix is shifted vertically

### ISSUE THREAD

**Issue by Punknium** [vuetifyjs/vuetify#9600]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Windows 10

### Steps to reproduce
Create an autocomplete that looks like this.
```vue
<v-autocomplete
  label="test"
  prefix="test"
  outlined
></v-autocomplete>
```

### Expected Behavior
I expect the prefix to be inline with the label.

### Actual Behavior
The prefix is shifted up.

### Reproduction Link
<a href="https://codepen.io/Punknium/pen/rNNdEqN" target="_blank">https://codepen.io/Punknium/pen/rNNdEqN</a>

**Comment by Punknium** [comment]
The issue appears to be this selector not taking into account the outlined flag.

**Comment by johnleider** [comment]
This appears resolved on the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
