### ISSUE TITLE
[Feature Request] Date range picker model must satisfy dates[0] < dates[1]

### ISSUE THREAD

**Issue by mahammad8564** [vuetifyjs/vuetify#9601]
### Problem to solve
It will fix the bugs  related to date difference, like the difference is negative if dates[0] > dates[1]

### Proposed solution
`this.$emit('input', this.value[0] > newInput ? [newInput, ...this.value] : [...this.value, newInput])`

**Comment by KaelWD** [comment]
Is this a bug report? You can just sort the array if you don't care about selection order.
