### ISSUE TITLE
[Bug Report] Rectangular outlined buttons on Firefox have a dimension change on mouse down

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetify#9603]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Mozilla Firefox
**OS:** Linux

### Steps to reproduce
Using Firefox on Ubuntu 18.04.3 clicking on a rectangular button with the outline property set to true causes the button to loose its border.

### Expected Behavior
The border should not vanish on Firefox when the button is clicked

### Actual Behavior
Border vanishes when clicked.

### Reproduction Link
<a href="https://codepen.io/MatthewAry/pen/NWWMPNm" target="_blank">https://codepen.io/MatthewAry/pen/NWWMPNm</a>

**Comment by KaelWD** [comment]
Hey look it's me: #1844
