### ISSUE TITLE
[Bug Report] v-chip  text-color  in v-chip-group not changed 

### ISSUE THREAD

**Issue by abumalekFayed** [vuetifyjs/vuetify#9604]
### Environment
**Vuetify Version:** 2.1.9
**Last working version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Windows 10

### Steps to reproduce
change color

### Expected Behavior
for color change

### Actual Behavior
change for color

### Reproduction Link
<a href="https://jsfiddle.net/abumalek/7tL3vf81/3/" target="_blank">https://jsfiddle.net/abumalek/7tL3vf81/3/</a>

**Comment by dimavolo** [comment]
`v-chip` `text-color` doesn't seem to have any effect in version`2.3.10`.
