### ISSUE TITLE
[Bug Report]  v-checkbox and v-radio do not work

### ISSUE THREAD

**Issue by CaoMeiYouRen** [vuetifyjs/vuetify#9609]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Open https://codepen.io/caomeiyouren/pen/bGGMaay on Chrome

### Expected Behavior
As shown in the figure below

![mark](http://cdn.cmyr.ltd/blog/20191107/2bhdDrPECfPU.png?imageslim)

### Actual Behavior
As shown in the figure below

![mark](http://cdn.cmyr.ltd/blog/20191107/0umP7Up8kCiK.png?imageslim)

### Reproduction Link
<a href="https://codepen.io/caomeiyouren/pen/bGGMaay" target="_blank">https://codepen.io/caomeiyouren/pen/bGGMaay</a>

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/quick-start#font-installation
