### ISSUE TITLE
[Bug Report] mdi-toolbox icon is wrong in webkit browsers

### ISSUE THREAD

**Issue by badders** [vuetifyjs/vuetify#9611]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Other
**OS:** Linux x86_64

### Steps to reproduce
Use the mdi-toolbox icon in a v-icon

### Expected Behavior
Shows the toolbox icon (works fine in chrome/edge/firefox)

### Actual Behavior
Shows a strange glyph (possibly korean?)

### Reproduction Link
<a href="https://jsfiddle.net/m9qy0dju/1/" target="_blank">https://jsfiddle.net/m9qy0dju/1/</a>

### Other comments
Tested in midori and epihany on linux with same results, presumably happens in safari too but i cant test that

**Comment by badders** [comment]
![mdi-toolbox-bad](https://user-images.githubusercontent.com/2690480/68393177-67051d80-0163-11ea-8cd4-8dd71e8ec1a9.png)
This is what is shown

**Comment by badders** [comment]
I suspect its really a webkit bug where its forcing that particular character to be rendered with a different font

**Comment by KaelWD** [comment]
You should open this on https://github.com/templarian/MaterialDesign/
