### ISSUE TITLE
[Bug Report] Slow build times when using Sass variables

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify#9612]
### Environment

**Browsers:** Chrome 78.0.3904.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a vuetify project and override the Sass variables in either of these 2 ways:
1. Using "vue-cli-plugin-vuetify" and a `src/sass/variables.s(a|c)ss` file (that's auto imported)
2. Not using "vue-cli-plugin-vuetify", importing Sass variables in vue.config.js and using "'vuetify-loader/lib/plugin'"

As far as I'm aware these are the only 2 ways to set Sass variables?

A few weeks ago our build times were 20seconds (using vuetify 2.0.18) but they are now as much as 80~90seconds.

When the CLI estimates a percentage, it flies along pretty quick then it gets to 60% and keeps going up and down whilst it runs through the Vuetfiy components.

### Expected Behavior
Compile times similar to what they used to be

### Actual Behavior
Build times of 80~90seconds.

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
I've tried upgrading to "vue-cli-plugin-vuetify" version 2.0.0 and it didn't help.
It looks like a similar/same issue as this https://stackoverflow.com/questions/58441782/extremely-long-compile-times-with-vuetify-2-1-and-webpack

I originally raised this in the vuetify loader repo but have been advised that it's not anything to do with that - https://github.com/vuetifyjs/vuetify-loader/issues/95

**Comment by KaelWD** [comment]
I already replied to the stackoverflow question: https://stackoverflow.com/a/58749021/2074736

**Comment by mattgreenfield** [comment]
Thanks @KaelWD, I've made a test repo here and am getting compile times of about 40seconds.
https://github.com/mattgreenfield/vuetify-sass-variables
As you mention, the more Sass variables I add, the slower the builds get. There is also only 2 components in my demo but many more in my real world project.

I can see that when building, it's looping over every Vuetify component and (presumably) passing in all my variables, even though I am not using any vuetify components in my project. Is there any possibility it could only merge Sass variables for components I'm actually using?

Another possible fix might be to allow me to have a `vuetify-variables.scss` file and a `my-component-variables.scss` file, meaning that the amount of variables that vuetify loads is reduced. I could not think of a way to do this with webpack.

Thanks for your help

**Comment by KaelWD** [comment]
With vuetify-loader@1.3 you can try importing from `vuetify/lib/framework` instead (https://github.com/vuetifyjs/vuetify-loader/issues/44)

**Comment by mattgreenfield** [comment]
Thanks @KaelWD. That's certainly quicker in my demo project but in my real work project it seems to miss certain imports of nested components when rendering them in storybook.

Was the way that Sass variables are loaded changed recently? I'm trying to find which of the many dependencies I need to roll back

**Comment by KaelWD** [comment]
vue-cli-plugin-vuetify changed some stuff.

**Comment by KaelWD** [comment]
Also you don't need all those imports any more, maps were changed to merge automatically in v2.1.3 (c9dac4a5823867c54cf7f2709e97ad3d95f4bdc4)

> seems to miss certain imports of nested components

Anything specific? If true that could be an actual bug.

**Comment by johnleider** [comment]
Multiple improvements have been made to improve compilation time with SASS variables, but as described in the stack response, it is expected as it has to recompile all of the styles.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
