### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by jgonzalez315** [vuetifyjs/vuetify#962]

**Comment by dohomi** [comment]
@jgonzalez315 is there anything else coming? closing it now feel free to re-open

**Comment by jgonzalez315** [comment]
Hi, I made an update of the issue

**Comment by nekosaur** [comment]
Vuetify does not support using it together with another CSS framework. As stated in the documentation:

> While Vuetify attempts to not cause any css collision as much as possible, there is no guarantee that your custom styles will not alter your experience when integrating this framework into your existing project.

**Comment by sl-digital** [comment]
Wrap your HTML in a div with an ID and then use Sass to create a prefixed version of Bootstrap.  The first Sass rule should be your ID and then paste your bootstrap styles inside.  That should give your bootstrap rules enough weight to override Vuetify's collisions for things like buttons, tables, etc.
