### ISSUE TITLE
[Bug Report] VDataTable "Mismatching childNodes vs. VNodes" in Nuxt for :loading

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#9624]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Windows 10

### Steps to reproduce
1. Run code under Nuxt
2. Assume :loading = true in client only (server :loading = false)
3. "Mismatching childNodes vs. VNodes" happens due to client is loading, while the SSR is not.

### Expected Behavior
childNodes vs. VNodes should always match regardless of :loading.

### Actual Behavior
Warning in console:
```
Mismatching childNodes vs. VNodes:  NodeList(3) [colgroup, thead.v-data-table-header, tbody] (4) [VNode, VNode, VNode, VNode]
commons.app.js:11992 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

### Reproduction Link
<a href="https://codepen.io/andrewspy/pen/ExxRVYO" target="_blank">https://codepen.io/andrewspy/pen/ExxRVYO</a>

### Other comments
The mismatch is probably caused by the additional DOM of VProgressLiner when loading. I have not seen the code, but I am guessing VProgressLiner should be hidden with v-show instead created with v-if.

**Comment by kevinmarrec** [comment]
@andrewharvey It's a common SSR hydration issue, having `loading` not in the same state `server` & `client` sides makes html mismatching.

> **Reminder**
> `created` hook is being called both on  `server` and `client` sides
> `beforeMount` & `mounted` hooks are only being called `client` side

This is neither Nuxt or Vuetify issue, you have to either :

**1)** Keep `loading` to `false`, and set it to `true` on client in `beforeMount`
> **Note**: If `beforeMount` still ends up in hydration issue, try `mounted`

*OR*

**2)** Set `loading` to `true` by default in `data` (so both `client` & `server`), then set it to `false` when the your data is fetched, after the component has been `mounted`.

**Comment by andrewharvey** [comment]
@kevinmarrec I think you meant @andrewspy

**Comment by kevinmarrec** [comment]
@andrewharvey You're right, sorry for the uncorrect ping, GH made me crazy :
![image](https://user-images.githubusercontent.com/25272043/72420420-f8ee5f80-377e-11ea-83a6-07652a3de092.png)

Updated the mention.

**Comment by andrewspy** [comment]
@kevinmarrec Thanks for the detail explanation, I shall close the issue.
