### ISSUE TITLE
The xs value does not work on the grid system

### ISSUE THREAD

**Issue by Alexisgt01** [vuetifyjs/vuetify#9629]
Hello,

I can not copy links correctly on the url https://issues.vuetifyjs.com
So I write here

The xs value does not work on the grid system
there is just to try on the codepen of the documentation

`<v-col col="4" xs="12"> </v-col>`
return 
`<div xs="12" class="col col-4"></div>`

find here, simply on the codepen : https://vuetifyjs.com/en/components/grids#usage

Maybe I didnt understand its use ?

thank you

**Comment by turbobuilt** [comment]
FYI for anybody wondering about this, `cols` is the equivalent of `xs`.  So you would do:

```
<v-col md="6" sm="9" cols="12">...</v-col>
```
