### ISSUE TITLE
Event to update miniVariant when click on any item inside navigation-drawer

### ISSUE THREAD

**Issue by EddFigueiredo** [vuetifyjs/vuetify#963]
### Steps to reproduce
Just start a new vuetify project, and scaffold a navigation-drawer and a toolbar.

### Versions
- Vue 2.3.3
- Vuetify 0.13.1

### What is expected ?
The items in the list should behave as normal link to another pages.

### What is actually happening ?
There's an event `update:miniVariant` being emitted setting the `miniVariant` to false when clicked.
This changes the navigation-drawer to not minified.

I had to manually remove line 4947 on node_modules/vuetify/dist/vuetify.js `_this2.$emit('update:miniVariant', false)`

### Reproduction Link
https://codepen.io/anon/pen/GEPvKp

**Comment by johnleider** [comment]
Just remove the ```.sync``` on the mini-variant.
