### ISSUE TITLE
[Bug Report] Span tag in hint attribute of v-autocomplete is escaped

### ISSUE THREAD

**Issue by yerzhant** [vuetifyjs/vuetify#9647]
### Environment
**Vuetify Version:** 2.1.9
**Last working version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.70
**OS:** Linux x86_64

### Steps to reproduce
`
<v-autocomplete hint="123 <span class='test'>33</span>" persistent-hint>
`

### Expected Behavior
On the page it should be:
123 33

### Actual Behavior
123 <span class='test'>33</span>

### Reproduction Link
<a href="https://codepen.io/yerzhant/pen/YzzjyrP" target="_blank">https://codepen.io/yerzhant/pen/YzzjyrP</a>

**Comment by Paulsky** [comment]
Same problem here. 

**Actual Behavior**
`<span>123 33</span>`

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/9491

**Comment by Paulsky** [comment]
Thank you @jacekkarczmarczyk . @yerzhant You can fix this by using the new 'message' slot.

Please see this CodePen: [https://codepen.io/Paulsky/pen/zYYmpEb](https://codepen.io/Paulsky/pen/zYYmpEb)

**Comment by jacekkarczmarczyk** [comment]
Looks like the slot is not mentioned in docs

**Comment by KaelWD** [comment]
It was also added in a patch release which I'm not to happy about.

**Comment by Paulsky** [comment]
This is related I guess: https://github.com/vuetifyjs/vuetify/issues/918
