### ISSUE TITLE
[Bug Report] No typings for import goTo function

### ISSUE THREAD

**Issue by mlesin** [vuetifyjs/vuetify#9648]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Safari 13.0.3, Google Chrome, Mozilla Firefox, Safari, Microsoft Edge, Internet Explorer, Opera, Other
**OS:** Mac OS 10.14.6

### Steps to reproduce
Just try to import goTo function from typescript:

`import goTo from "vuetify/lib/services/goto";`

### Expected Behavior
successful import

### Actual Behavior
TS Error:
`Could not find a declaration file for module 'vuetify/lib/services/goto'`

### Reproduction Link
<a href="https://codesandbox.io/s/zen-taussig-3dwph" target="_blank">https://codesandbox.io/s/zen-taussig-3dwph</a>

### Other comments
Looks like type definition is missing.
Using this as workaround, in shims-vue.d.ts:

    declare module "vuetify/lib/services/goto" {
      import Vue from "vue";
      export default function goTo<T extends string | number | HTMLElement | Vue>(target: T, options?: any): any;
    }

**Comment by Eisfluegel** [comment]
I have exactly the same error (I'm trying to use goTo with vue-router as described here: https://vuetifyjs.com/en/styles/scroll#using-with-router).
The thing is, I am not using Typescript. So none of the Typescript workarounds are useful for me (shims, compiler options).

Have you encountered this? Is this even possible, since this seems to be a TS specific error?

**Comment by KaelWD** [comment]
If you're getting that exact error then you are using typescript.

**Comment by bo-oz** [comment]
I have a similar problem without Typescript. I just import the code in my router like this:

`import goTo from 'vuetify/es5/services/goto';`

This gives me the following error

```
index.js:24 Uncaught ReferenceError: exports is not defined
    at eval (index.js:24)
    at Module../node_modules/vuetify/es5/services/goto/index.js (app.js:8235)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (router.js:13)
    at Module../src/components/_helpers/router.js (app.js:13835)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at eval (index.js?d5eb:1)
    at Module../src/components/_helpers/index.js (app.js:13823)
```

**Comment by joyceben33** [comment]
Bug has resurfaced in new major version `^3.0.0`

Environment 

```
 "vue": "^3.2.47",
 "vuetify": "^3.1.13"
```

**Comment by Keropon** [comment]
Can confirm I encountered the bug in 
```
"vue": "^3.2.47",
"vuetify": "^3.1.11"
```

**Comment by etienne-monier** [comment]
Me too. I use TS.

```
vue@3.3.4
vuetify@3.3.8
```

**Comment by etienne-monier** [comment]
Can someone detail how to use the workaround?
