### ISSUE TITLE
Text field (with prepend icon) error messages should have an indent (padding-left)

### ISSUE THREAD

**Issue by bunnypro** [vuetifyjs/vuetify#965]
**Step to reproduce**
Create a textfield with prepend icon and provide the `error-messages`

**Version**
vuetify: 0.13

**What is expected ?**
![screenshot_20170712_124326](https://user-images.githubusercontent.com/9997767/28103518-51329316-6700-11e7-94b1-8d2e4da4547b.png)

**What is actually happening ?**
![screenshot_20170712_124036](https://user-images.githubusercontent.com/9997767/28103529-6311f7c0-6700-11e7-9747-b94a1a914915.png)

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/895
