### ISSUE TITLE
[Bug Report] v-slider value reset

### ISSUE THREAD

**Issue by Bhavini30** [vuetifyjs/vuetify#9650]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.5.17
**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
1. Select any value in Slider 
2. Click on Reset
3. The value will reset but the slider will not reset on its main position

### Expected Behavior
The Slider should move to its main position as the value reset

### Actual Behavior
Reset Functionality 

### Reproduction Link
<a href="https://codepen.io/etsbhavini/pen/pooZeWB?editors=1010" target="_blank">https://codepen.io/etsbhavini/pen/pooZeWB?editors=1010</a>

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/list.html#Caveats

**Comment by KaelWD** [comment]
https://vuejs.org/v2/guide/list.html#Caveats
