### ISSUE TITLE
[Feature Request] Add support for paddings/margins and element heights to VSkeletonLoader 

### ISSUE THREAD

**Issue by valentingavran** [vuetifyjs/vuetify#9653]
### Problem to solve
Currently, it's not possible to create any type of skeleton for a component with the VSkeletonLoader. For example, if you have an article where you first want to display the skeleton before the data arrives from the server, then it is limited. In many cases if you want to display your specific component, then the distances between the headline, the cover, and the text are not the same as it will be when the data arrives.

### Proposed solution
There should be a way to configure the height and spacing of a skeleton item, as with the @ sign. For example, you could create 3 pictures in with the height of 300 with following property:

`image-h300@3`

Or, for example, if you have a headline and need a margin at the top, then you can use the following:

`heading-mt4 , ...`

**Comment by manuelmeister** [comment]
I think it would already be enough if classes set on <v-skeleton-loader> are applied to the actual contents and not the wrapper element itself.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration, the team has decided that this is not functionality that we are looking to implement at this time.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
