### ISSUE TITLE
[Bug Report] V-Autocomplete does not delete selected item by pressing Backspace twice

### ISSUE THREAD

**Issue by lawl-dev** [vuetifyjs/vuetify#9654]
### Environment
**Vuetify Version:** 2.1.9
**Last working version:** 2.0.20
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
1. Select item.
1. Press Backspace twice.

### Expected Behavior
1. Item should be deleted

### Actual Behavior
1. Nothing happens

### Reproduction Link
<a href="https://codepen.io/Grexter/pen/qBByjKe?&editable=true&editors=101" target="_blank">https://codepen.io/Grexter/pen/qBByjKe?&editable=true&editors=101</a>

### Other comments
When adding multiple attribute, it works.

**Comment by jacekkarczmarczyk** [comment]
Broken in 2.1.4 https://github.com/vuetifyjs/vuetify/commit/8580c7bb59945158c1b9e8df7da6979a9a394fec
