### ISSUE TITLE
[Feature Request] v-date-picker with range/multiple should emit a change event (good to have)

### ISSUE THREAD

**Issue by mahammad-sixberries** [vuetifyjs/vuetify#9656]
### Problem to solve
v-date-picker with range/multiple don't emit a change event

### Proposed solution
v-date-picker with range/multiple should emit a change event

https://codepen.io/mahammad8564-the-animator/pen/zYYWwgQ?editors=1011

**Comment by jacekkarczmarczyk** [comment]
Please show the problem in codepen

**Comment by mahammad-sixberries** [comment]
@jacekkarczmarczyk

Please find the problem in
https://codepen.io/mahammad8564-the-animator/pen/zYYWwgQ?editors=1011

**Comment by mahammad-sixberries** [comment]
I don't why they restrict in the first place, maybe there is some issue regarding this but I need it.

```
    emitInput (newInput: string) {
      if (this.range && this.value) {
        this.value.length === 2
          ? this.$emit('input', [newInput])
          : this.$emit('input', [...this.value, newInput])
        return
      }

      const output = this.multiple
        ? (
          (this.value as string[]).indexOf(newInput) === -1
            ? (this.value as string[]).concat([newInput])
            : (this.value as string[]).filter(x => x !== newInput)
        )
        : newInput

      this.$emit('input', output)
      this.multiple || this.$emit('change', newInput)
    },
```

should be 

```

```

**Comment by YipingRuan** [comment]
@mahammad-sixberries  Does 'input' event work for you?

**Comment by YipingRuan** [comment]
@jacekkarczmarczyk  Please help to alight with the current document

> Reactive date picker emits input even when any part of the date (year/month/day) changes, but change event is emitted only when the day (for date pickers) or month (for month pickers) changes.

If change is needed I can fix quickly.

**Comment by jacekkarczmarczyk** [comment]
Yeah, that should be updated for range picker - it behaves a bit different than normal one. Feel free to create PR for the picker and docs (fix for this issue should be to emit `@change` along with `@input` when `this.value.length === 2`, tests also should be updated)

**Comment by mahammad-sixberries** [comment]
> Yeah, that should be updated for range picker - it behaves a bit different than normal one. Feel free to create PR for the picker and docs (fix for this issue should be to emit `@change` along with `@input` when `this.value.length === 2`, tests also should be updated)

@jacekkarczmarczyk 
Is should be more helpful when @change emits for every change (any this.value.length)
