### ISSUE TITLE
[Feature Request] VTextarea row counter

### ISSUE THREAD

**Issue by Shinigami92** [vuetifyjs/vuetify#9658]
### Problem to solve
We have a textarea in our project that we applied a custom row/line counter instead of a character counter

So it counts every `\n` instead of any character

### Proposed solution
Maybe that could be solved with https://github.com/vuetifyjs/vuetify/issues/9548

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8788 and https://github.com/vuetifyjs/vuetify/issues/9548

**Comment by Shinigami92** [comment]
Want to mention that it is not a duplicate of #8788!
