### ISSUE TITLE
[Bug Report] v-responsive doesn't work in Firefox

### ISSUE THREAD

**Issue by dsanders11** [vuetifyjs/vuetify#9659]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. Start window full screen
2. Shrink horizontally

### Expected Behavior
Card maintains aspect ratio

### Actual Behavior
Card does not maintain aspect ratio

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/aspect-ratios" target="_blank">https://vuetifyjs.com/en/components/aspect-ratios</a>

### Other comments
According to [this](https://stackoverflow.com/a/46846942) StackOverflow post, this is due to how Firefox resolves the padding that Vuetify is using to maintain the aspect ratio. As such, it doesn't look like this technique will ever work in Firefox.

There is quirky behavior, like it *seems* to work if you load the page in a small window, but overall it doesn't work.

**Comment by KaelWD** [comment]
What version?

**Comment by dsanders11** [comment]
@KaelWD, of Firefox? The latest, 70.

**Comment by dsanders11** [comment]
@KaelWD, I don't know if it's applicable, but [this seems to work](https://jsfiddle.net/rfq320xg/1/) to maintain aspect-ratio, pulled [from here](https://css-tricks.com/aspect-ratio-boxes/#article-header-id-6).

**Comment by KaelWD** [comment]
Firefox doesn't implement the flexbox specification correctly: https://stackoverflow.com/a/36783414/2074736
We need to switch to floats to prevent this, but then the content div can't be made full-height, which breaks things even worse. Unless you know how to make something 100% height without flex I'm gonna have to close this as wontfix, the current behaviour is only kinda weird vs completely breaking it for everyone.

**Comment by johnleider** [comment]
Reverted in a01fa36a7 due to https://github.com/vuetifyjs/vuetify/issues/10094
