### ISSUE TITLE
DataTable invalid row order

### ISSUE THREAD

**Issue by megapctr** [vuetifyjs/vuetify#966]
I noticed that DataTable displays rows in invalid order for larger datasets. Repro on codepen: https://codepen.io/anon/pen/BZvxXY

**The fix is to set `total-items` prop. This disables the default sorting function DataTables use.**

Hopefully this will help anyone who stumbles upon the same issue :+1:

Feel free to close this issue, unless you feel the docs should mention that or whatever

**Comment by nekosaur** [comment]
We should be able to fix this with a small correction to the internal sort function

**Comment by fleebzz** [comment]
Thx @megapctr !! You workaround works.

FYI it also happens with a small dataset of ~15 items. I can't figure why one of my items is on top but if @nekosaur sees what's happening I'll let the pros on the subject.
