### ISSUE TITLE
[Bug Report] Readonly slider label click causes value change

### ISSUE THREAD

**Issue by TheOnlyError** [vuetifyjs/vuetify#9660]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
1. Click the label

### Expected Behavior
Value should not change

### Actual Behavior
Value does change

### Reproduction Link
<a href="https://codepen.io/theonlyerror/pen/XWWBxJK?&editable=true&editors=101" target="_blank">https://codepen.io/theonlyerror/pen/XWWBxJK?&editable=true&editors=101</a>

**Comment by KaelWD** [comment]
Broken by #5399
