### ISSUE TITLE
[Documentation] Drawer Example Doesn't Work

### ISSUE THREAD

**Issue by knunery** [vuetifyjs/vuetify#9663]
### Environment

**Browsers:** Chrome 78.0.3904.87
**OS:** Windows 10

### Steps to reproduce
Navigate to https://vuetifyjs.com/en/components/navigation-drawers#playground.

### Expected Behavior
The playground for the navigation drawers doesn't show a drawer.

### Actual Behavior
The playground should allow you to quickly test out the navigation drawer functionality.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/navigation-drawers#playground" target="_blank">https://vuetifyjs.com/en/components/navigation-drawers#playground</a>

**Comment by KaelWD** [comment]
Blame: https://github.com/vuetifyjs/vuetify/commit/66696f71dafafd2390f2773bc1992ab72709c320#diff-e29de58ce6dffa634529defe0e1546ee

**Comment by MajesticPotatoe** [comment]
No longer applicable.

**Comment by kala-here** [comment]
This looks like it is still an issue
![Screenshot 2024-01-10 at 3 55 45 PM](https://github.com/vuetifyjs/vuetify/assets/26551811/b2c3ff43-91f8-436d-8911-3184a277112a)

**Comment by MajesticPotatoe** [comment]
> This looks like it is still an issue 

Its there, Expand your screen/ move the divider. You aren't seeing it right away because mobile breakpoint is in effect

**Comment by kala-here** [comment]
Oof. Gotcha. Thanks!
