### ISSUE TITLE
[Bug Report] v-scroll breaks with v-lazy

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#9664]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
In this example CodePen is reproduced as follows:
1. We click on loadData
2. We scroll and see that it works perfectly
3. Now we click on the filter button and scroll again
4. And we see that the scroll does not work

### Expected Behavior
It is expected to continue working with scroll reduction

### Actual Behavior
This has to scroll correctly

### Reproduction Link
<a href="https://codepen.io/frbuceta/pen/NWWBoYW" target="_blank">https://codepen.io/frbuceta/pen/NWWBoYW</a>

**Comment by KaelWD** [comment]
Don't use v-scroll on an element in a loop.

**Comment by frbuceta** [comment]
> Don't use v-scroll on an element in a loop. It works fine if you bind it directly to the scroll-target element instead.

Even so, when there is horizontal and vertical scrolling, the elements do not load well.

**Comment by frbuceta** [comment]
the element within v-lazy is longer ... how is this possible?
