### ISSUE TITLE
[Feature Request] Send notifications with v-alert from the code

### ISSUE THREAD

**Issue by frbuceta** [vuetifyjs/vuetify#9665]
### Problem to solve
Let's get in the case that we have a plugin that is the API and this breaks, I need to send the user an alert but I can't because I can't call this from that JS file

### Proposed solution
Something like this: https://bootstrap-vue.js.org/docs/components/toast#advanced-usage

**Comment by jacekkarczmarczyk** [comment]
Duplicate of #3037 / #2384
