### ISSUE TITLE
[Feature Request] VDataTable add delay option to loading prop

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#9667]
### Problem to solve
When using server side data for pagination, etc most of the requests are handled back within 100-200 milliseconds.  For that reason it is sort of annoying to see the loading progress bar for that split second.  It would be nice to set a loading delay so that requests shorter than 200 milliseconds don't change the loading progress on the table.

### Proposed solution
Add new Prop:
loading-delay: integer  (milliseconds)  default: 0

This prop should only be in effect if the "loading" prop is TRUE.
This prop needs to be smart enough to cancel the delay once the "loading" prop has been changed to FALSE.

**Comment by nekosaur** [comment]
Thank you for the Feature Request and interest in improving Vuetify. Unfortunately this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
