### ISSUE TITLE
[Bug Report] VDataTable Loading Progress bar pushes content down

### ISSUE THREAD

**Issue by ggedde** [vuetifyjs/vuetify#9668]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
Setting the "loading" prop to true

### Expected Behavior
The Progress bar should be positioned absolute to not effect the layout of the table when loading.

### Actual Behavior
What happens is when the loading prop is set to true and the progress bar is showing the cells and other content below it get pushed down the height of the progress bar.  If your loading is only a few milliseconds then this can be very distracting.

View the CodePen example and click on a header to sort the data.  You will see as it loads it pushes the content down a few pixels

### Reproduction Link
<a href="https://codepen.io/ggedde/pen/PooBgeQ" target="_blank">https://codepen.io/ggedde/pen/PooBgeQ</a>

### Other comments
A quick work around for me at the moment is adjusting this with css
```
.v-data-table__progress [role='progressbar'] {
	position: absolute;
}
```

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetify/pull/10169
