### ISSUE TITLE
[Feature Request] Allow for browser scrollbar

### ISSUE THREAD

**Issue by Stoom** [vuetifyjs/vuetify#9671]
### Problem to solve
It has been a few years and an entirely new version of Vuetify.  Browsers now have overlaying scrollbars unless you force the overflow scroll.

### Proposed solution
Remove the `overflow-y: scroll` from the `html` element

### Related issues
Remove overflow-y from html element #1197

**Comment by KaelWD** [comment]
> Browsers now have overlaying scrollbars unless you force the overflow scroll.

???

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
