### ISSUE TITLE
[Bug Report] Breakpoint and thresholds - Weird behavior

### ISSUE THREAD

**Issue by leoclipet** [vuetifyjs/vuetify#9673]
### Environment
**Vuetify Version:** 2.1.9
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Resize the window and check the boolean value of the different threshold

### Expected Behavior
Below 1280px lgAndUp should be false
Below 800px mdAndUp should be false

### Actual Behavior
Below 1280px lgAndUp is true
Below 800px mdAndUp is true

### Reproduction Link
<a href="https://codepen.io/leococo/full/rNNZyao" target="_blank">https://codepen.io/leococo/full/rNNZyao</a>

**Comment by jacekkarczmarczyk** [comment]
```js
{
      xs: 340,
      sm: 540,
      md: 800,
      lg: 1280,
    }
``` 
means XS=0-340, SM=341-540, MD=541-800, LG=801-1280,XL=1281-Inf, so for width below 1280px (and above 800px) it will be LG

However there's a bug that causes that scrollBarWidth is not set to 0 https://github.com/vuetifyjs/vuetify/blob/9a797d887553a448162764b51edebd3f5332829b/packages/vuetify/src/services/breakpoint/index.ts#L67

**Comment by jacekkarczmarczyk** [comment]
closing as the 0 scrollWidth is actually a different issue and there's 
already https://github.com/vuetifyjs/vuetify/pull/9401
