### ISSUE TITLE
[Bug Report] Parent persistent modal should not animate when clicking on child modal

### ISSUE THREAD

**Issue by kennedyoliveira** [vuetifyjs/vuetify#9675]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
1 -> Click on "Open Dialog 1"
2 -> In the new dialog click on "open dialog 2"
3 -> Click anywhere in the second modal, it will make the parent modal, the first one animate

### Expected Behavior
It should NOT make the parent modal animate

### Actual Behavior
The parent modal animate

### Reproduction Link
<a href="https://codepen.io/kennedyoliveira/pen/jOOvxgJ?&editable=true&editors=101" target="_blank">https://codepen.io/kennedyoliveira/pen/jOOvxgJ?&editable=true&editors=101</a>

**Comment by diazemiliano** [comment]
The same behavior having a `fullscreen + persistent` parent dialog with a `persistent` dialog.
Reproduction Link: https://codepen.io/diazemiliano/pen/xxbVGwY

**Comment by Webifi** [comment]
This issue started in 2.1.7.

**Comment by KaelWD** [comment]
ba99a45c

**Comment by Webifi** [comment]
Here's my hack of a work-around for the issue until it's fixed.  (Issue was blocking release of an app.)
https://codepen.io/webifi/pen/BayKLJv

I'm just watching when the dialog opens, then modifying its animateClick function:
`watch: {
    dialog (v) {
      this.$refs.dialog1.animateClick = () => {}
    }
  }`

**Comment by KaelWD** [comment]
Fixed by 118d1d070ca65bc1c9e69a299e93486381fbddd5
