### ISSUE TITLE
[Feature Request] Should allow defining default props globally like dense, outlined etc. (good to have)

### ISSUE THREAD

**Issue by mr-mad-e** [vuetifyjs/vuetify#9677]
### Problem to solve
Don't have to set props every time like outlined, dense

### Proposed solution
Should allow defining default props globally

`new Vuetify({
  default: {
    props: {
      dense: true,
      outlined: true
    }
  }
})`

**Comment by ibrahimBeladi** [comment]
[It is in the roadmap](https://vuetifyjs.com/en/introduction/roadmap), It will be coming around Q1 of 2020 in v2.3 Release (Orion)

**Comment by uphone** [comment]
what is default props?

**Comment by uphone** [comment]
> ### Problem to solve
> Don't have to set props every time like outlined, dense
> 
> ### Proposed solution
> Should allow defining default props globally
> 
> `new Vuetify({ default: { props: { dense: true, outlined: true } } })`

is not work:
// vuetify.js
import Vue from 'vue';
import Vuetify from 'vuetify/lib';
import i18n from './i18n';
Vue.use(Vuetify);
export default new Vuetify({
  lang: {
    t: (key, ...params) => i18n.t(key, params),
  },
  // is not work...
  default: {
    props: { color: 'primary' }
  }
});

`
// xx.vue
<v-row>
      <v-toolbar dense>
        <v-btn>Test</v-btn>
      </v-toolbar>
    </v-row>
`

**Comment by husayt** [comment]
@KaelWD just to be clear for everyone, is this now possible with presets in v2.2?

**Comment by MajesticPotatoe** [comment]
@husayt This is not possible right now with presets. Presets do provide configuration to the options, but only already available options. Its on the roadmap slated for v3.1.

**Comment by ctwhome** [comment]
is this part now of the v3 release, not anymore for v2?

**Comment by isacRU11** [comment]
this feature not workin in `@nuxt/vuetify` ?
i use `@nuxt/vuetify` version 2.0.0-beta.2

**Comment by ddsultan** [comment]
is there any workaround other than applying the property to each component?

**Comment by snarkeystarkey** [comment]
@johnleider I'm confused about the project management labeling...

Is this feature implemented, currently? I'm struggling to find documentation.

Thank you for everything you do - Sorry to bother you!

**Comment by nekosaur** [comment]
This will be available in Vuetify 3.0, which has not been released yet.

**Comment by snarkeystarkey** [comment]
> This will be available in Vuetify 3.0, which has not been released yet.

Thank you for the clarification!
