### ISSUE TITLE
[Bug Report] Activator not working if queryselector not hit anything on mount

### ISSUE THREAD

**Issue by zssng** [vuetifyjs/vuetify#9679]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
click btn not show the menu ,change `myactivator:false` to `myactivator:true` works

### Expected Behavior
Activator work on all element created anytime

### Actual Behavior
only the element present at mount works

### Reproduction Link
<a href="https://codepen.io/zssng/pen/eYYLPrz" target="_blank">https://codepen.io/zssng/pen/eYYLPrz</a>

**Comment by KaelWD** [comment]
It isn't magic, and we're not attaching a mutation observer to the entire document just to watch for an activator. You can do the querySelector yourself and pass the element itself instead of a selector string.
