### ISSUE TITLE
[Bug Report] Scrollbar of filled textarea overlaps with clearable icon

### ISSUE THREAD

**Issue by TheOnlyError** [vuetifyjs/vuetify#9681]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
None (just open the link and observe)

### Expected Behavior
Scrollbar should not overlap with the clearable icon

### Actual Behavior
Scrollbar does overlap with the clearable icon

### Reproduction Link
<a href="https://codepen.io/theonlyerror/pen/BaaOvLZ?&editable=true&editors=101" target="_blank">https://codepen.io/theonlyerror/pen/BaaOvLZ?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
Without `filled` prop it also doesn't look good

**Comment by TheOnlyError** [comment]
Just wanted to mention this bug is still present in the current version (2.2.15) of vuetify.

**Comment by mdavis95** [comment]
The scrollbar with clearable is pretty odd even when it does not directly overlap

**Comment by payammeyer** [comment]
A fix for this would be very much appreciated, here's an example of what it looks like in one of our apps:

![image](https://user-images.githubusercontent.com/9900587/81320359-11042a80-905f-11ea-8b23-c5c654a96f16.png)

**Comment by m0bbin** [comment]
Bump still an issue currently in June 2020.
