### ISSUE TITLE
[Documentation] No translation for description

### ISSUE THREAD

**Issue by GLeBaTi** [vuetifyjs/vuetify#9688]
### Environment

**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 8.1

### Steps to reproduce
Open non-english page and view API table

### Expected Behavior
Maybe show English text if field have no translation?

### Actual Behavior
Empty description field in API table for non-english translations. 

### Reproduction Link
<a href="https://vuetifyjs.com/ru/components/grids" target="_blank">https://vuetifyjs.com/ru/components/grids</a>

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/68846644-fbd9bf00-06ff-11ea-83b5-bb1bcade5d78.png)

**Comment by jacekkarczmarczyk** [comment]
Hmm, shouldn't it show the english version?

**Comment by GLeBaTi** [comment]
![Снимок](https://user-images.githubusercontent.com/693132/68851579-2f5c1f80-06e7-11ea-85da-7018f1615ba3.PNG)

**Comment by jacekkarczmarczyk** [comment]
That's what I just said
