### ISSUE TITLE
[Feature Request] Add specific vuetify prefix to ALL classes declarations

### ISSUE THREAD

**Issue by simonmaass** [vuetifyjs/vuetify#9689]
### Problem to solve
There used to be a feature request that already adressed this issue (https://github.com/vuetifyjs/vuetify/issues/1561) but was closed before all classes were prefixed. Missing are the following:
* [ ] App
* [ ] Grid

There are a lot of other frameworks or utility frameworks out there (for example tailwindcss) that create very weird and unwanted results in combination. Of course you could also prefix the utility framework but that would just result in having to write the prefix over and over...
 

### Proposed solution
Please finish the started efford to prefix all vuetify class including:
- [ ] App
- [ ] Grid
  - [ ] Colum
  - [ ] Container
  - [ ] Flex
  - [ ] Layout
  - [ ] Offset
  - [ ] Row
  - [ ] Wrap
  - [ ] ... ?

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
