### ISSUE TITLE
[Documentation] "input" documentation examples seems broken

### ISSUE THREAD

**Issue by guillaumethibault** [vuetifyjs/vuetify#9690]
### Environment
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Go to examples on the documentation page

### Expected Behavior
Examples should work

### Actual Behavior
Examples are not working

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/inputs#inputs" target="_blank">https://vuetifyjs.com/en/components/inputs#inputs</a>

**Comment by MajesticPotatoe** [comment]
Can you elaborate?

**Comment by guillaumethibault** [comment]
Yes sorry.
I think that the examples are broken because I cannot use them as they should behave.
I cannont click, enter text or do anything to check rules explained in forementionned examples.

![image](https://user-images.githubusercontent.com/7540939/68928772-3177ba00-078b-11ea-894a-f23bf0c0aa5c.png)

**Comment by KaelWD** [comment]
You want https://vuetifyjs.com/en/components/text-fields

v-input is kinda useless and will be removed from the documentation at some point

**Comment by guillaumethibault** [comment]
Ok, thanks a lot, that's what is was looking for.
