### ISSUE TITLE
[Feature Request] Expose transition hooks

### ISSUE THREAD

**Issue by DanielStefanK** [vuetifyjs/vuetify#9691]
### Problem to solve
We should be able to run code base on the state of the transition.

### Proposed solution
Expose the default transition component events (before-enter, enter, after-enter, enter-cancelled, before-leave, leave, after-leave, leave-cancelled) on all transition components.

**Comment by KaelWD** [comment]
They are, some can only be used as camelCase though because vue overwrites instead of merging listeners with different casing.

**Comment by jacekkarczmarczyk** [comment]
Dialogs etc could expose content's transition events, they don't do it now afaik

**Comment by KaelWD** [comment]
@jacekkarczmarczyk #6504
