### ISSUE TITLE
[Feature Request] Add a slot in the v-data-footer before the pagination controls

### ISSUE THREAD

**Issue by fontzter** [vuetifyjs/vuetify#9695]
### Problem to solve
This would help keep buttons and other controls associated with the table data close to it and not require more real estate. There is typically a good deal of empty space to the left of the controls in the footer. One could put an Add button or a switch to toggle the data for example.

### Proposed solution
Add a slot in the v-data-footer right before the v-data-footer__select element to utilize the space.

**Comment by JungComdok** [comment]
A similar feature was allready added to the v1.2.0 milestone with Issue #4691.
The slots got lost with the rework of the datatable in v2.

**Comment by fontzter** [comment]
@JungComdok good catch! The only difference is that I think it should be before the page controls. This would keep them consistently in the same place regardless of whether the new slot is used. Perhaps both (two slots) would be even better -- `footer.append` and `footer.prepend`

**Comment by fontzter** [comment]
A hacky css work-around for now: https://codepen.io/fontzter/pen/MWwGzjv

**Comment by denmasyarikin** [comment]
Yes, I need for bulk action buttons

**Comment by jelle-eastground** [comment]
This slot would be great.

**Comment by abcox** [comment]
> A hacky css work-around for now: https://codepen.io/fontzter/pen/MWwGzjv

Your CSS helped me refine approach using the v-slot.  This works:

`
		      <template
		        v-slot:footer
			    >
			    <div style="margin: 0px 0px -45px 15px">
            	  <v-fab-transition>
	                <v-btn
	                  color="primary"
	                  fab
	                  dark
	                  relative
	                  float
	                  >
	                  <v-icon>
	                	mdi-plus
	                  </v-icon>
	                </v-btn>
            	  <v-fab-transition>
            	</div>
              </template>
`
