### ISSUE TITLE
[Feature Request] V-expansion-panels icon position

### ISSUE THREAD

**Issue by beerwin** [vuetifyjs/vuetify#9698]
### Problem to solve
We have some designs where the icon is on the left side of the expansion header title.

### Proposed solution
An option to place the icon on the left side, just before the header text.

**Comment by KaelWD** [comment]
You can do this with CSS `order` or by modifying the default slot.

**Comment by roblugt** [comment]
Shame this has been closed; we need this functionality too and the closure comment does not really give sufficient signposting to a workable solution.

**Comment by johngoben-righteye** [comment]
I agree that the closure comment did not have significant sign posting for a workable solution. I did manage to figure out a solution using `order` as a clue.

`
<template>
	<v-expansion-panel-header>
	    <template v-slot:actions>
	        <v-icon class="icon">$expand</v-icon>
	    </template>
	    <span class="header">{{ headerText }}</span>
	</v-expansion-panel-header>
</template>

<style>
	.icon {
	    order: 0;
	}

	.header {
	    order: 1;
	}
</style>
`

**Comment by ogmo0n** [comment]
How about if I need the default chevron icon on the right and a custom icon on the left of the header?

**Comment by ogmo0n** [comment]
Never mind - I nested my icon within the v-expansion-panel-header and achieved what I was going for

**Comment by arsh13** [comment]
> I agree that the closure comment did not have significant sign posting for a workable solution. I did manage to figure out a solution using `order` as a clue.
> 
> ```
> <template>
> 	<v-expansion-panel-header>
> 	    <template v-slot:actions>
> 	        <v-icon class="icon">$expand</v-icon>
> 	    </template>
> 	    <span class="header">{{ headerText }}</span>
> 	</v-expansion-panel-header>
> </template>
> 
> <style>
> 	.icon {
> 	    order: 0;
> 	}
> 
> 	.header {
> 	    order: 1;
> 	}
> </style>
> ```

I was stuck at the same thing today. There's no documentation about how to shift icons to the left too.
Thanks @johngoben-righteye, your solution saved a lot of my efforts.

**Comment by surajsharmadev** [comment]
.v-expansion-panel-header {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
    }

**Comment by RoboVij** [comment]
A workaround: https://stackoverflow.com/a/72444901

**Comment by beerwin** [comment]
Having to resort to CSS hacks kinda defeats the purpose of using a styled component. At the other end @RoboVij's solution works well (abusing the default slot). I think that workaround could be added to the documentation.
