### ISSUE TITLE
Datatable 'rows per page' menu items hidden by scroll bar

### ISSUE THREAD

**Issue by ptrbrynt** [vuetifyjs/vuetify#970]
Using Safari 10.1.1 on macOS 10.12.5

<img width="98" alt="screen shot 2017-07-12 at 19 51 26" src="https://user-images.githubusercontent.com/24222738/28134708-ae1b1388-673b-11e7-8c21-70023aff164a.png">

Reproducible on the Vuetify website: https://vuetifyjs.com/components/data-tables

Basically doesn't look like the drop-down is wide enough to accommodate the scrollbar.

**Comment by johnleider** [comment]
This is a valid bug report, but, rules are rules!
\---
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
