### ISSUE TITLE
[Feature Request] Access the "close" of a chip so we can display different tooltip

### ISSUE THREAD

**Issue by leoclipet** [vuetifyjs/vuetify#9701]
### Problem to solve
I would like to be able to display a different tool-tip when hoovering a chip and its close button.

Example: "Click to activate", when hoovering the chip "Click to delete" when hoovering the close button

### Proposed solution
Give access to the "close" slot so we can achieve this

https://codepen.io/leococo/pen/abbQpGq

**Comment by johnleider** [comment]
resolved by #13192

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
