### ISSUE TITLE
[Documentation] Sorts Incorrectly in Demo When Value is a Percentage

### ISSUE THREAD

**Issue by knunery** [vuetifyjs/vuetify#9704]
### Environment

**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Sort by the Iron(%) column.

### Expected Behavior
The column is sorted by the percentage value.

### Actual Behavior
Sorts the % values lexically.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/data-tables#examples" target="_blank">https://vuetifyjs.com/en/components/data-tables#examples</a>

**Comment by MajesticPotatoe** [comment]
duplicate #7149
