### ISSUE TITLE
[Bug Report] Glitch with window and textfield

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#9707]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.15.0

### Steps to reproduce
Put a `<v-text-field>` inside of a `<v-window-item>`

### Expected Behavior
Display content below the window without a glitch.

### Actual Behavior
Content below the window moves up and down when loading a window.

### Reproduction Link
<a href="https://codepen.io/thomaskientz/pen/RwwqYMW" target="_blank">https://codepen.io/thomaskientz/pen/RwwqYMW</a>

**Comment by KaelWD** [comment]
v-text-field has a top margin that is collapsed until its parent is absolutely positioned: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing

Putting the text field in an extra div, adding `class="mt-0"`, or adding a small amount of padding to  `.v-window-item` will prevent this.
