### ISSUE TITLE
[Documentation] Selection controls description in list item group component is unclear

### ISSUE THREAD

**Issue by mitar** [vuetifyjs/vuetify#9712]
### Environment

**Browsers:** Firefox 70.0
**OS:** Ubuntu undefined

### Discussion

So reading the current description of this section I am lacking understanding why would this be useful. So currently the main parts are:

```
<v-list-item :value="item">
...
<v-checkbox
  :input-value="active"
  :true-value="item"
  @click="toggle"
></v-checkbox>
```

This looks equivalent to:

```
<v-list-item :value="item">
...
<v-checkbox
  v-model="active"
  @click="toggle"
></v-checkbox>
```

So why this more verbose way? If this is not some legacy example, I think it is missing explanation for rationale and some description about cases in which this would be useful, especially over the `v-model` approach.

### Reproduction Link

<a href="https://vuetifyjs.com/en/components/list-item-groups#selection-controls" target="_blank">https://vuetifyjs.com/en/components/list-item-groups#selection-controls</a>

**Comment by KaelWD** [comment]
Assigning to a function argument overwrites it, it isn't reactive. 

```js
h('v-list-item', {
  scopedSlots: {
    default ({ active, toggle }) {
      active = false // Not reactive
      // h('v-checkbox', {...
    }
  }
})
```

The example is also incorrect, you shouldn't use `@click` on a checkbox.

**Comment by KaelWD** [comment]
Oh I see what you mean, yeah there isn't really any reason to be using true-value there. The existing description contradicts itself.

**Comment by KaelWD** [comment]
In fact, true-value doesn't even do anything unless combined with false-value: #7269

**Comment by mitar** [comment]
> The example is also incorrect, you shouldn't use @click on a checkbox.

Hm, all examples using [list & checkbox](https://vuetifyjs.com/en/components/lists#subheadings-and-dividers) uses `@click`.

**Comment by mitar** [comment]
So I think `v-mode="active"` is invalid everywhere and should be replaced with `:input-value="active"`.

**Comment by mitar** [comment]
In fact, using either `v-model="active"` or `:input-value="active"` behaves strangely if I use `tab` to move around and press space to select things:
* I can select a list item indepdentently from the checkbox, list item can get grayed out, or the checkbox.
* By pressing the space I can manage to get things out of sync: it can happen that list item is activated, but checkbox is not checked, or the opposite.

**Comment by KaelWD** [comment]
That's why you shouldn't use `@click`, it doesn't reflect the actual state of the checkbox.

**Comment by mitar** [comment]
Yes, the above is without `@click`.

**Comment by KaelWD** [comment]
Oh, because you need `@change` too, as I said above v-model with a scoped slot won't propagate the value back out.

**Comment by mitar** [comment]
OK, so the following seems to work best:

```
<v-checkbox
  :input-value="active"
  @change="toggle"
  @click="toggle"
></v-checkbox>
```

So you do need `@click` to make it work with `space`. You do need `@change` to sync up changes back to the state.
