### ISSUE TITLE
[Bug Report] Item added via timeout does not appear in treeview

### ISSUE THREAD

**Issue by choofy** [vuetifyjs/vuetify#9715]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.120
**OS:** Windows 10

### Steps to reproduce
See codepen. Open root item in the treeview and wait. First, the icon will change to expanded. Then, after 1.5 sec (when timeout fires), it changes back to non-expanded.

### Expected Behavior
It is expected that after 1.5 sec, when the timeout fires, the new item that is added during the timeout is in fact added and the root node is opened up. 

### Actual Behavior
The root node closes after 1.5 seconds.

### Reproduction Link
<a href="https://codepen.io/choofy01/pen/ExxGpoW" target="_blank">https://codepen.io/choofy01/pen/ExxGpoW</a>

### Other comments
Note 1: Locally, on my computer, the behaviour is the same (item does not get added), but in addition to this, I get the following error:

vue.runtime.esm.js:1888 TypeError: Cannot set property 'vnode' of undefined
    at o.register (VTreeview.js:260)
    at o.created (VTreeviewNode.js:132)
    at ne (vue.runtime.esm.js:1854)
    at Nn (vue.runtime.esm.js:4213)
    at o.t._init (vue.runtime.esm.js:5002)
    at new o (vue.runtime.esm.js:5148)
    at sn (vue.runtime.esm.js:3283)
    at init (vue.runtime.esm.js:3114)
    at p (vue.runtime.esm.js:5972)
    at f (vue.runtime.esm.js:5919)

Unfortunately, I cannot reproduce this error, I already spent a lot of time on this. I hope that the attached codepen is in fact the same issue.

I know that the following workaround works for my case (see line between >> and <<):

register(node) {
      >> this.buildTree([node.item]); <<
      const key = getObjectValueByPath(node.item, this.itemKey);
      this.nodes[key].vnode = node;
      this.updateVnodeState(key);
    },

Note 2: Of course, I could wait for the item to be added before returning from fetchChildren. But that is not my use case. I simulate the case here where "spontaneous" updates of the children come in later on.

**Comment by choofy** [comment]
I made a mess of my codepen... It did not save my changes.. I will fix it first..

**Comment by choofy** [comment]
The proper codepen is now mentioned in the issue description.
It is: https://codepen.io/choofy01/pen/ExxGpoW
Apologies for the inconvenience.

**Comment by johnleider** [comment]
This is not the described way to use that function. More information can be found in this example: https://vuetifyjs.com/components/treeview#async-items

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
