### ISSUE TITLE
[Bug Report] Click a button within a tooltip

### ISSUE THREAD

**Issue by leoclipet** [vuetifyjs/vuetify#9717]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
- Click the button to toogle the tooltip
- Try to click on the button within the tooltip

### Expected Behavior
You should be able to click on a button which is in a tooltip

### Actual Behavior
The button does not respond

### Reproduction Link
<a href="https://codepen.io/leococo/pen/NWWeEgm" target="_blank">https://codepen.io/leococo/pen/NWWeEgm</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/commit/2d2312a220713c88484a03532e8cebae98dd0d45

**Comment by KaelWD** [comment]
MD2 tooltips are not interactive. You probably want to use a snackbar there instead.
