### ISSUE TITLE
Enhancement Request | v-text-field custom colors

### ISSUE THREAD

**Issue by 4eveRS** [vuetifyjs/vuetify#972]
It would be nice if it was possible to set other colors (custom colors) for the v-text-field line. Right now it is static to blue if everything is ok and red if something is wrong (required/length).

It will be a nice addition to match all kinds of themes created by the vuetify users.

**Comment by Phunky** [comment]
One way to approach this would be to utilise currentColor throughout the component for the main highlight colour. 

This would simplify overriding this to just defining the color property on the components container and having it applied through the other components.

Obviously this won't cover everyones need, but could be a simple improvement on the current state.
