### ISSUE TITLE
[Bug Report] FontAwesome breaks update:open functionality of v-treeview

### ISSUE THREAD

**Issue by LoveSponge** [vuetifyjs/vuetify#9722]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0, Google Chrome, Safari, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
When using FontAwesome (setting { icons: { iconFont: 'fa' } } in vuetify.js/ts and loading a v-treeview, the update:open event is not fired when clicking on the arrow.

This was found after hours of looking for every other type of solution there could have been and then asking the simple question "could you try changing your font to material design icons?"

Hilariously enough, an npm i, a setting, a rebuild and refresh later, it magically started working...

### Expected Behavior
Arrows should fire the event to change the state of the treeview.

### Actual Behavior
Arrows do not fire the event.

### Reproduction Link
<a href="https://codepen.io/LoveSponge/pen/PooXMdP?editors=1010" target="_blank">https://codepen.io/LoveSponge/pen/PooXMdP?editors=1010</a>

### Other comments
The codepen does not work properly because fonts are not loading correctly. This has to be replicated locally, if anyone has a fix for codepen please comment here to save the dev's time.

**Comment by MajesticPotatoe** [comment]
seems to work <https://codepen.io/majesticpotatoe-the-bashful/pen/JjjxPQX>

**Comment by LoveSponge** [comment]
I'm not sure how you are showing the icons on codepen but i assure you this was not working on a local machine until the font was changed from fa to mdi.

Also i'm unable to alternate between mdi and fa on your pen?

**Comment by MajesticPotatoe** [comment]
in codepen, you add mdi/fa via css (not js)
if you do not have icons locally, there's a high chance your icons are not installed properly. 2.x uses `mdi` by default. Verify you have it installed properly using the following [instructions](https://vuetifyjs.com/en/customization/icons#install-font-awesome-5-icons)

( i only did `fa` - codepens updated to include `mdi` now)

**Comment by LoveSponge** [comment]
I tested it with a fresh install of vuetify on a freshly created Vue app. using the versions described above. I'm sorry but I'm not basing the output of the results on this from codepen.
Please simply run 2 commands and paste in the code from the codepen and you will see all you need to recreate this.

`Vue create tree-test`
`Vue add vuetify`

Paste the code directly into app.vue

Change the config in plugins/vuetify.js and witness the bug happening in your browser.

**Comment by jacekkarczmarczyk** [comment]
We accept github repos as a reproduction

**Comment by LoveSponge** [comment]
Ah I will link a github repo that can be cloned and tested; thankyou - please be aware I am afk atm so this will likely not happen until tomorrow.

**Comment by jacekkarczmarczyk** [comment]
No problem, to make sure that have all information please also show which options did you select while running both commands (`vue create` and `vue add`)

**Comment by LoveSponge** [comment]
Yes absolutely :+1:

**Comment by LoveSponge** [comment]
See below link to repository which should show the problem.... Except it doesn't.

I'm not really sure what to say at this point; Yesterday I witnessed, clear as day, a tree view that was using 'fa' fonts that simply was not allowing dropdown arrows to be clicked, wasn't even firing the event. All other functionality was working as expected. After downloading @mdi/font and switching to it, like i said in the description, the click events and arrows started working.

I included the repo anyway but all I can speculate was that it was some deeper problem with using fa fonts and the codebase... But what????

Here is the repo anyway;

https://github.com/LoveSponge/vuetify-tree-test

**Comment by LoveSponge** [comment]
For anyone else that happens accross this, it was because the following was in the index.html source:

```
  <script defer src="https://pro.fontawesome.com/releases/v5.5.0/js/solid.js"
    integrity="sha384-VxezC2Q+YoC+yUILib+HlmOsFiqNzYtQIXsHYY6ST7QZVfgBNs2giKE97ijGMgUH" crossorigin="anonymous">
  </script>
  <script defer src="https://pro.fontawesome.com/releases/v5.5.0/js/fontawesome.js"
    integrity="sha384-oPma1F1txBbqTG+1O7BEx0A/qFtD+R661ULJLmI9RDQ0PfbRP1tQU3vBIBbJIAxL" crossorigin="anonymous">
  </script>
```
Removing it fixes the issue.

**Comment by KaelWD** [comment]
Duplicate of #3505
