### ISSUE TITLE
[Bug Report] v-edit-dialog not giving dense inputs enough space

### ISSUE THREAD

**Issue by icleolion** [vuetifyjs/vuetify#9724]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Please see codepen

### Expected Behavior
Autocomplete label to stay within confines of dialog when autocomplete is focused

### Actual Behavior
Autocomplete label moves past the top of the dialog and becomes largely unreadable

### Reproduction Link
<a href="https://codepen.io/icleolion/pen/JjjxRRv" target="_blank">https://codepen.io/icleolion/pen/JjjxRRv</a>

### Other comments
Works fine when dense prop is removed from autocomplete

**Comment by KaelWD** [comment]
Inputs are supposed to have some top padding to make room for the label:
![image](https://user-images.githubusercontent.com/16421948/69139028-d8ee4700-0b13-11ea-97fb-4a28ed599854.png)
![image](https://user-images.githubusercontent.com/16421948/69139060-e3104580-0b13-11ea-8109-19b7134fda10.png)

**Comment by johnleider** [comment]
We are removing `v-edit-dialog` in v3 and as such, this Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
