### ISSUE TITLE
[Bug Report] Master branch CI test fail

### ISSUE THREAD

**Issue by YipingRuan** [vuetifyjs/vuetify#9728]
### Environment
**Vuetify Version:** 2.1.10
**Last working version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Clone master branch

\vuetify\packages\vuetify> yarn run test

### Expected Behavior
Test pass

### Actual Behavior
Test fail
VDialog.ts › should not close if persistent and hide-overly when click outside

    expect(jest.fn()).toHaveBeenCalled()

    Expected mock function to have been called, but it was not called.

      342 |     expect(input).toHaveBeenCalledWith(true)
      343 |     wrapper.vm.closeConditional(new Event('click'))
    > 344 |     expect(clickOutside).toHaveBeenCalled()

### Reproduction Link
<a href="https://travis-ci.org/vuetifyjs/vuetify/jobs/613798191?utm_medium=notification&utm_source=github_status" target="_blank">https://travis-ci.org/vuetifyjs/vuetify/jobs/613798191?utm_medium=notification&utm_source=github_status</a>

### Other comments
https://github.com/vuetifyjs/vuetify/commit/f11d8454320a671392bf96c9076b2f39d29d11e6#diff-6d73f6698e69f2b6c718dfed6b89cd34

this.$emit('click:outside') was removed and the test case will not pass

**Comment by KaelWD** [comment]
`jest -o` wasn't doing anything: 12875d65dc6d3122612d5fb4f82f391e978129c2

fixed in 843cffabb90182822faa22b9fcb2047de02c0b94

The #volunteers channel on discord is probably better for things like this
