### ISSUE TITLE
v-toolbar fixed with extended prop is overflowing content

### ISSUE THREAD

**Issue by dohomi** [vuetifyjs/vuetify#973]
An extended `toolbar fixed` is overflowing the main content of a page. Here a codepen as a showcase:
https://codepen.io/anon/pen/WOPQMr

**Comment by dohomi** [comment]
A second showcase for showing the content overflow is with the v-tab example included and fixed toolbar prop.
https://codepen.io/anon/pen/yXZYKg

**Comment by johnleider** [comment]
Fixed with #969

**Comment by Denfie** [comment]
Solve this fix also the problem with [#5 Flexible toolbar and card toolbar](https://vuetifyjs.com/components/toolbars) when the toolbar is fixed and have card toolbar as overlay?
