### ISSUE TITLE
[Bug Report] v-text-field messages are not reactive when messages slot is used to show html

### ISSUE THREAD

**Issue by cars10** [vuetifyjs/vuetify#9730]
### Environment
**Vuetify Version:** 2.1.10
**Last working version:** 2.1.8
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
Before 2.1.9 you could put html in the `messages` prop of a `v-text-field`. With 2.1.9 that changed and you have to use a scoped slot to show html. If you do use a slot you can correctly show html but the messages are no longer reactive. Updating the original message does not update the message anymore, this works when you don't use a slot.

The pen shows the broken behaviour. Click the "change message" button to see that only the messages in the first input are updated.

### Expected Behavior
Message should update correctly

### Actual Behavior
Message does not update

### Reproduction Link
<a href="https://codepen.io/cars10/pen/Rwwvgyy?editors=1010#0" target="_blank">https://codepen.io/cars10/pen/Rwwvgyy?editors=1010#0</a>

**Comment by tpodom** [comment]
This also seems to affect the display of the validation error messages.  When using the scoped slot the text is not changing from the hint text to the validation error message.  If I remove the scoped slot the validation error is shown correctly.  In debugging though, I see that the v-messages is created with the validation message and the scoped slot is called with the validation message but the new contents are never rendered.

I did find that if I added an extra attribute to the element for the transition-group in VMessage that contained the contents of this.value then that attribute in the DOM had the correct text set.

**Comment by tpodom** [comment]
I found that if I change VMessage to not pass innerHTML as undefined then the slot works correctly:

```javascript
      const innerHTML = !slot ? escapedHTML : undefined;
      const domProps = !slot ? { innerHTML } : undefined;
      return this.$createElement('div', {
        staticClass: 'v-messages__message',
        key,
        domProps
      }, slot);```

I don't really know if that's the correct solution because I don't really understand why innerHTML set to undefined would cause the slot children not to re-render.

**Comment by KaelWD** [comment]
Thanks for investigating @tpodom, probably just vue trying to be clever and not updating children if innerHTML is present.

**Comment by Paulsky** [comment]
Do you have a quick fix or workaround @tpodom ?

**Comment by Paulsky** [comment]
Nevermind. I created a quick fix for this: https://codepen.io/Paulsky/pen/abbeoPE?editors=1010#0 

Don't know what happend, some kind of patch? But the changes on the hint attribute are breaking changes for me; https://github.com/vuetifyjs/vuetify/issues/9730
