### ISSUE TITLE
[Bug Report] Dark theme not applied to v-row

### ISSUE THREAD

**Issue by BasilaryGroup** [vuetifyjs/vuetify#9733]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Create a v-container that contains a v-row and v-col. Toggle between dark and light theme.

### Expected Behavior
The v-row background color should change to use the dark theme background color.

### Actual Behavior
The v-row background color does not change. Other components such as v-col use the dark theme background color.

### Reproduction Link
<a href="https://codepen.io/DavidKyle/pen/GRRzGoo" target="_blank">https://codepen.io/DavidKyle/pen/GRRzGoo</a>

**Comment by KaelWD** [comment]
v-row does not normally have a background colour, you've used `class="grey lighten-5"`
