### ISSUE TITLE
[Documentation] Add redirect links to quickly navigate to component documentation.

### ISSUE THREAD

**Issue by ScottSEA** [vuetifyjs/vuetify#9735]
### Problem to solve
Currently, to get to the documentation for a component (v-card, for example) I usually go to google and type "vuetify v-card", and the first result is usually the documentation link for that component.  

### Proposed solution
It would be much faster, at least in  my opinion, if I could type `vuetifyjs.com/en/components/` (which is usually already there or will autofill) and then just add the component I'm looking for, e.g. `vuetifyjs.com/en/components/v-card` and have it redirect to `/cards` or just show the same content.  No googling, no searching, just go right to what I'm looking for.

**Comment by johnleider** [comment]
Recently added this guide https://vuetifyjs.com/en/resources/search-engine/

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
