### ISSUE TITLE
[Feature Request] treeview track indeterminate nodes

### ISSUE THREAD

**Issue by snoopy83101** [vuetifyjs/vuetify#9736]
### Problem to solve
treeview partially selected?

when selection-type = 'leaf'

i hope get partially node.  But I can't do it.. 

 

### Proposed solution
I think this is a functional defect

**Comment by snoopy83101** [comment]
![image](https://user-images.githubusercontent.com/24613784/69204248-513f2180-0b81-11ea-9154-e2d393989bf6.png)

**Comment by Leespiker** [comment]
In the meantime, [here's a way](https://codepen.io/Leespiker/pen/abOgJXo) to track indeterminate and non-leaf nodes in leaf mode.

**Comment by KaelWD** [comment]
Duplicate of #6590
