### ISSUE TITLE
[Bug Report] v-date-picker with range is allow to select same date as range

### ISSUE THREAD

**Issue by mahammad8564** [vuetifyjs/vuetify#9746]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
select a date 
select the same date

### Expected Behavior
should not allow selecting same date as a range

### Actual Behavior
it allows selecting same date as a range
i.e, 2019-11-20 ~ 2019-11-20

### Reproduction Link
<a href="https://codepen.io/mahammad8564-the-animator/pen/zYYWwgQ?editors=1011" target="_blank">https://codepen.io/mahammad8564-the-animator/pen/zYYWwgQ?editors=1011</a>

**Comment by MajesticPotatoe** [comment]
Why not? Don't really see any harm in allowing it, and can have practical applications. Possibly a FR to disable the functionality IMO would be more appropriate (though can also be achieved in userland)

**Comment by myleslee** [comment]
I agree with MajesticPotatoe. Suppose you run a report that allows you to specify the date range, and you can either get data for a range of dates or just for one specific day.

**Comment by johnleider** [comment]
This is not a bug.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
