### ISSUE TITLE
[Feature Request] VDataTable/VDataIterator select element from value prop

### ISSUE THREAD

**Issue by arielnmz** [vuetifyjs/vuetify#9748]
### Problem to solve
Currently, the value prop is used to communicate back the currently selected row, but apparently there's no way of programatically setting the selected row, i.e. setting the value of the prop does nothing

### Proposed solution
Maybe the quickest solution would be to expose a selectByKey method that takes the key or the index of the row to select, which also triggers the selection event.

**Comment by KaelWD** [comment]
> setting the value of the prop does nothing

No it doesn't: https://codepen.io/kaelwd/pen/qBBvoyq?&editable=true&editors=101

You're doing something else wrong.

**Comment by arielnmz** [comment]
@KaelWD I was just checking some workarounds and actually there's a catch, if the table rows haven't finished rendering at the moment you set the value prop, some elements seem to not update correctly. Let me elaborate:

Let's say we have the following component layout, and that the table initally has no items:

```
<v-data-table :items="items" v-model="selected">
  <template v-slot:item="item,isSelected">
    <tr>
      <td>{{isSelected}}</td>
      <td>
        <v-checkbox
          :value="isSelected"
        />
      </td>
    </tr>
  </template>
</v-data-table>
```

And then some event sets the value of "items", e.g. Apollo. As soon as the new "items" var is set, a watch may be triggered with the new values:

```
watch: {
  items (nv) {
    const vm = this

    vm.selected = [nv[0]] // Selecting the first one for example
  }
}
```

In this case the value of "selected" gets updated properly and indeed the row is marked as selected, but an inner element may not catch up with the new state and would not render correctly. In other words, the first column would correctly show "true" but the second one (the checkbox) will show up as an unmarked checkbox.

![image](https://user-images.githubusercontent.com/24735547/69320498-f0f2c300-0c06-11ea-853e-3f5a4080488a.png)

So, a workaround is to wait for all the children to render before selecting the row, like this:

```
watch: {
    items (nv) {
      const vm = this

      this.$nextTick(()=>{
        vm.selected = [nv[0]]
      })
    }
}
```

Now, I'm pretty sure this is caused because of a race condition where the first element may be already rendered when I set the value of the selected row and thus the inside checkbox is not aware of the new value... And I don't think it's the VDataTable component's job to figure that out or wait for the tick before passing down the value, maybe this should be addressed by Vue.js itself or perhaps the before mentioned workaround is the best solution we can get?

**Comment by arielnmz** [comment]
Take a look at this Pen

https://codepen.io/arielnmz/pen/xxxBozV?editors=1010

**Comment by KaelWD** [comment]
`<v-switch :input-value="isSelected">`
