### ISSUE TITLE
[Documentation] Vuetify i18n documentation only describes vue-i18n `$t`

### ISSUE THREAD

**Issue by wouterkroes** [vuetifyjs/vuetify#9749]
### Problem to solve
The current [internationalization (i18n) documentation](https://vuetifyjs.com/en/customization/internationalization#internationalization-i-18-n) only describes integrating vue-i18n feature `$t`. But how can I use other vue-i18n features as [number-localization](https://kazupon.github.io/vue-i18n/guide/number.html#number-localization) or [$te](https://kazupon.github.io/vue-i18n/api/#te)?

I had a quick look at the [Vuetify codebase](https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src) and I could not find any code supporting these features of vue-i18n?

### Proposed solution
Update the documentation [internationalization (i18n) documentation](https://vuetifyjs.com/en/customization/internationalization#internationalization-i-18-n) about how to implement more features of vue-i18n

**Comment by MajesticPotatoe** [comment]
The docs state that "hook up vue-i18n to Vuetify by supplying a custom translation function (as seen in the example below)"
The portion i believe this is referring to is:
```js
export default new Vuetify({
  lang: {
    t: (key, ...params) => i18n.t(key, params),
  }
})
```
so to add `te` for example would be to add `te: (key, locale) => i18n.te(key, locale)` to the lang object
Would probably be beneficial to mention this or break this out into its own snippet for clarification

**Comment by KaelWD** [comment]
That's for customising the language strings used by our components if you want to store them in vue-i18n instead of a separate service. Exposing anything else like $te on $vuetify is pointless, just use it directly. 

> so to add `te` for example would be to add `te: (key, locale) => i18n.te(key, locale)` to the lang object

That does nothing, we only use `t`

**Comment by wouterkroes** [comment]
Ok, clear answer and thanks for the replies!
