### ISSUE TITLE
[Documentation] different hash id generation in content and TOC

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetify#9751]
### Reproduction Link
https://vuetifyjs.com/en/getting-started/browser-support

"IE11 & Safari 9 support" title id is `ie-11-amp-safari-9-support`

![image](https://user-images.githubusercontent.com/15625235/69324438-0acded80-0c7b-11ea-8790-5bbca9395851.png)

but in TOC it's `ie-11-safari-9-support`

![image](https://user-images.githubusercontent.com/15625235/69324425-01dd1c00-0c7b-11ea-903e-39d100d9cf17.png)

**Comment by MajesticPotatoe** [comment]
guessing it doesn't like the ampersands 🐙
