### ISSUE TITLE
[Bug Report] <v-textarea> dense option only affect label position when outlined

### ISSUE THREAD

**Issue by rsaleri** [vuetifyjs/vuetify#9755]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
The "dense" attribute affect only the label position when focused and not the overall textarea dimension, the reproduction link is pretty self explanatory

### Expected Behavior
The "dense" parameter should "dense up" the textarea as well

### Actual Behavior
The "dense" parameter only affect the label, which expects to find a much more "dense" environment

### Reproduction Link
<a href="https://codepen.io/rsaleri/pen/abbMRoK" target="_blank">https://codepen.io/rsaleri/pen/abbMRoK</a>

**Comment by rehdie** [comment]
As a workaround you might use the following css-rule (at least worked for me):

.v-textarea.v-input--dense.v-text-field--outlined .v-label {
	top: 10px !important;
}

**Comment by johnleider** [comment]
v2.2.3:
![image](https://user-images.githubusercontent.com/9064066/72488777-99706e00-37d7-11ea-8d44-3c59e4752620.png)

v2.2.4:
![image](https://user-images.githubusercontent.com/9064066/72488789-a1301280-37d7-11ea-9e1f-ddcc42e2b68d.png)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
