### ISSUE TITLE
[Bug Report] No margin between buttons with tooltip in v-card-actions

### ISSUE THREAD

**Issue by Josef-Reichardt** [vuetifyjs/vuetify#9756]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Linux

### Steps to reproduce
Within a `v-card-actions` insert for example two buttons and wrap the second on in a `v-tooltip`.

### Expected Behavior
The buttons (and the margin between them) should look identical and doesn't matter they have a tooltip or not.

### Actual Behavior
There is no spacing between the buttons if the second one is wrapped by a `v-tooltip`.

### Reproduction Link
<a href="https://codepen.io/CptS/pen/Jjjzwby" target="_blank">https://codepen.io/CptS/pen/Jjjzwby</a>

### Other comments
In the css editor in the linked codepen you can find a commented solution suggestion. Maybe the correct place would be near to https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VCard/VCard.sass#L96.

**Comment by jacekkarczmarczyk** [comment]
Related https://github.com/vuetifyjs/vuetify/issues/6951, although hiding this extra element won't help in this case. It happens also when button as dialog/menu's activator

**Comment by Isitar** [comment]
any fix for this issue?

**Comment by howar31** [comment]
any fix?
