### ISSUE TITLE
[Bug Report] VAutocomplete ignore initial value of search-input prop

### ISSUE THREAD

**Issue by esynaps** [vuetifyjs/vuetify#9757]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Create a VAutocomplete with a property initialized with a value

### Expected Behavior
The field should contain the initial search value

### Actual Behavior
The field is empty

### Reproduction Link
<a href="https://codepen.io/Alex83690/pen/Yzzggzq" target="_blank">https://codepen.io/Alex83690/pen/Yzzggzq</a>

### Other comments
If you set the search value after a delay, it works

**Comment by transfluxus** [comment]
well ok it works when I set the items and v-model at the same time. But this is kindof a workaround for, since I dont use v-model in my real application and also the items are initially not set neither

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
