### ISSUE TITLE
[Bug Report] Combobox shows value which is not exist in items array

### ISSUE THREAD

**Issue by skortabeast** [vuetifyjs/vuetify#9758]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
input value which not exist in items

### Expected Behavior
show only values which are present in items

### Actual Behavior
shows added value which does not exist in items

### Reproduction Link
<a href="https://codepen.io/skortabeast/pen/wvvZGRJ?&editable=true&editors=101" target="_blank">https://codepen.io/skortabeast/pen/wvvZGRJ?&editable=true&editors=101</a>

**Comment by jacekkarczmarczyk** [comment]
use `v-autocomplete` if you want only values from items

**Comment by skortabeast** [comment]
@jacekkarczmarczyk v-autocomplete clears selected values ​​if items was realoading
