### ISSUE TITLE
[Bug Report] [Bug Report] Making boxes readonly will not prevent deleting if clearable is true

### ISSUE THREAD

**Issue by mrksoftware** [vuetifyjs/vuetify#9760]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Add readonly and clearable props

### Expected Behavior
Selected value is not deleted when pressing on the X (clearable)

### Actual Behavior
The selected value is deleted.

### Reproduction Link
<a href="https://codepen.io/mrksoftware/pen/oNNOzoE" target="_blank">https://codepen.io/mrksoftware/pen/oNNOzoE</a>

**Comment by mrksoftware** [comment]
Related to #8867

**Comment by KaelWD** [comment]
Duplicate of #7111
