### ISSUE TITLE
[Bug Report] v-date-picker displays the wrong week number when first-day-of-week="1"

### ISSUE THREAD

**Issue by knekki** [vuetifyjs/vuetify#9764]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Using v-date-picker with the following attr: `show-week` and `first-day-of-week="1"`

Set the date to e.g. `2017-08-17`, the week number is displayed is `34`. Expected: `33`.

![v-date-picker week number bug](https://i.imgur.com/6Vc4Ntv.png)

### Expected Behavior
Week number `33` displayed for the selected date `2017-08-17`

### Actual Behavior
Week number `34` is displayed for the selected date `2017-08-17`

### Reproduction Link
<a href="https://codepen.io/knekk/pen/oNNOZMd" target="_blank">https://codepen.io/knekk/pen/oNNOZMd</a>

### Other comments
It seems like the bug is only occuring for certain years e.g. `2017`

**Comment by jacekkarczmarczyk** [comment]
Weeks are shifted because they start from another day? See January

![image](https://user-images.githubusercontent.com/15625235/69425949-8a80b880-0d5e-11ea-84ab-fb06bb41c375.png)

**Comment by knekki** [comment]
That looks like the case. January 1st should have been connected to week number 52 (previous year)?:

Example from google calendar: 
![January 2017 - Google Calendar](https://user-images.githubusercontent.com/10436866/69426088-a10e1c00-0d2c-11ea-953b-58e2cae31da3.png)

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/69426182-388c6280-0d5f-11ea-897b-20640247aa3a.png)

**Comment by KaelWD** [comment]
Also the year has 53 weeks in both
![image](https://user-images.githubusercontent.com/16421948/69427208-320fe200-0d83-11ea-9224-89810cca1742.png)

**Comment by lxr900** [comment]
IMHO week number should follow the ISO standard:
> The ISO 8601 definition for week 01 is the week with the first Thursday of the Gregorian year (i.e. of January) in it. 
More info on [wikipedia](https://en.wikipedia.org/wiki/ISO_week_date#First_week):

**Comment by abbierwolf** [comment]
> IMHO week number should follow the ISO standard:
> 
> > The ISO 8601 definition for week 01 is the week with the first Thursday of the Gregorian year (i.e. of January) in it.
> 
> More info on [wikipedia](https://en.wikipedia.org/wiki/ISO_week_date#First_week)

Did you look at the code of the pull request?
