### ISSUE TITLE
[Bug Report] v-color-picker - canvas - dot is not draggable on android devices

### ISSUE THREAD

**Issue by manuel3108** [vuetifyjs/vuetify#9765]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Android

### Steps to reproduce
Open the reproduction Link on a mobile device (I tested Android 9, Chrome and Firefox for mobile), and try to drag the dot in the color canvas (the big field withe the color gradients) around.

### Expected Behavior
You can drag the dot with your finger or a pen the way you are able to on desktop (I tested Chrome 78 on Linux)

### Actual Behavior
Dragging is not working.
If you just click the color you want, it works.

### Reproduction Link
<a href="https://codepen.io/manuel3108/pen/yLLrXbQ" target="_blank">https://codepen.io/manuel3108/pen/yLLrXbQ</a>

**Comment by MajesticPotatoe** [comment]
Seems to be working fine on Chrome 78.0.3904.96 and 78.0.3904.108
Android 9 - Galaxy S10

**Comment by MajesticPotatoe** [comment]
Nevermind that, thought you meant sliders.

**Comment by manuel3108** [comment]
Yes, that was not exactly. Updated the issue.
I can not test it, but I think this will also be an issue on IOS. Do you want me to add this to the issue?

**Comment by nekosaur** [comment]
Without checking the code I'm guessing we haven't hooked up touch events

**Comment by mikeacre** [comment]
Is anyone working on adding this feature? Would be a nice addition. If not I can try to take a stab at it.

**Comment by amirking59** [comment]
i fix the problem simply by listening to touch events.
i changed VColorPickerCanvas.js in node_modules 
how can i submit this changes ?
PR or write it here ?

**Comment by manuel3108** [comment]
PR would be easier for everyone i guess
