### ISSUE TITLE
Data table 'rows per page' menu items cut off by scroll bar

### ISSUE THREAD

**Issue by ptrbrynt** [vuetifyjs/vuetify#977]
### Steps to reproduce
Implement any data table with actions not hidden.

### Versions
Tested on macOS 10.12.5 in Safari 10.1.1, Vue 2.4.1, Vuetify 0.13

### What is expected ?
Expect to see a drop-down with fully visible items, not obscured or clipped by a scroll bar.

### What is actually happening
The drop-down contains the correct items, but they are being cut off by the scroll bar. It also does a weird animation on first open where it appears from the left-side of the screen and moves over to the correct position.
<img width="98" alt="28134708-ae1b1388-673b-11e7-8c21-70023aff164a" src="https://user-images.githubusercontent.com/24222738/28156259-edc37c96-67a9-11e7-96d0-c9d1809ab928.png">

### Reproduction Link
https://codepen.io/anon/pen/MoLmVN

**Comment by coldoutside** [comment]
I have the same behavior on:
-Firefox and Waterfox 54 (Mac OS Sierra and Windows 10)
-Safari 10.1.1 (Mac OS Sierra)

Display correctly on:
Chrome 59 (Mac OS Sierra and Windows 10)
Opera 46 (Mac OS Sierra)
