### ISSUE TITLE
[Bug Report] v-tab-item 'disabled' prop is not working

### ISSUE THREAD

**Issue by tostangs** [vuetifyjs/vuetify#9770]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.6

### Steps to reproduce
Set the 'disabled' property to false within a v-tab-item component and try to navigate to it.

### Expected Behavior
The user would be unable to click and/or navigate to the tab.

### Actual Behavior
The user is able to click and navigate to whichever tab irrelevant of the disabled property

### Reproduction Link
<a href="https://codepen.io/tostangs/pen/dyyLKEb" target="_blank">https://codepen.io/tostangs/pen/dyyLKEb</a>

**Comment by jacekkarczmarczyk** [comment]
Use `disabled` on `v-tab`
`disabled` is mentioned in `v-tab-item` props in docs, looks like a docs issue, or `disabled` prop shouldn't be in VWindowItem

**Comment by KaelWD** [comment]
You need it on both, they don't talk to each other. `v-tab` to prevent clicking and `v-tab-item` to prevent swiping.

**Comment by jacekkarczmarczyk** [comment]
Ah right, forgot about swiping
