### ISSUE TITLE
[Bug Report] Header not showing when updating data v-autocomplete

### ISSUE THREAD

**Issue by maikenmadsen1992** [vuetifyjs/vuetify#9772]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Mac OS 10.14.5

### Steps to reproduce
When the user starts typing in the input the Group 1 and Group 2 headers from the array disapear in the list

### Expected Behavior
The Group 1 and Group 2 needs to be shown all the time

### Actual Behavior
It shows the rest if the array 

### Reproduction Link
<a href="https://codepen.io/maikenmadsen92/pen/KKKYBNe?editors=1010" target="_blank">https://codepen.io/maikenmadsen92/pen/KKKYBNe?editors=1010</a>

### Other comments
The code snippet in the codepen is from the documentation about slots in v-autocomplete

**Comment by jacekkarczmarczyk** [comment]
Duplicate  of https://github.com/vuetifyjs/vuetify/issues/7424
