### ISSUE TITLE
[Bug Report] Container with fill-height makes row smaller than it should

### ISSUE THREAD

**Issue by mrodal** [vuetifyjs/vuetify#9773]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Windows 10

### Steps to reproduce
Set a container with fill-height
Add a row

### Expected Behavior
row is centered on container

### Actual Behavior
Row is not centered

### Reproduction Link
Here you can see that theres more space to the right of the row than to the left:
<a href="https://codepen.io/mrodal/pen/GRRLBvm" target="_blank">https://codepen.io/mrodal/pen/GRRLBvm</a>

### Other comments
What I could find is that this style looks like the culprit

```
.container.fill-height>.row {
    max-width: 100%;
}
```
When taken away, the issue is fixed.. I dont know if removing it breaks something else

**Comment by rodrigoterminus** [comment]
I can confirm the issue. I spent a long time after updating Vuetify trying to find out what I was doing wrong. 😅

It seems that the issue was somehow introduced by [#9731](https://github.com/vuetifyjs/vuetify/issues/9731).

**Comment by piotrek-szczygiel** [comment]
Use `style="max-width: initial"` as a temporary fix.

**Comment by arminmon** [comment]
> Use `style="max-width: initial"` as a temporary fix.

Did the trick. Thanks.

**Comment by lampewebdev** [comment]
Thanks `style="max-width: initial"` worked als for me!

I hope there will be a fix soon for this.

This bug even breaks the official `pre-made layouts`.

**Comment by janmichek** [comment]
For me worked this temporary solution

```
  .container.fill-height > .row {
    max-width: initial;
    width: 100%;
  }
```

**Comment by simonmaass** [comment]
this isnt fixed!
