### ISSUE TITLE
[Bug Report] The separator climbs beyond the borders of the button

### ISSUE THREAD

**Issue by Alexandr-Belchev** [vuetifyjs/vuetify#9776]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 7

### Steps to reproduce
1) Select "Segmented" option.
2) Select "Dense" option.
3) Press the button. Аnd you will see that the separator climbs beyond the borders of the button - http://joxi.ru/zANNdGZivQPz6A

### Expected Behavior
The separator should not creep out the edges of the button

### Actual Behavior
The separator climbs beyond the borders of the button

### Reproduction Link
<a href="https://codepen.io/sasha-belchew/pen/yLLWBBa" target="_blank">https://codepen.io/sasha-belchew/pen/yLLWBBa</a>

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
