### ISSUE TITLE
[Bug Report] Long event names in v-calendar

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#9786]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
1. Open the link
2. Check the event with `start: "2018-12-31"`
3. The event name is longer than the width of a day tile and gets cut off

### Expected Behavior
If the event spans across multiple day tiles, use all available space to display the event name.

### Actual Behavior
Event name gets cut off

### Reproduction Link
<a href="https://codepen.io/auspex/pen/wvvbNow?&editable=true&editors=101" target="_blank">https://codepen.io/auspex/pen/wvvbNow?&editable=true&editors=101</a>

![image](https://user-images.githubusercontent.com/2115696/69558527-639ccf00-0f76-11ea-8c01-c63dc17066b1.png)

**Comment by ClickerMonkey** [comment]
Resolved in #9974
