### ISSUE TITLE
[Bug Report] !important is being used

### ISSUE THREAD

**Issue by jpbamberg1993** [vuetifyjs/vuetify#9793]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 71.0
**OS:** Mac OS 10.15

### Steps to reproduce
If you put a class of .success on an element it applies these styles.
.v-application .success {
    background-color: #4caf50 !important;
    border-color: #4caf50 !important;
}

### Expected Behavior
Should not have !important anywhere.

### Actual Behavior
Has !important.

### Reproduction Link
<a href="https://codepen.io/" target="_blank">https://codepen.io/</a>

### Other comments
I'm using "@nuxtjs/vuetify": "^1.9.0"

**Comment by OuyangZq** [comment]
poor english！

You need to check your code！To confirm introduce your css file after vuetify's style file。

But，you should not directly overwrite vuetify's style files!

Vuetify has a theme style editor that allows you to change the style of the preset keywords ('primary', 'success', 'error', etc) at any time, see this [link](https://next.vuetifyjs.com/en/customization/theme#customizing)

Or sometimes you can use:
```javascript
this.$vuetify.theme.themes.dark.success= '#4caf50'
// or this.$vuetify.theme.themes.light.success= '#4caf50'
```

**Comment by jpbamberg1993** [comment]
I am, it doesn't matter if you are using `!important`
The idea that I shouldn't overwrite vuetify's styles is crazy
It's a pretty fundamental practice that you not use `!important`

**Comment by KaelWD** [comment]
Easier said than done. If you think you have a way to do this without it feel free to open a PR.
