### ISSUE TITLE
[Bug Report] v-calendar wrong height if event-more="false"

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/vuetify#9796]
### Environment
**Vuetify Version:** 2.1.11
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Windows 10

### Steps to reproduce
1. Add several events for the same date
2. Disable the `more` functionality of the calendar
3. See the day overflowing

### Expected Behavior
The day should automatically adjust its height to fit all of its content in case `:event-more="false"`.

### Actual Behavior
Events spill into other days and become unclickable.

### Reproduction Link
<a href="https://codepen.io/auspex/pen/gOONaNR?&editable=true&editors=101" target="_blank">https://codepen.io/auspex/pen/gOONaNR?&editable=true&editors=101</a>

![image](https://user-images.githubusercontent.com/2115696/69603318-3be64f00-0fe8-11ea-97f0-8611e2f656eb.png)

**Comment by pumpknhd** [comment]
Workaround, add the following CSS:

.v-calendar-weekly {
    display: table;
    table-layout: fixed;
  }
  .v-calendar-weekly__week {
    height: auto;
    display: table-row;
  }
  .v-calendar-weekly__day {
    display: table-cell;
    width: calc(100% / 7)
  }

https://codepen.io/pumpknhd/pen/JjYjxRz?editors=0100

**Comment by youngmd** [comment]
This workaround breaks the day of week labels (places them all in the first column).  Add the following CSS to fix those as well:

```
.v-calendar-weekly__head {
    height: auto;
    display: table-row;
}

.v-calendar-weekly__head-weekday {
    display: table-cell;
    width: calc(100% / 7)
}
```

**Comment by MartinX3** [comment]
Sadly the workaround creates another issue
![image](https://user-images.githubusercontent.com/4518092/181266526-710692c1-8216-4971-bc70-75e7c24a0f2b.png)

**Comment by iguilhermeluis** [comment]
Fixed by using

```
.v-calendar-weekly__day {
  overflow-y: auto;
}
```
