### ISSUE TITLE
[Bug Report] VToolbar not supported non pixel value

### ISSUE THREAD

**Issue by Marco3jp** [vuetifyjs/vuetify#9799]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Linux x86_64

### Steps to reproduce
Set non pixel value(%, vh) to v-toolbar height.

### Expected Behavior
Non pixel value are interpreted as css value.(like [measurableStyles](https://github.com/vuetifyjs/vuetify/blob/v2.1.11/packages/vuetify/src/mixins/measurable/index.ts#L26))

### Actual Behavior
Non pixel values are interpreted as pixels only in numbers. (ex. "50%" -> 50 -> "50px", "10vh" -> 10 -> "10px")

### Reproduction Link
<a href="https://codepen.io/marco3jp/pen/vYYqKrL" target="_blank">https://codepen.io/marco3jp/pen/vYYqKrL</a>

### Other comments
I read v-toolbar code. It seems that only numbers are parsed by [this parseInt](https://github.com/vuetifyjs/vuetify/blob/v2.1.11/packages/vuetify/src/components/VToolbar/VToolbar.ts#L67).
If this behavior was specification, i'm sorry.

**Comment by johnleider** [comment]
At this point in time, it is the intended functionality of the measurable mixin.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
