### ISSUE TITLE
Rectangular touch effect on rounded buttons in Android Chrome

### ISSUE THREAD

**Issue by abastardi** [vuetifyjs/vuetify#98]
In Chrome on Android, touching a rounded button results in a rectangular area around the button being highlighted, as shown in the animated GIF below:

![vuetify_buttons](https://cloud.githubusercontent.com/assets/1295688/22069164/72bc1216-dd65-11e6-84b4-df1d8ca0c83f.gif)

**Comment by yoyo930021** [comment]
I go to Google.
get this answear
`-webkit-tap-highlight-color: rgba(255, 255, 255, 0);`

**Comment by johnleider** [comment]
This has been fixed for the upcoming patch.
