### ISSUE TITLE
[Bug Report] Incorrect rendering position of active VTextField label inside VMenu/VDialog activator slot when using prepend-inner-icon

### ISSUE THREAD

**Issue by haggys22** [vuetifyjs/vuetify#9801]
### Environment
**Vuetify Version:** 2.1.11
**Last working version:** 2.0.20
**Vue Version:** 2.6.10
**Browsers:** Vivaldi 2.9.1705.31, Mozilla Firefox
**OS:** Linux x86_64

### Steps to reproduce
1. Follow reproduction link
2. Click inside the 1st "Breaks" text field (already breaks)
3. Click "Cancel" in VDatePicker
4. Click inside 2nd "Breaks" text field
5. Select a date (breaks again)
6. "Save" (stays broken)

### Expected Behavior
The active label should be rendered inside the outline gap

### Actual Behavior
The label is shifted to the right, overlapping the outline

### Reproduction Link
<a href="https://jsfiddle.net/wq27nv9t/" target="_blank">https://jsfiddle.net/wq27nv9t/</a>

### Other comments
As seen in the 3rd VCard ("Works"), a standalone VTextField is not affected by this bug

**Comment by johnleider** [comment]
This no longer occurs as of v2.2.3.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
