### ISSUE TITLE
[Bug Report] v-select / v-autocomplete cannot read property trim of undefined

### ISSUE THREAD

**Issue by jappyjan** [vuetifyjs/vuetify#9803]
### Environment
**Vuetify Version:** 2.1.7
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.15.1

### Steps to reproduce
- create v-autocomplete
- try to select an item

### Expected Behavior
- should work without errors

### Actual Behavior
works but throws errors

### Reproduction Link
<a href="https://jsfiddle.com" target="_blank">https://jsfiddle.com</a>

### Other comments
[Vue warn]: Error in render: "TypeError: Cannot read property 'trim' of undefined"

found in

---> <VIcon> at src/components/AnimatedRouterView.vue
       <VListItem> at src/components/AnimatedRouterView.vue
         <VList> at src/components/AnimatedRouterView.vue
           <VSelectList> at src/components/AnimatedRouterView.vue
             <ThemeProvider> at src/components/AnimatedRouterView.vue
               <VMenu> at src/components/AnimatedRouterView.vue
                 <VAutocomplete> at src/components/AnimatedRouterView.vue
                   <VCard> at src/components/AnimatedRouterView.vue
                     <TaskTable> at src/views/Projects/Tasks/TaskListViews/TaskTable.vue
                       <ProjectDetails> at src/views/Projects/ProjectDetails.vue
                         <AnimatedRouterView> at src/components/AnimatedRouterView.vue
                           <VContent> at src/components/AnimatedRouterView.vue
                             <VApp> at src/components/AnimatedRouterView.vue
                               <App> at src/App.vue
                                 <Root>

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a valid reproduction. In order to effectively. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by jappyjan** [comment]
I'm sorry it's kinda hard to create a reproduction link because i use a webpack build environment and it seems to only happen in this environment... but might also be because of me using the material icons instead of material design icons font.

the error disappears as soon as i provide custom markup for the "item" slot. seems like the default slot tries to load an icon (propably the checkbox icon) and fails somewhere while doing so...

i really hope you investigate this problem even without a reproduction link.

the only thing i can provide by the moment would be a copy of the component file where i get the error...

**Comment by jacekkarczmarczyk** [comment]
We accept github repos as well, but make sure it's boiled down to minimal
