### ISSUE TITLE
[Feature Request] use vuetify in more "classic" way

### ISSUE THREAD

**Issue by EwaMakowska** [vuetifyjs/vuetify#9807]
### Problem to solve
I think vuetify are the most beautifull frontend components, but I really don't like new way of use it. I don't understand why I need to create plugin file for vuetify or use vue-style-loader. I really need it? I think it would complicate my code more complicated. Maybe I can use it in more "classic" way? like that:

`
t emplate>
   d iv>
       v-al ert type="success" />
   </d iv>
</t emplate>

<script>
    import alert from 'good path, but I don't know it';
    export default { ... } 
</script>
`

### Proposed solution
examples, how to use it in more "classic" way

**Comment by KaelWD** [comment]
> I don't understand why I need to create plugin file for vuetify or use vue-style-loader.

You don't. https://vuetifyjs.com/en/getting-started/quick-start#cdn-usage

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by jacekkarczmarczyk** [comment]
You don't need to create a plugin file in non-cdn mode as well:

```js
// main.js

import Vuetify from 'vuetify/lib';

new Vue({
  vuetify: new Vuetify(),
  ...
});
```

and in your .vue file: 
```
// Foo.vue

<script>
import { VList } from 'vuetify/lib';

export default {
  components: { VList },
}
</script>
```

Although this doesn't make sense since there's a vuetify-loader which imports vuetify components automatically
