### ISSUE TITLE
[Bug Report] Text field label overlays with outlined border in datepicker menu

### ISSUE THREAD

**Issue by demonye** [vuetifyjs/vuetify#9810]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.13.6

### Steps to reproduce
1. create a datapicker menu with an outlined text field
2. set a label and initial date value
3. the label overlays with the text field border

### Expected Behavior
The text field label displays between the text field border

### Actual Behavior
The label overlays with the text field border

### Reproduction Link
<a href="https://codepen.io/demonye/pen/ExxBqWY" target="_blank">https://codepen.io/demonye/pen/ExxBqWY</a>

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetify/issues/9413
https://github.com/vuetifyjs/vuetify/issues/9225
