### ISSUE TITLE
[Bug Report] Change event is broken in v-text-field, if one tries to update the value in it

### ISSUE THREAD

**Issue by archeg** [vuetifyjs/vuetify#9811]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
See codepen. Try to enter `bcd` into vueitifyjs text field. 

### Expected Behavior
Text field should maintain the string `a` in it, no matter what user is trying to enter.

### Actual Behavior
The text in the field is changed to `acd`, although the model is still `a`. After this any text can be entered in the text field without any changes to the model or to the representation in the text field.

### Reproduction Link
<a href="https://codepen.io/archegg/pen/RwwXbpB?&editable=true&editors=101" target="_blank">https://codepen.io/archegg/pen/RwwXbpB?&editable=true&editors=101</a>

### Other comments
Compare this behavior to the behavior of original `input` (same codepen, styled with grey color). Everything works there.

I needed this to apply special mask to my text field. The `v-mask`, as described in the documentation, using  `vue-the-mask` is not sufficient to me, as I want more control of the masking.

**Comment by johnleider** [comment]
You have to wait for the updated value to persist before you attempt to change it: https://codepen.io/johnjleider/pen/NWPYmjp?editable=true&editors=101

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
