### ISSUE TITLE
[Bug Report] Prefix overlaps with label in VTextField used as VMenu activator.

### ISSUE THREAD

**Issue by EPillin** [vuetifyjs/vuetify#9812]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.87
**OS:** Linux x86_64

### Steps to reproduce
Follow the reproduction link, which consists of a copy of [an example in the documentation](https://vuetifyjs.com/en/components/time-pickers#in-dialog-and-menu), but with a prefix added to both VTextFields.

### Expected Behavior
The VTextField's label displays next to its prefix.

### Actual Behavior
The VTextField's label and prefix overlap.

### Reproduction Link
<a href="https://codepen.io/epillin/pen/YzzmwrN" target="_blank">https://codepen.io/epillin/pen/YzzmwrN</a>

### Other comments
Upon inspection, this seems to be caused by the VTextField's `prefixWidth` property, which is erroneously set to 0 upon the component being mounted in this case. I don't know what the root cause is, but replacing `this.setPrefixWidth()` by `this.$nextTick(this.setPrefixWidth)` in the `mounted` function seemed to fix this issue.

**Comment by jacekkarczmarczyk** [comment]
This no longer occurs as of v2.2.3.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
