### ISSUE TITLE
[Feature Request] We should have color schema for the vuetify with number to align the Material Design color pattern

### ISSUE THREAD

**Issue by dotku** [vuetifyjs/vuetify#9814]
### Problem to solve
for example, we have color.red.500 from material design instead of using Vuetify darken-1; basically, darken-1 doesn't means it is good for light colors font. eg `yellow darken-1`

### Proposed solution
We should just use material design numbers

**Comment by KaelWD** [comment]
This was based on [materialize](https://materializecss.com/color.html) and would not be worth changing now. 

> basically, darken-1 doesn't means it is good for light colors

That doesn't make sense, it's exactly the same as yellow 600.

**Comment by dotku** [comment]
@KaelWD  darken means it should be light/white text; but official doc is using dark text instead light/white text color.

**Comment by KaelWD** [comment]
#4921

**Comment by dotku** [comment]
@KaelWD Exactly, that's why I recommend follow the Material Design color design with number instead of words (and also the words are not exactly correct)
