### ISSUE TITLE
disable individual v-select items

### ISSUE THREAD

**Issue by jhudzik** [vuetifyjs/vuetify#982]
Any issue created without this markup will be immediately closed

Have a feature request?
=======================
- Allow us to disable individual items in `<v-select>`, similar to how `<option disabled>` would work with a `<select>` element. Exposing a property `item-disable` or something of this nature on `<v-select>` 
`props: { itemDisable: [String, Function] `}, where we could pass a key or supply a custom function to make the determination.

- I currently don't have a work around as of yet, but will be looking into the `item` slot to see what I can come up with.

-  Doesn't help to avoid bugs, would just be a useful feature.

**Comment by johnleider** [comment]
Ooh I like this!
