### ISSUE TITLE
[Feature Request] Create option to set custom classes on VDataDable rows

### ISSUE THREAD

**Issue by guilhermemj** [vuetifyjs/vuetify#9822]
### Problem to solve
AFAIK, the only way to set custom classes on VDataTable rows is by using the `item` and `body` slots.

They come with the drawback of losing some of the component's functionalities (e.g `item.<name>` slots, mobile display, etc) and create lots of unnecessary boilerplate. 

Here is an example of how to solve this issue (custom row classes) in userland: https://codepen.io/guilhermemj/pen/abbeXML

### Proposed solution
Allow users to inform a function that receives current item's data and returns a string that will be used as the default `<tr>` class.

The example showed above could be rewritten as a simple `:item-classes="item => (item.calories > 500 ? 'error' : '')"` option.

This concept may even be expanded to allow users to return an object that will be bound to the `<tr>` element:

``` html
<v-data-table
  :item-attrs="item => ({
    class: item.calories > 500 ? 'error' : '',
    lang: item.lang,
    dir: item.dir,
    dataItemId: item.id,
  })"
/>
```

**Comment by shadowlik** [comment]
It would be really nice to be able to customize the tr tag out-side-the-box!

**Comment by alvaro-canepa** [comment]
Or maybe inject tr `class` automatically if item has `class` property. Or a custom property, like is used in `v-autocomplete` for `value` and `text`.

**Comment by jacekkarczmarczyk** [comment]
@alvaro-canepa That won't allow you to add class to the table (or table wrapper)

I've seen in other framework (don't remember which one atm) prop for passing node data, so not only attributes but also event handlers etc., so like extended version of @guilhermemj 's proposal

I think for table row attributes and events would be enough, for table cell we would need also tag or boolean `header` attr (to be able to change it from `<td>` to `<th>`)

That issue raises the same problem as https://github.com/vuetifyjs/vuetify/issues/8643 so I'm closing it as a duplicate, discussion can be continued there
