### ISSUE TITLE
[Bug Report] Label and prefix overlap in filled VTextField

### ISSUE THREAD

**Issue by frandiox** [vuetifyjs/vuetify#9826]
### Environment
**Vuetify Version:** 2.1.12
**Last working version:** 1.5.21
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.15.0

### Steps to reproduce
Create a VTextField with `filled`, `label` and `prefix` props.

### Expected Behavior
The label doesn't overlap the prefix and is aligned with it when input is empty.

### Actual Behavior
The label randomly overlaps the prefix. If not, then the label is not aligned with the prefix.

### Reproduction Link
<a href="https://codepen.io/frandiox/pen/yLLmdJg" target="_blank">https://codepen.io/frandiox/pen/yLLmdJg</a>

### Comments:

![image](https://user-images.githubusercontent.com/1634092/69845831-5e60bc80-12b5-11ea-8337-0e170f26e853.png)

![image](https://user-images.githubusercontent.com/1634092/69845857-720c2300-12b5-11ea-9727-318dcb1b37c0.png)

**Comment by Prophe1** [comment]
Can this be fixed?

**Comment by johnleider** [comment]
Will be resolved as part of #7872 and as such am closing this in favor of it.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
