### ISSUE TITLE
[Bug Report] Modal lose focus (for body) after an inner button is clicked

### ISSUE THREAD

**Issue by Thibaud-R** [vuetifyjs/vuetify#9830]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3762.0
**OS:** Windows 7

### Steps to reproduce
When the dialog is open, keyboard shortcut "Enter" should close it.
If the button (2) is clicked, the shortcut doesn't work anymore, unless you click inside the dialog, so that the activeElement is set to a component of the dialog.

### Expected Behavior
Whatever component of the dialog, here the button (2) of the dialog is used, it should not transfer the focus to the body (keep the focus or transfer it to the modal ).

### Actual Behavior
After clicking on the button (2) the document.activeElement became the page body (and the keydown shortcut doesn't work).

### Reproduction Link
<a href="https://codepen.io/thibaud-r/pen/ZEYzWrb?editors=1010" target="_blank">https://codepen.io/thibaud-r/pen/ZEYzWrb?editors=1010</a>

### Other comments
Using the debug view of the codepen (https://cdpn.io/thibaud-r/debug/ZEYzWrb/LDkmdEnJZpNA) you could see that the document.activeElement, change from the dialog to the body after click on button (2).

When activating an input (like a v-text-field), I don't think the focus is set to the body.

**Comment by johnleider** [comment]
You need to use the **retain-focus-on-click** property of `v-btn`: https://codepen.io/johnjleider/pen/VwYdaMa?editors=1010

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
