### ISSUE TITLE
[Bug Report] Vuetify Page not showing in IE11 

### ISSUE THREAD

**Issue by sangilIm** [vuetifyjs/vuetify#9833]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108, Internet Explorer
**OS:** Windows 10

### Steps to reproduce
input below URL in explorer 11 Browser

https://sangilim.github.io/vue-page-test/

### Expected Behavior
show display like chrome browser same output

### Actual Behavior
IE11 not showing anythings

### Reproduction Link
<a href="https://github.com/sangilIm/vue-page-test" target="_blank">https://github.com/sangilIm/vue-page-test</a>

### Other comments
node -v : 12.13.1
npm -v : 6.12.1
vue -v : @vue/cli 4.1.1

when i create vue cli project 
i had checked "Use babel/polyfill" option "Y"

Before I typed the "vue add vuetify" command, the screen in IE worked fine. But when I add vuetify library, it does not print

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/getting-started/browser-support#ie-11-amp-safari-9-support

You're missing `transpileDependencies` in vue.config.js

**Comment by sangilIm** [comment]
> https://vuetifyjs.com/en/getting-started/browser-support#ie-11-amp-safari-9-support
> 
> You're missing `transpileDependencies` in vue.config.js


thank you sir 
We solved problem as follows ^^

// vue.config.js
module.exports = {
    publicPath:'/dist/',
    transpileDependencies: ['vuetify']
}
