### ISSUE TITLE
[Bug Report] VSwitch rtl support

### ISSUE THREAD

**Issue by 01101101M** [vuetifyjs/vuetify#9835]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Linux x86_64

### Steps to reproduce
use right-to-left direction

### Expected Behavior
support rtl

### Actual Behavior
support rtl

### Reproduction Link
<a href="https://codepen.io/01101101m/pen/BayBEyz" target="_blank">https://codepen.io/01101101m/pen/BayBEyz</a>

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/zYxOXBm
