### ISSUE TITLE
[Bug Report] Vuetify Issue Creator is not working correctly

### ISSUE THREAD

**Issue by munierujp** [vuetifyjs/vuetify#9839]
Body which is created by Vuetify Issue Creator has replaced by repository's `ISSUE_TEMPLATE.md` 😢

![画面収録 2019-12-02 2 14 38 mov](https://user-images.githubusercontent.com/20086673/69917496-0939cc00-14aa-11ea-8e83-5b481e791499.gif)

**Comment by munierujp** [comment]
😢

**Comment by sugoidesune** [comment]
The issue creator is sending me to tot he Github Email settings, without creating the issue.
