### ISSUE TITLE
[Bug Report] Spacing helper classes with xs-breakpoint not applying

### ISSUE THREAD

**Issue by T3nak** [vuetifyjs/vuetify#9841]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
1. Create any element.
2. Add any of the spacing helper classes with the xs-breakpoint (e.g. `class="my-xs-12"`).
3. Notice that the spacing is not applied.

### Expected Behavior
The spacing should be applied on screens smaller than that specified by the xs-breakpoint, and all screen sizes larger - unless overridden.

### Actual Behavior
No spacing is applied at all - neither when screen size is smaller than what the xs-breakpoint defines, nor larger.

### Reproduction Link
<a href="https://codepen.io/Duard/pen/dyPbEgZ" target="_blank">https://codepen.io/Duard/pen/dyPbEgZ</a>

### Other comments
When applying spacing classes without breakpoints using the [breakpoint service object](https://vuetifyjs.com/en/customization/breakpoints#breakpoint-service-object) it works as expected (e.g. `:class="{ 'my-12': $vuetify.breakpoint.smAndDown }"`).

However, I would prefer to rely on using classes rather than the above, because:
1. Code gets messier using the above solution, as compared to a simple class.
2. The above applies the class only when resizing of the window stops, which creates a slightly worse user-experience.

Thank you very much for all the work done on this wonderful project!

**Comment by jacekkarczmarczyk** [comment]
my-12 is applied for xs and up, only higher breakpoints need a modifier
