### ISSUE TITLE
[Documentation] 404 on bars/toolbars

### ISSUE THREAD

**Issue by pacific202** [vuetifyjs/vuetify#9842]
### Environment

**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Visit the page

### Expected Behavior
See toolbar documentation

### Actual Behavior
Whoops, 404
The page you were looking for does not exist

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/toolbars" target="_blank">https://vuetifyjs.com/en/components/toolbars</a>

**Comment by MajesticPotatoe** [comment]
Maybe a cache issue, try clearing your cache. The link you provided seems to work fine.

**Comment by pacific202** [comment]
Fixed
