### ISSUE TITLE
[Feature Request] v-menu color prop

### ISSUE THREAD

**Issue by PortStone** [vuetifyjs/vuetify#9844]
### Problem to solve
If the user switches from light to dark the v-select changes to dark and the menu can be switched to dark as well with the menu-props but I don't have an option to change the primary color as well. This makes it hard to read the selected item on the menu if the user has dark theme selected.

with that I could easily do :menu-props="{ dark: true,  color: $vuetify.theme.themes.dark.primary}"
![image](https://user-images.githubusercontent.com/27790087/69921041-ec43cf80-148e-11ea-91cf-f3545616c2d1.png)
As you can see the icon has changed his primary color to the dark primary color but not the menu and therefore it is hard to read the selected text.
### Proposed solution
Add a color prop to v-menu

**Comment by KaelWD** [comment]
The list is using your primary color, I don't know where the lighter one on the icon is coming from. You should make sure your primary color has good contrast against the theme background, as it's used by default for hyperlinks and other elements without their own backgrounds like text fields and list items.

**Comment by PortStone** [comment]
The icon is using my primary color for the dark theme which should be used for selecting the items as well but I don't know how I change it for the items and because of that it still uses the primary color from the light theme. You can see my full v-select here:
```
<v-select
  :items="states"
  label="Artikel"
  :prepend-icon="icons.mdiPackageVariantClosed"
  :dark="themeSwitch"
  menu-props="{ dark: themeSwitch }"
  :color="$vuetify.theme.themes[themeColor].primary"
 ></v-select>
```
primary color for dark theme: "#BB86FC" as you can see on the icon and my primary color for the light theme is "#6200EE"

**Comment by PortStone** [comment]
The issue closed itself because I found a new way to handle dark / light which will use the correct primary color.
