### ISSUE TITLE
[Bug Report] v-model not updated when create new field on v-combobox

### ISSUE THREAD

**Issue by max3163** [vuetifyjs/vuetify#9846]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Select combobox, add a new item with typing text and after click directly on the button. 

### Expected Behavior
Sync the v-model with the combobox element enter.

### Actual Behavior
The v-model is not updated and the last value is display on the console.

### Reproduction Link
<a href="https://codepen.io/max31_/pen/VwYwjRR" target="_blank">https://codepen.io/max31_/pen/VwYwjRR</a>

**Comment by xmilygit** [comment]
I also encountered the same problem as you, please solve it?

**Comment by johnleider** [comment]
This isn't something that is solvable. In this case, when you click on the outside button, the chain of events is something like this:

- button click event
- click event method invoked
- combobox is blurred
- combobox watcher is triggered for blur
- combobox updates its value

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
