### ISSUE TITLE
[Feature Request] VDataTable: Option to hide columns

### ISSUE THREAD

**Issue by malkhuzayyim** [vuetifyjs/vuetify#9847]
### Problem to solve
Ability to "hide" columns temporarily within VDataTables

I find myself implementing it often, I think it'd be great to include it as a default option within the component.

### Proposed solution
https://codepen.io/malkhuzayyim/pen/VwYwPXV?editors=1010

Complete codepen example, ability to hide columns using a v-select.

**Comment by KaelWD** [comment]
This isn't necessary in my opinion, it adds api complexity and you've shown it can be implemented very easily if needed.

**Comment by nekosaur** [comment]
I agree with @KaelWD

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
