### ISSUE TITLE
[Feature Request] Treeview Hover class

### ISSUE THREAD

**Issue by rogeralsing** [vuetifyjs/vuetify#9852]
### Problem to solve
I cannot find any way to override the hover effect/class on the TreeView.
There is class and active-class, but no hover-class.

### Proposed solution
Add a hover-class setting to allow the user to tweak how the hover effect is rendered.

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8416
