### ISSUE TITLE
[Bug Report] Expanded row and content class is not set on data table when a row is expanded programmatically

### ISSUE THREAD

**Issue by jrigunawan** [vuetifyjs/vuetify#9853]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Google Chrome
**OS:** Windows 10

### Steps to reproduce
Click any row in the data table

### Expected Behavior
The class on the <tr> that is just clicked is set to "v-data-table__expanded v-data-table__expanded__row"

The class on the expanded content is set to "v-data-table__expanded v-data-table__expanded__content"

### Actual Behavior
No class is set

### Reproduction Link
<a href="https://codepen.io/jgunawan-dc/pen/bGNGLpv" target="_blank">https://codepen.io/jgunawan-dc/pen/bGNGLpv</a>

**Comment by jacekkarczmarczyk** [comment]
`expanded-item` expects that you provide a `<tr>` as well, so you need to add classes also by 
yourself (however it may be considered to be inconsistent with built in expand behaviour where you don't need `<tr>`)

Same about `item` slot - you're providing `<tr>` here so you also need to provide all classes and other attributes you need

https://codepen.io/jkarczm/pen/bGNGzBv?editors=1010

Maybe we could provide these classes in slot props
