### ISSUE TITLE
[Bug Report] Slide is not displayed when you delete an active slide in carousel

### ISSUE THREAD

**Issue by Apo-S** [vuetifyjs/vuetify#9854]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.14.5

### Steps to reproduce
On the first slide, click "Remove slide with a base color," which is located at the top

### Expected Behavior
The second slide with the color "secondary" will become active

### Actual Behavior
The slide is not displayed

### Reproduction Link
<a href="https://codepen.io/Apo-S/pen/RwNwBKY" target="_blank">https://codepen.io/Apo-S/pen/RwNwBKY</a>

### Other comments
This happens when you delete an active slide if it is not the last

**Comment by johnleider** [comment]
Workaround: https://codepen.io/johnjleider/pen/eYmKbGE
