### ISSUE TITLE
[Bug Report] ref on VLabel <v-label> doesn't work

### ISSUE THREAD

**Issue by omscarr** [vuetifyjs/vuetify#9855]
### Environment
**Vuetify Version:** 1.5.21
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
add a ref to a VLabel.
Check vm.$refs and confirm that the VLabel's ref is not there

### Expected Behavior
VLabel's ref should be in $refs

### Actual Behavior
VLabel's ref is missing from $refs

### Reproduction Link
<a href="https://codepen.io/mhealy-avinet/pen/qBEBMqg" target="_blank">https://codepen.io/mhealy-avinet/pen/qBEBMqg</a>

### Other comments
This seems to be fixed in v2, but I could not find a bug report for v1.5.
Code pen attached shows that the refs on the VTextField and the span do work, but the ref on the VLabel added in the same fashion does not work.
The same code on the v2 codepen template does work.

**Comment by jacekkarczmarczyk** [comment]
- for 1.5 version we focus only on security and critical issues, this issue doesn't seem to be one. 
- 2.0 also doesn't work as you'd expect - compare the label's `ref` with `refsResult`
- `v-label` is more like internal component, intended to use only by Vuetify components

**Comment by johnleider** [comment]
This is resolved as of the latest version and will not be backported.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
