### ISSUE TITLE
[Bug Report] Calender first-interval set to 10 but starts from 2AM

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#9861]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
??

### Expected Behavior
15 minutes label for each row.On click should take start time as event start time.

### Actual Behavior
Returns 3 AM

### Reproduction Link
<a href="https://codepen.io/spider007/pen/RwNwvzM" target="_blank">https://codepen.io/spider007/pen/RwNwvzM</a>

**Comment by KaelWD** [comment]
Please detail exactly what actions I need to take in that codepen and what the expected results are. Based on the title first-interval is working correctly, 9 * 15min = 2:15

**Comment by kunalahirrao** [comment]
I want interval to start at 9AM.
Expected ---

![Calendar_PH-01](https://user-images.githubusercontent.com/52235656/70030937-3da7a800-15d0-11ea-9c9f-62408f81317a.jpeg)

**Comment by KaelWD** [comment]
Then you need to set it to 36.

**Comment by kunalahirrao** [comment]
How to get 15 minutes label for each row
