### ISSUE TITLE
[Bug Report] Time stamp  for each row (time interval) in Calendar Component.

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#9863]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Adding Props to add time stamp for each interval

### Expected Behavior
Interval with timestamp

### Actual Behavior
No timestamp for each row but it is there for entire interval

### Reproduction Link
<a href="https://codepen.io/spider007/pen/RwNwvzM" target="_blank">https://codepen.io/spider007/pen/RwNwvzM</a>

**Comment by kunalahirrao** [comment]
![Calendar_PH-01](https://user-images.githubusercontent.com/52235656/70033125-d2140980-15d4-11ea-9155-90b513617974.jpeg)
Expected Output

**Comment by KaelWD** [comment]
`:show-interval-label="() => true"`

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
