### ISSUE TITLE
[Bug Report] Outlined text field in radio-group's label slot does not align correct

### ISSUE THREAD

**Issue by mseele** [vuetifyjs/vuetify#9864]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Having a v-textfield with style outlined inside a radio group does not look correct.

### Expected Behavior
textfield and label should be aligned correct

### Actual Behavior
Having a v-textfield with style outlined inside a radio group does not look correct.
If textfield is inside radio v-slot:label, the whole textfield and the label is to high.
If textfield just comes after radio, only label is rendered to high.

 v-textfield without style outlined looks correct

### Reproduction Link
<a href="https://codepen.io/mseele/pen/wvBBvgZ" target="_blank">https://codepen.io/mseele/pen/wvBBvgZ</a>

**Comment by benjamindedonder** [comment]
I'm having the same issue with selects and disabled text fields inside a radio group.
In my case I'm using expansion panels to select different parts of a form. Inside the header of an expansion panel is a radio button and inside the content are selects and text fields.

v-select (style solo) has a misplaced label because

```
.v-text-field.v-text-field--solo .v-label {
    top: calc(50% - 10px);
}
```

gets overridden by

```
.v-input--selection-controls.v-input .v-label {
    top: 0;
}
```

and a disabled v-text-field (style solo) has the wrong text color because

```
.theme--light.v-input--is-disabled .v-label, .theme--light.v-input--is-disabled input, .theme--light.v-input--is-disabled textarea {
    color: rgba(0,0,0,.38);
}
```

gets overridden by

```
.theme--light.v-input:not(.v-input--is-disabled) input, .theme--light.v-input:not(.v-input--is-disabled) textarea {
    color: rgba(0,0,0,.87);
}
```

**Comment by Kotoriii** [comment]
Just came across this issue myself. Thanks for posting it and hoping for a rapid fix.

**Comment by dalholm** [comment]
@mseele 
I had the same issue, but i find o good solution in the docs. 
```
<v-card-text>
      <v-row align="center">
        <v-radio value="answer_a" hide-details class="shrink mr-2 mt-0"></v-radio>
        <v-text-field label="Include files"></v-text-field>
      </v-row>
</v-card-text>
```
Look here: [https://vuetifyjs.com/en/components/selection-controls#checkboxes-inline-with-a-textfield](url)

**Comment by benjamindedonder** [comment]
I came across a similar issue but unrelated I think:
A v-file-input also has the wrong text color when disabled.

I fixed it by adding
```
.v-input.v-input--is-disabled .v-file-input__text {
    color: rgba(0,0,0,.38);
}
```

**Comment by jacekkarczmarczyk** [comment]
First issue (input not in `label` slot) was fixed in 2.2.2, but when the input is placed in the `label` slot it changed a bit:
<https://codepen.io/jkarczm/pen/NWPMgOP>

**Comment by johnleider** [comment]
The label alignment issues have been resolved. In regards to the margin under the radio in the custom row implementation, just apply the `mb-0` class: https://codepen.io/johnjleider/pen/VwYNrwM

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jacekkarczmarczyk** [comment]
For https://codepen.io/jkarczm/pen/NWPMgOP see https://github.com/vuetifyjs/vuetify/issues/10360 (workaround may not work though, needs to be more specific to not affect text-field's label)

**Comment by carlosbertarinijr** [comment]
Try this: 
 .v-input--selection-controls.v-input .v-label { top: 'your heigth' !important; }
