### ISSUE TITLE
[Bug Report] VSkeletonLoader not showing in production

### ISSUE THREAD

**Issue by SumNeuron** [vuetifyjs/vuetify#9865]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Firefox 71.0
**OS:** Linux x86_64

### Steps to reproduce
NOTE: it is gitlab not github (changed to pass form validation)

1. Clone repo
2. use python docker script to build and launch dev environment `python docker.py -c up`
3. go to localhost. You should see v-skeleton-loader of type table which comes from component `VBoilerplate.vue` (taken from Vuetify.js documentation)
4. stop dev environment `python docker.py -c down`
5. launch production environment `python docker.py -c up -p`
6. go to localhost:3000, notice component is mounted, but skeleton loader is nowhere to be seen (you can also see the deployed gitlab page here: https://sumneuron.gitlab.io/vskel/ vue tools are enabled)

### Expected Behavior
"It just works", no extra configuration between dev and production for vskeletonloader / vboilerplate

### Actual Behavior
skeletonloader not shown in production

### Reproduction Link
<a href="https://gitlab.com/SumNeuron/vskel" target="_blank">https://gitlab.com/SumNeuron/vskel</a>

I hope dockerized git repo is ok

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/70139042-38c42080-16c4-11ea-84cb-9a782a0bdc79.png)

**Comment by SumNeuron** [comment]
@jacekkarczmarczyk as stated in comments it is a gitlab repository. The form only allowed gothub

**Comment by jacekkarczmarczyk** [comment]
OK, btw you can edit issue in github

**Comment by SumNeuron** [comment]
@jacekkarczmarczyk I didn't know if that would cause issues since there is the form to populate it. Are you able to reproduce it at least?

**Comment by jacekkarczmarczyk** [comment]
No, I don't use docker and I'm not familiar with nuxt, also I don't think it requires any of them to reproduce. Did you try to create a simple vue-cli reproduction?

**Comment by SumNeuron** [comment]
Would you be willing to humor me then? You do not have to use docker. you can 

```
npm run dev
```

and for production

```
npm build
npm run start
```

**Comment by SumNeuron** [comment]
@jacekkarczmarczyk does that work for you? You don't need to be familiar with nuxt to see the issue

**Comment by jacekkarczmarczyk** [comment]
I can reproduce but it seems more like a `nuxtjs` or `@nuxtjs/vuetify` issue

**Comment by kevinmarrec** [comment]
Not a **Nuxt.js** or **Vuetify** issue, it's just Vue.js `render` function that doesn't support component names **unless it is already registered globally**. Component should directly passed to the `h`.

See https://github.com/nuxt-community/vuetify-module/issues/224#issuecomment-563141479 for in-depth explanations.

**Comment by KaelWD** [comment]
Yeah this is https://github.com/vuejs/vue/issues/7492
