### ISSUE TITLE
[Bug Report] Timepicker minutes are incorrectly set in XS view

### ISSUE THREAD

**Issue by duebbert** [vuetifyjs/vuetify#9867]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Firefox 70.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Open the reproduction link (or even on the Timepicker documentation page: https://vuetifyjs.com/en/components/time-pickers)
2. Change to a mobile/XS view. (Views SM and up seem to be fine.)
3. Click the picker and select an hour.

### Expected Behavior
The hour should be set to the selected hour and the minutes should stay the same.

### Actual Behavior
The minutes also change. For example, if clicking "9" then the minutes will change to "45".

### Reproduction Link
<a href="https://codepen.io/duebbert/pen/rNaaVYX" target="_blank">https://codepen.io/duebbert/pen/rNaaVYX</a>

### Other comments
I believe this is a regression but couldn't test previous versions yet.

**Comment by duebbert** [comment]
Just checked all the way back to 2.0.0 and it seems this bug is in all versions.

**Comment by duebbert** [comment]
I think this issue can be closed. It seems to be a specific Firefox problem and it only happens when the "touch simulation" is activated (which it is by default). When that is deactivated all works fine.

**Comment by jacekkarczmarczyk** [comment]
Yeah, just checked on mobile firefox and it works fine
