### ISSUE TITLE
[Bug Report] Upgraded to v2, REMs rescaled?

### ISSUE THREAD

**Issue by icarusmiles** [vuetifyjs/vuetify#9869]
### Environment
**Vuetify Version:** 2.1.12
**Last working version:** 1.5.21
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.14.6

### Steps to reproduce
`html` on the latest version of Vuetify shows as `16px` for the font-size, causing my old theme REM to be rescaled. 

### Expected Behavior
The `html` font-size and other required REM px classes to be retained the same so my REM scaling remains the same.

### Actual Behavior
The `html` font-size was pushed from `14px` to `16px` between v1.5 to v2, modifying (inspect element) to `14px` fixes some elements but not all. 

### Reproduction Link
<a href="http://codepen.io/" target="_blank">N/A</a>

### Other comments
Is there a recommended approach to keeping the same REM scaling between Vuetify versions? Should I switch all REMs to fit the new pattern, switch to px, or force `html` font-size and other required elements to use old pattern?

**Comment by johnleider** [comment]
You should update `$font-size-root` to whatever default value you want. MD1 used 14px and MD2 uses 16px.

You can find more information on sass variables here: https://vuetifyjs.com/customization/sass-variables

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
