### ISSUE TITLE
[Feature Request] data table expand add transition

### ISSUE THREAD

**Issue by peppeg85** [vuetifyjs/vuetify#9871]
### Problem to solve
hello, on the old vuetify the expand slot had the transition effect, now it's disappeared, i'm trying with v-expand-transition but it doesn't work fine, any suggestions?

https://codepen.io/peppeg85/pen/ZEYYWMg?editors=1010

### Proposed solution
add transition natively to expansion slot

**Comment by Webifi** [comment]
They intentionally removed the transition in 2.x, and it doesn't seem like there's any rush to bring it back.

See my code pen here for how I got it working.  Takes a fair amount of code: https://github.com/vuetifyjs/vuetify/issues/8197#issuecomment-546002356

**Comment by peppeg85** [comment]
ok, thank you for the help
