### ISSUE TITLE
[Bug Report] Incorrect tooltip position inside v-for

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#9872]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
- Open reproduction link
- Hover over `v-chip` items and take a look at the tooltip position

### Expected Behavior
Tooltip should be displayed under the hovered element

### Actual Behavior
Tooltip becomes attached to the **first** element you hover and doesn't change position when you hover over other elements of the `v-for`

### Reproduction Link
<a href="https://codepen.io/AlekseiHoffman/pen/rNaaypv" target="_blank">https://codepen.io/AlekseiHoffman/pen/rNaaypv</a>

**Comment by KaelWD** [comment]
In 2.3 you'll only be able to have a single element in the slot so this isn't worth fixing.
