### ISSUE TITLE
Error/Warning in Navigation Drawer

### ISSUE THREAD

**Issue by nickycdk** [vuetifyjs/vuetify#9875]
Hey - Im using version 2.1.13, and are using the navigation drawer component, however, it gives me an error/warning: Error in beforeCreate hook: "TypeError: Cannot read property 'tag' of undefined"
in the file:  at VueComponent.provide (VNavigationDrawer.ts?6ca0:52)

When looking inside, it seems it's this: 
provide (): object {
    return {
      isInNav: this.tag === 'nav',
    }
  },

it's failing on... Why I have no idea?

Im using the component in a sub component, and are using it like so: 

<v-navigation-drawer color="#fff"
                       v-model="drawer"
                       light
                       app
                       fixed
                       hide-overlay
                       style="top:80px"
                       expand-on-hover
                       permanent>
...... Navigation items...
 </v-navigation-drawer>

**Comment by mbaev** [comment]
It was a good question, though
