### ISSUE TITLE
[Bug Report] Error from Navigation Drawer

### ISSUE THREAD

**Issue by nickycdk** [vuetifyjs/vuetify#9876]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.15.1

### Steps to reproduce
Try inserting the component... 

### Expected Behavior
Not to give me an error

### Actual Behavior
?

### Reproduction Link
<a href="https://jsfiddle.idonthaveone.com" target="_blank">https://jsfiddle.idonthaveone.com</a>

### Other comments
Hey - Im using version 2.1.13, and are using the navigation drawer component, however, it gives me an error/warning: Error in beforeCreate hook: "TypeError: Cannot read property 'tag' of undefined"
in the file:  at VueComponent.provide (VNavigationDrawer.ts?6ca0:52)

When looking inside, it seems it's this: 
`provide (): object {
    return {
      isInNav: this.tag === 'nav',
    }
  },`

it's failing on... Why I have no idea?

Im using the component in a sub component, and are using it like so: 

`<v-navigation-drawer color="#fff"
                       v-model="drawer"
                       light
                       app
                       fixed
                       hide-overlay
                       style="top:80px"
                       expand-on-hover
                       permanent>
...... Navigation items...
 </v-navigation-drawer>`

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
