### ISSUE TITLE
[Documentation] Vuetify ---  Calender Weekly not showing on website

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#9877]
### Environment

**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
NA

### Expected Behavior
It should show weekly calender

### Actual Behavior
Weekly calender

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/calendars" target="_blank">https://vuetifyjs.com/en/components/calendars</a>

**Comment by KaelWD** [comment]
#8525
https://github.com/vuetifyjs/vuetify/pull/9862#issuecomment-561054585

**Comment by kunalahirrao** [comment]
![vue](https://user-images.githubusercontent.com/52235656/70135828-d281d280-16b0-11ea-9a23-079805231729.PNG)

**Comment by MajesticPotatoe** [comment]
This has been resolved.
