### ISSUE TITLE
[Bug Report] v-data-table's "select all" button not updated when paging hides rows

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuetifyjs/vuetify#9880]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Linux x86_64

### Steps to reproduce
Note - Please refer to the codepen when reproducing steps

Steps to reproduce:
 - Click on the Green Toggle button.
 - Notice how the Select All button changes when an item has been selected.
 - Click on the Green Toggle button to reset the checked row.
 - Notice how the Select All button changes when an item has been deselected.
 - Change paging to only show first 5 entries.
 - Click on the Green Toggle button.
 - Notice how the Select All button is unaware an item has been selected or deselected, since it is hidden by paging.

### Expected Behavior
The 'Select All' checkbox should be aware of any selected rows, regardless of whether or not it is hidden by paging.

### Actual Behavior
The 'Select All' checkbox does not respond to any row/item not shown in the current paging

### Reproduction Link
<a href="https://codepen.io/uglyhobbitfeet/pen/PowwMVN" target="_blank">https://codepen.io/uglyhobbitfeet/pen/PowwMVN</a>

**Comment by nekosaur** [comment]
This is intended behavior. The select-all toggle is only for the items on current page. You can see this by setting items per page to 5, clicking on select-all, then going to next page.

**Comment by UglyHobbitFeet** [comment]
Where does it say that the functionality of the 'select all' is only for
the current viewed page?  On the v-data-table section I see " The
show-select prop will render a checkbox in the default header to toggle all
row".  By definition, 'all' implies every row in the entire table.  I see
this as a bug as the 'select all' does not correctly reflect what is
actually selected in 'all' of the table.  Please reinstate this ticket as I
see it as a valid bug.

**Comment by nekosaur** [comment]
That's a documentation issue. We could certainly phrase that in a better way. But the toggle is working as intended.

**Comment by UglyHobbitFeet** [comment]
Is there support for a select all working as 'all'?  This is definitely
seen as a bug from our use-case and would be a show-stopper without a
workaround.

Thanks!
