### ISSUE TITLE
[Documentation] v-dialog should document the input event

### ISSUE THREAD

**Issue by SuspendedPhan** [vuetifyjs/vuetify#9881]
### Environment

**Browsers:** Chrome 77.0.3865.120
**OS:** Linux x86_64

### Steps to reproduce
"input" is not listed in the events tab. Examples use v-model, but confusing for begineers. textfield documents it.

### Expected Behavior
Should show that v-dialog emits input event

### Actual Behavior
Missing

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/dialogs" target="_blank">https://vuetifyjs.com/en/components/dialogs</a>

**Comment by MajesticPotatoe** [comment]
resolved in d6a5b06
