### ISSUE TITLE
[Bug Report] v-data-table shows loading message after splicing out all rows

### ISSUE THREAD

**Issue by cdecinkoKnight** [vuetifyjs/vuetify#9882]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Create a v-data-table with multiple rows. Add a button to each row that when clicked deletes the current row.  Delete all the rows.

### Expected Behavior
The table is now empty and should display the no-data-text value.

### Actual Behavior
Instead the loading-text value is displayed.

### Reproduction Link
<a href="https://codepen.io/cdecinko_knight/pen/qBEdOrr?#anon-signup" target="_blank">https://codepen.io/cdecinko_knight/pen/qBEdOrr?#anon-signup</a>

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/70205531-69659200-1778-11ea-9552-fb9534aa523b.png)
