### ISSUE TITLE
Feature request: datepicker event indicator

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#989]
I think it might be a nice addition if you can add an array of dates to the datepicker that will show a small indicator on those dates.
Let's say there is something going on next week and the user can clearly see there is an event because that day has a special marker.

A picture speaks a thousand words, so.. 
![capture](https://user-images.githubusercontent.com/3471363/28207596-8ae3061e-688a-11e7-8692-9001bfd8858a.PNG)

Alternatively: maybe a slot for a day number so total customization is possible

**Comment by jacekkarczmarczyk** [comment]
With https://github.com/vuetifyjs/vuetify/pull/2109 it will be possible to mark events using the following code:

```vue
<template>
  <v-app id="inspire" :dark="dark">
    <v-content>
      <div style="width: 290px">
        <v-date-picker :day-format="d"></v-date-picker>
      </div>
    </v-content>
  </v-app>
</template>

<script>
export default {
  data() {
    return {
      d: date => {
        return '<span class="' + (date.substr(9, 1) === '1' ? 'event' : '') + '">' + date.substr(8, 2).replace(/^0/, '') + '</span>'
      }
    }
  }
}
</script>

<style>
.event {
  position: relative;
}

.event:after {
  display: block;
  content: "";
  width: 6px;
  height: 6px;
  background: blue;
  border-radius: 50%;
  position: absolute;
  bottom: -3px;
  left: calc(50% - 3px);
}
</style>
```

![image](https://user-images.githubusercontent.com/15625235/31582435-b23ec8b8-b1ac-11e7-9067-355a60b8d097.png)

It doesn't mean that this is the final solution though

**Comment by mknnaren** [comment]
Hey @jacekkarczmarczyk , I tried your temp. solution but its not working. Can you please share the version nos. of Vuetify and Vue you used for this. 

Thank you

**Comment by jacekkarczmarczyk** [comment]
0.17 (not released yet)
