### ISSUE TITLE
[Bug Report] I Think it's bug v-select

### ISSUE THREAD

**Issue by samvelian13** [vuetifyjs/vuetify#9899]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 7

### Steps to reproduce
I use v-select into v-dialog, with multiple select and vuetify use rules, when I log the rule value it triggered many times , but must be one time, if you move out the select box it works normally or if I set v-dialog :value=true always true it works normally, but when v-modal value or v-modal is dynamic , it doesn/t work correctly

### Expected Behavior
The function for rule must trigger one time when I select the option and it's work like this when I bind the value to true

### Actual Behavior
I need help to understand why

### Reproduction Link
<a href="https://www.codepen.com/" target="_blank">https://www.codepen.com/</a>

**Comment by samvelian13** [comment]
I don't have codepen or other link it is in my local project, but I need solution for this asap

**Comment by samvelian13** [comment]
the problem is going from v-dialog value I think, if Anyone know solution plz let me know

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)
