### ISSUE TITLE
[Bug Report] Microsoft Edge (Not Chromium) Only v-dialog and v-snackbar Issue

### ISSUE THREAD

**Issue by MRSessions** [vuetifyjs/vuetify#9905]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Use Edge Browser (not the new Chromium version)
A v-dialog with persistent is needed and then a v-snackbar notification needs to popup while the dialog is up

Issue is only in Edge

### Expected Behavior
Ability to close a snackbar notification without affecting the dialog

### Actual Behavior
Close button on the snack bar is not clickable unless you make the window small enough for it to hover over the dialog. When using select an element in dev tools, you can't select the snackbar or close button with a dialog up.

### Reproduction Link
<a href="https://codepen.io/MRSessions/pen/eYmpdxe?editors=1000" target="_blank">https://codepen.io/MRSessions/pen/eYmpdxe?editors=1000</a>

### Other comments
This is only affecting the Edge (Project Spartan, not Chromium).

The new Edge (Chromium) browser works, Chrome and Firefox both work.

**Comment by johnleider** [comment]
Move `v-snackbar` out of the `v-dialog`'s content: https://codepen.io/MRSessions/pen/eYmpdxe?editors=1000

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
