### ISSUE TITLE
[Bug Report] v-select options is rendered behind v-menu

### ISSUE THREAD

**Issue by jrigunawan** [vuetifyjs/vuetify#9906]
### Environment
**Vuetify Version:** 2.1.13
**Last working version:** 1.5.21
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Click the button, expand the expansion panel, click on the v-select element.

### Expected Behavior
The v-select options are displayed in front of v-menu

### Actual Behavior
The v-select options are displayed behind v-menu

### Reproduction Link
<a href="https://codepen.io/jgunawan-dc/pen/KKwdMYP" target="_blank">https://codepen.io/jgunawan-dc/pen/KKwdMYP</a>

**Comment by jrigunawan** [comment]
My temporary solution for this situation for now is setting a class to through menu-props, then have a CSS rule that targets that class with z-index higher than the parent menu.

**Comment by johnleider** [comment]
This can be resolved by changing the `initDetach` fn to append the child instead of shifting it to the top.

https://github.com/vuetifyjs/vuetify/blob/19bf5d319bf810a5ca97efef84e90df01dfd9edb/packages/vuetify/src/mixins/detachable/index.ts#L144

Changing this:
```
target.insertBefore(
  this.$refs.content,
  target.firstChild
)
```
to this:
```
target.appendChild(this.$refs.content)
```

thoughts @KaelWD ?

**Comment by KaelWD** [comment]
I remember prototyping detaching to a wrapper element at the end of the body but idk where that went.
