### ISSUE TITLE
[Documentation] Hitting "/" won't focus the search input

### ISSUE THREAD

**Issue by jpereira94** [vuetifyjs/vuetify#9911]
### Environment

**Browsers:** Firefox 70.0, Google Chrome, Mozilla Firefox
**OS:** Linux, Ubuntu undefined

### Steps to reproduce
I'm using a Portugues keyboard, and can't focus on the search input with shift+7 or the keypad / . I have tested this in multiple computers with different linux distros and on firefox and chrome, all using a PT keyboard.

### Expected Behavior
When hitting the "/" to focus the search input.

### Actual Behavior
Nothing happens

### Reproduction Link
<a href="https://vuetifyjs.com/en/" target="_blank">https://vuetifyjs.com/en/</a>

**Comment by phiter** [comment]
Hi, @jpereira94 . I'm also using a portuguese keyboard (ABNT), and pressing semicolon `;` does the trick.

**Comment by jpereira94** [comment]
Hi @phiter, no it doesn't work. I have this [keyboard layout](https://en.wikipedia.org/wiki/Portuguese_keyboard_layout#/media/File:KB_Portuguese.svg) (with a numpad) and have tried the comma, semicolon, point, colon, hyphen, undescore (using the necessary shift modifier) to no avail.

**Comment by nekosaur** [comment]
My suggestion would be to change the shortcut to something like `.` or `,`

**Comment by thoni56** [comment]
In Firefox the slash brings up the browsers search box... (At least for me...)

**Comment by jpereira94** [comment]
https://github.com/vuetifyjs/vuetify/blob/47847224a4a94fdbf39208932b1c631dd0b39b63/packages/docs/src/layouts/documentation/Search.vue#L58

Maybe changing this line from `e.keyCode === 191` to `e.key === '/'`does the trick?
