### ISSUE TITLE
[Bug Report] Color prop not taking effect on v-select multiple

### ISSUE THREAD

**Issue by mirikerstein** [vuetifyjs/vuetify#9914]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Adding the color prop to a v-select does not affect the colors of the checkboxes inside the v-select.

### Expected Behavior
The checkboxes within the list should assume the color specified in the color prop.

### Actual Behavior
The checkboxes seem to be perpetually blue.

### Reproduction Link
<a href="https://codepen.io/mkers/pen/zYxrvog" target="_blank">https://codepen.io/mkers/pen/zYxrvog</a>

**Comment by mirikerstein** [comment]
I see that this was discussed a while back, but apparently it hasn't been incorporated: 
https://github.com/vuetifyjs/vuetify/pull/2189

**Comment by jacekkarczmarczyk** [comment]
use `item-color` prop
