### ISSUE TITLE
[Feature Request] Counter Clockwise Progress Circular component

### ISSUE THREAD

**Issue by sangheili868** [vuetifyjs/vuetify#9918]
### Problem to solve
I'm using a progress circular component to represent a character's health in a game, and I think it would look better if the circle rotated counter-clockwise instead of clockwise.
https://codepen.io/sangheili868/pen/dyPGdbg

### Proposed solution
Add a "counterClockwise" boolean prop to the "v-progress-circular" component. If true, display the progress counter-clockwise instead of clockwise.

Alternatively, add a "direction" string prop with possible values "clockwise" and "counterClockwise", defaulting to "clockwise".

**Comment by jacekkarczmarczyk** [comment]
Easy to do with `style="transform: scaleX(-1)"`

**Comment by sangheili868** [comment]
@jacekkarczmarczyk Of course! That works for me. Thanks!
