### ISSUE TITLE
[Feature Request] Set a class for v-select items

### ISSUE THREAD

**Issue by bulentAkgul** [vuetifyjs/vuetify#9919]
### Problem to solve
I use a bunch of v-select all over my application and some of their items need styling separately. As far as I can see there is no way to select one particular v-menu.

### Proposed solution
It would be great if they have a special class name if a class name is defined in v-select. For instance, such an item:

    <v-select
        class="my-awesome-list"
        :items=items
    ></v-select>

can have a menu like this:

    <div class="v-menu__content theme--light v-menu__content--fixed my-awesome-list__items">...

**Comment by KaelWD** [comment]
`<v-select :menu-props="{ contentClass: 'my-awesome-list' }"`

**Comment by masumbillah** [comment]
How to set class in ```<div class="v-list-item__content">...``` or ```<div class="v-list-item__title">...```

Actually I want to add a class with ```v-list-item__content``` or ```v-list-item__title```
My Items list 

```
[
{ text: 'testing 1', value: 'testing-1-slug' }
]
