### ISSUE TITLE
Hover styles are present on <v-btn tag='a' disabled />

### ISSUE THREAD

**Issue by megapctr** [vuetifyjs/vuetify#992]
### Steps to reproduce
Try using `<v-btn tag='a' disabled />` - it displays a button which changes background on hover.

### Versions

Chrome 59

### What is expected ?

The second button should look the same as the first button

### What is actually happening ?

The second button doesn't look like it's disabled

### Reproduction Link

https://codepen.io/anon/pen/qjvodr

**Comment by johnleider** [comment]
I can confirm that this is fixed in dev.
