### ISSUE TITLE
[Bug Report] Mocking vuetify lang property with vue test utils

### ISSUE THREAD

**Issue by JohanSantamaria17** [vuetifyjs/vuetify#9923]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Other
**OS:** Windows 10

### Steps to reproduce
Following the documentation https://vuetifyjs.com/en/getting-started/unit-testing
I mocked this property in two ways:

Mocking thourgh vuetify object
vuetify = new Vuetify({ mocks: { $vuetify: { breakpoint: new Breakpoint(opts), lang: { t: () => { }, }, theme: { dark: false } } } }) localVue.use(vuetify);

Mocking through mount options
wrapper = mount(CampaignListPage, { router, localVue, store, vuetify, sync: false, mocks: { $vuetify: { breakpoint: {}, lang: { t: (key) => { } }, theme: { dark: false } } } })

### Expected Behavior
lang mocked property that comes from $vuetify global variable is defined

### Actual Behavior
I am getting the following error
Error in render: "TypeError: Cannot read property 'lang' of undefined" at node_modules\vuetify\lib\components\VDataTable\VDataTableHeaderDesktop.js:52:50)

This is so weird because at https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VDataIterator/VDataIterator.ts#L194 this works fine

### Reproduction Link
<a href="https://jsfiddle.net/g86q27wL/" target="_blank">https://jsfiddle.net/g86q27wL/</a>

**Comment by JohanSantamaria17** [comment]
Hello @KaelWD I was trying to figure out and I found a @johnleider's comment, I tested it and this worked 👍 

https://github.com/vuetifyjs/vuetify/issues/4964#issuecomment-500574050

**Comment by dnutiu** [comment]
I've solved this by mocking lang and only use vuetify on the Vue instance, not localVue.

```
Vue.use(Vuetify);
...
    let component = mount(ModelConfusionMatrixParams, {
      localVue,
      store,
      propsData: {
        model
      },
      mocks: {
        $vuetify: {
          lang: {
            t: (val: string) => val
          }
        }
      },
      vuetify: new Vuetify(),
      stubs
    });
```
