### ISSUE TITLE
[Bug Report] Moving the tack on v-slider on mobile causes the screen to scroll

### ISSUE THREAD

**Issue by HeadAdmiral** [vuetifyjs/vuetify#9925]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
npm run serve
Open local server on a mobile device
Move the slider back and forth
Screen will scroll when the slider tack is moved back and forth

### Expected Behavior
Screen should not scroll at all if slider is in use

### Actual Behavior
Screen scrolls and moves around while sliding the tack

### Reproduction Link
<a href="https://codepen.io/HeadAdmiral/pen/NWPxeqe" target="_blank">https://codepen.io/HeadAdmiral/pen/NWPxeqe</a>

### Other comments
Can probably be resolved just by changing the page's CSS when the tack is in use.

**Comment by johnleider** [comment]
Need more information, the reproduction steps and the codepen do not make sense.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
