### ISSUE TITLE
[Bug Report] Date pickers - birthday picker not behaving accurately in v-for loop

### ISSUE THREAD

**Issue by MRUBS** [vuetifyjs/vuetify#9928]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
it should work as start from select year, but not working in n loop using v-for, please take a look at the jsfiddle link,

### Expected Behavior
normally it works but not working in n loop using v-for, please take a look at the jsfiddle link, the first one has the select from year, month and date, but the others are not.

### Actual Behavior
normally it works but not working in n loop using v-for, please take a look at the jsfiddle link, the first one has the select from year, month and date, but the others are not.

### Reproduction Link
<a href="https://jsfiddle.net/mrubs/53xhp6bn/12/" target="_blank">https://jsfiddle.net/mrubs/53xhp6bn/12/</a>

**Comment by KaelWD** [comment]
You've made a lot of mistakes there, see #3466

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by MRUBS** [comment]
can you check it again please. the main problem is, when you use birthday picker without any loop, it works like you get select the year first, then month and then the date, but when it's in a loop, you just get to select the date only, the year and month doesn't appear. i follow the reference you mention, it doesn't work like that in n loop. Please can you look into this. Thanks.

**Comment by KaelWD** [comment]
On line 15 you're still referring to picker instead of pickerN, and all the components in the loop are sharing models.

**Comment by MRUBS** [comment]
ok, i change it, doesn't show me the year first in loop. what about the sharing models, can you explain please. here is the saved link, https://jsfiddle.net/mrubs/53xhp6bn/15/

**Comment by MRUBS** [comment]
any update please ???
