### ISSUE TITLE
[Documentation Request] small information regarding v-ripple

### ISSUE THREAD

**Issue by waszqba** [vuetifyjs/vuetify#9931]
### Problem to solve
There was quite a bit of confusion regarding the sue of v-ripple in my project. I tried to use id on v-card since it natively does not show ripple on click, then I've assigned a @click listener, and it caused ripple containers to build up and not go away after a click, as there was a double ripple put on the card

### Proposed solution
To add a simple note to the ripple page regarding that many components have ripple enabled when the @click listener is used so there's no need using the directive manually when doing that

**Comment by jacekkarczmarczyk** [comment]
That sounds more like a bug, can you provide a reproduction?

**Comment by KaelWD** [comment]
#8018, #8017, I swear there was another but I can't find it

**Comment by anedosugov** [comment]
how can I **prevent** ripple from firing on **swipe** over an item (to scroll the page), and allow it to occur on purposeful tap only?

**Comment by waszqba** [comment]
Strangely enough I cannot create a simple reproduction on fiddle or codepen despite many trials and having cdn-ed the same version of vue and vuetify as in my project...

However maybe you'll be able to reproduce it locally? what I use is Vue@2.6.10 and Vuetify@2.1.11

I run it with TypeScript@3.7.2 and use 
 - babel@7.x
 - css-loader@3.2.0
 - sass@1.23.0
 - sass-loader@8
 - vue-template-compiler@2.5.21
 - vuetify-loader@1.3.0

the script is just defining some props and the template goes like this:
```vue
<template>
<v-card @click="$emit('input', option)"
        elevation="3"
        class="d-flex justify-space-between px-5 my-4"
        v-ripple><!-- and this ripple is redundant, after deletion everything works as intended -->
  <div class="radio">
    <v-radio-group :value="value" @change="$listeners.input">
      <v-radio :value="option"/>
    </v-radio-group>
  </div>
  <div class="information">
    <v-card-title>
      {{title}}
    </v-card-title>
    <v-card-subtitle>
      {{description}}
    </v-card-subtitle>
  </div>
  <div class="icon pt-3">
    <v-icon color="muted">{{icon}}</v-icon>
  </div>
</v-card>
</template>
```

I've even considered the cause being radio group having a ripple that would overlap with the card, but that made no change and sense since it is in a separate container

**Comment by MajesticPotatoe** [comment]
@waszqba we accept repositories as reproductions.

**Comment by waszqba** [comment]
I'll try to make one in the following week

**Comment by waszqba** [comment]
Sorry, I couldn't make a fresh repo to reproduce the issue and I cannot share even anonymized code from my project. I guess we have to assume this is just a bug in the way I incorporated the framework and close the issue. If I'll ever be able to recreate the issue, I'll reopen it or create a new one. For now, let's call it a day. Merry Christmas guys, keep up the good work :)
