### ISSUE TITLE
[Bug Report] V-Tab breakpoint error after migrating from 1.5.21

### ISSUE THREAD

**Issue by pokecheater** [vuetifyjs/vuetify#9932]
### Environment
**Vuetify Version:** 2.1.10
**Vue Version:** 2.6.10
**Browsers:** Other
**OS:** Windows 10

### Steps to reproduce
Always getting width not defined error, after I switched from Meteor with vuetigy version 1.5.6 to electron 2.6.10. Even your simplest code samples for v-tab are not working.

 warn]: Error in render: "TypeError: Cannot read property 'width' of undefined"

found in

---> <VTabsBar>
       <VTabs>
         <VueTableControl> at src/components/arch_editor_nodes/controls/VueTableControl.vue
           <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
Vue._render @ vue.runtime.esm.js?2b0e:3544
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
createChildren @ vue.runtime.esm.js?2b0e:6047
createElm @ vue.runtime.esm.js?2b0e:5948
patch @ vue.runtime.esm.js?2b0e:6471
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
patch @ vue.runtime.esm.js?2b0e:6471
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
init @ vue.runtime.esm.js?2b0e:3118
createComponent @ vue.runtime.esm.js?2b0e:5972
createElm @ vue.runtime.esm.js?2b0e:5919
patch @ vue.runtime.esm.js?2b0e:6510
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
createVue @ vue-render-plugin.esm.js?f261:485
createControl @ vue-render-plugin.esm.js?f261:519
(anonymous) @ vue-render-plugin.esm.js?f261:57

### Expected Behavior
It should work as before?! Even this examples are not working:
https://vuetifyjs.com/en/components/tabs

### Actual Behavior
Is not wokring

### Reproduction Link
<a href="http://codepen/thereisnolinktomyprivatepc.com" target="_blank">http://codepen/thereisnolinktomyprivatepc.com</a>

**Comment by pokecheater** [comment]
I found something out. The error comes from the following line:
![image](https://user-images.githubusercontent.com/20928617/70535351-39920200-1b5d-11ea-9e6e-be86d70c0356.png)





So if add the following lines in my root view (App.vue) 
 

mounted () {
    console.log("mounted: this.$vuetify.breakpoint", this.$vuetify.breakpoint);
  },

the breakpoint attribute is initialized. 
![image](https://user-images.githubusercontent.com/20928617/70535444-66461980-1b5d-11ea-9072-d7e52ddddf8b.png)

But if I do so in a sub component the same leads to undefined.
![image](https://user-images.githubusercontent.com/20928617/70535485-74943580-1b5d-11ea-82e8-4aa7867c0183.png)

**Comment by MajesticPotatoe** [comment]
You've submitted an issue that does not contain a reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment. This issue will be tagged as `needs reproduction` for the next 14 days before being closed.

Services to create a reproduction:

- [Codepen](https://template.vuetifyjs.com)
- [Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)
- [Codesandbox](https://codesandbox.io)
- [JSFiddle](https://jsfiddle.net/)
- A small reproduction repository

Thank you for your contribution and interest in improving Vuetify.

**Comment by pokecheater** [comment]
Great... 
just forget ist we set the value now by hand in our component.
Just for letting you know it seems that a lot of people facing this issue and they are all unresolved:

![image](https://user-images.githubusercontent.com/20928617/70536116-77dbf100-1b5e-11ea-935b-72d1aaffed5d.png)

I think my comment should exactly describe where the error comes from.

**Comment by KaelWD** [comment]
> I think my comment should exactly describe where the error comes from

It does, but doesn't explain why it's undefined. Every time I've seen that error it's been a misconfigured project.

**Comment by pokecheater** [comment]
Okay that is a hint, are there common mistakes that leads to this behavior?
I do not understand why it works on in the App.vue but not inside any other sub component.
Inside the old vue version this wasn't a problem.

**Comment by KaelWD** [comment]
https://stackoverflow.com/a/56915785
https://stackoverflow.com/a/57019427

or #4068 if you've got some really weird build setup

**Comment by pokecheater** [comment]
Okay I will check theese, Thx :)

**Comment by MajesticPotatoe** [comment]
given you are upgrading from 1.5 to 2.x you should also take a glance at the [Migration Guide](https://vuetifyjs.com/en/getting-started/releases-and-migrations#migration-guide). Bootstrapping was changed between these versions which points to the direction of the 2 stackoverflows that kael posted.

**Comment by KaelWD** [comment]
There's a good chance you even have this:
![image](https://user-images.githubusercontent.com/16421948/70538446-31b27c00-1bb6-11ea-8a4d-61d835fc6e72.png)

**Comment by pokecheater** [comment]
@KaelWD  I do not have this issue: 
![image](https://user-images.githubusercontent.com/20928617/70538986-474a8600-1b63-11ea-8b99-7d74dfcb8974.png)


This is my vuetify initialization (looks very similar to the auto generated one from vue-cli):
![image](https://user-images.githubusercontent.com/20928617/70539132-8a0c5e00-1b63-11ea-9a05-6574e9b03c08.png)

**Comment by pokecheater** [comment]
@MajesticPotatoe I will double check the migration guide

**Comment by pokecheater** [comment]
sry, accidently closed the issue by rapid clicking

**Comment by pokecheater** [comment]
Okay double checked it nothing showy... But I found out something really intresting:

All my components that are loaded via the router have access to the breakpoint property. All sub components that are loaded and mounted via the <component> element do not have access. 
Let me show inside the browser-log (highlighted the relevant lines for you). 

The first mounted line comes from App.vue 
The next two highlited lines comes from my Project.vue  (vuetify.breakpoint is accessible)
The last one comes from a subcomponent that is loaded via component tag. (vuetify.breakpoint is not accessible)



![image](https://user-images.githubusercontent.com/20928617/70540831-38b19e00-1b66-11ea-953f-8eae001cdfc1.png)

**Comment by pokecheater** [comment]
Hey folks, we solved it by a workaround. 

Just as hint for others who are facing this issue. Inside the affected subcomponents we added a property named vuetify_ref. When we instantiate the sub component we give this property a reference to the this.§vuetify value of the parent component. Than inside the created() method we switch the $vuetify value of the sub component with the vuetify_ref property and voiala everything works again :).

just a little code snippets to clearify it:

**in parent component:** 
available_layer.component.vuetify_ref = this.$vuetify;

**in sub component:**
export default {
    props: ["type", "readonly", "emitter", "ikey", "**vuetify_ref**"],
    data() {
...

created() {
      **this.$vuetify = this.$props.vuetify_ref;**
    }
...

(Note that there is a wrapper class in between those both components, which sets the property of vuetify_ref

export default class IconNameControl extends Rete.Control {
    constructor(emitter, vuetify_ref, key, readonly, type) {
        super(key);
        this.component = VueIconNameControl;
        **this.props = {emitter, ikey: key, readonly, type, vuetify_ref};**
    }


I still have no clue why this problem occured after we swichted from vuetify 1.5.6 to 2.1.0, but if I should make a guess I think maybe the vuetify value was never setted correctly but in the newer version of vuetify it is suddenly needed by the tab component.

I want to say thank you to everyone who supported and answered us so fast.  I really appreciate that :). Special thx to @MajesticPotatoe and @KaelWD. And thank you to the whole vuetify team for this awesome framework :). Merry Christmas.

**Comment by KaelWD** [comment]
Are you doing some weird shit like `new IconNameControl().$mount('element')`?

**Comment by pokecheater** [comment]
No, I scanned the whole project. The only $mount comes from App.vue.

vue.$mount('#app');

But inside our node_modules there appear some of them. Especially Retejs seems to mount each node by it's on with    app.$mount(nodeEl);.

Is that's the cause?

**Comment by KaelWD** [comment]
Yeah, we use `this.$parent` to set `$vuetify`. IDK how rete is creating components but you can either pass the vuetify instance in (`new SomeComponent({ vuetify })`) or set the parent (`new SomeComponent({ parent: someOtherComponentInstance }`).
