### ISSUE TITLE
[Feature Request] Button: an affirmative button

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuetifyjs/vuetify#9934]
### Problem to solve
Imagine a button which saves something. While saving you add the loading prop so your users have a great experience. Except when the saving happens really quick the user doesn't get a confirmation that i's saved.

### Proposed solution
A new button type or prop which has the following result.
You click on the button and the loading icon appears. This loading icon is always at least 500ms visible. When the saving is succeeded an icon with a check appears.

This is what i currently use: https://gist.github.com/ricardovanlaarhoven/ac71077104502d4a12b882e7e8a95694

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by SoftWebMike** [comment]
> ### Problem to solve
> Imagine a button which saves something. While saving you add the loading prop so your users have a great experience. Except when the saving happens really quick the user doesn't get a confirmation that i's saved.
> 
> ### Proposed solution
> A new button type or prop which has the following result.
> You click on the button and the loading icon appears. This loading icon is always at least 500ms visible. When the saving is succeeded an icon with a check appears.
> 
> This is what i currently use: https://gist.github.com/ricardovanlaarhoven/ac71077104502d4a12b882e7e8a95694

Thank you for your code sample - it was exactly what I was looking for!
