### ISSUE TITLE
[Bug Report] V-Slider convert null to min value

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify#9935]
### Environment
**Vuetify Version:** 2.1.5
**Vue Version:** 2.6.10
**Browsers:** Chrome 80.0.3983.2
**OS:** Windows 10

### Steps to reproduce
Set value in slider

Click X to unset the value

### Expected Behavior
Put slider in the min value and return `null || undefined`

### Actual Behavior
Put slider in the min value and return `0`

### Reproduction Link
<a href="https://codepen.io/joel_rodrigues/pen/ZEYWQZp" target="_blank">https://codepen.io/joel_rodrigues/pen/ZEYWQZp</a>

**Comment by KaelWD** [comment]
Related to #4746
