### ISSUE TITLE
[Bug Report] v-expand-transition and v-expand-x-transition not showing transition

### ISSUE THREAD

**Issue by odellcraig** [vuetifyjs/vuetify#9938]
### Environment
**Vuetify Version:** 2.1.13
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Linux x86_64

### Steps to reproduce
This is actually a direct fork of the existing codepen from https://vuetifyjs.com/en/styles/transitions. If you open the attached codepen or the one from the documentation, you will see that the expand transitions are not working. 

### Expected Behavior
Expect the div to grow/shrink with a transition.

### Actual Behavior
Div appears suddenly without growing/shrinking

### Reproduction Link
<a href="https://codepen.io/odellcraig/pen/povybva" target="_blank">https://codepen.io/odellcraig/pen/povybva</a>

### Other comments
May be unrelated, but I've been using v-expand-transition serving from the vue cli in dev-mode and the animation works as expected, but after building the source and deploying the transition stops working.

**Comment by KaelWD** [comment]
This is another CSS ordering bug, it works if you use vuetify.css instead of vuetify.min.css in the codepen.

**Comment by CodeSkills** [comment]
Confirmed and still not working in 2.2.4. Tried both minified and not minified version and it does not work.

**Comment by anzuj** [comment]
Experiencing the same thing when trying to toggle a child component like so: 
```
  <v-expand-transition>
        <Task v-show="showTask"/>
     </v-expand-transition>
```

**Comment by vladimirtemnikov** [comment]
Any workarounds while using `vuetify-loader`?
