### ISSUE TITLE
[Feature Request] Prop for date - Change background color

### ISSUE THREAD

**Issue by yogeshkudikala** [vuetifyjs/vuetify#9941]
### Problem to solve
We want to display attendance status of employee using calendar-monthly component. So the background color on each date would help them to keep a track on their attendance 

### Proposed solution
Option to change background color of date in calendar.

**Comment by johnleider** [comment]
Thank you for the Feature Request and interest in improving Vuetify. After careful consideration the team has decided that this is not functionality that we are looking to implement at this time.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
