### ISSUE TITLE
[Bug Report] v-list-item-icon and v-list-item-content are misaligned when the icons are different

### ISSUE THREAD

**Issue by skymaze** [vuetifyjs/vuetify#9942]
### Environment
**Vuetify Version:** 2.1.12
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Linux x86_64

### Steps to reproduce
See reproduction link. Use different icons with different width.

### Expected Behavior
v-list-item-icon and v-list-item-content should be aligned

### Actual Behavior
misaligned

### Reproduction Link
<a href="https://codepen.io/skymaze/pen/WNbwzxE" target="_blank">https://codepen.io/skymaze/pen/WNbwzxE</a>

### Other comments
Can be aligned by add "width:24px" to v-icon.

**Comment by Ltyi** [comment]
This usually happens when using font-awesome icons
use 'fa-fw' to fixed the width
[fa-fw](https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons)

that is work for me

**Comment by ricardovanlaarhoven** [comment]
Is it an idea to add this fa-fw on all font-awesome icons?
i could try to make a PR

**Comment by mttmccb** [comment]
Using `fa-fw` didn't work for me 100%, I have had to fix the width of the icon. Bit of a weird one, it was fine for most icons in the list i.e. those that ended up as links but not for those that were divs, couldn't see an obvious reason why. I am using a navigation drawer and it's only when it's expanded there is an issue.

**Comment by ricardovanlaarhoven** [comment]
Could you make a codepen, as an example?

**Comment by mttmccb** [comment]
Yep, here's an example, you'll see the plus icon is small than the others and misaligned for the open menu, it's fine on the mini variant.

https://codepen.io/mttmccb-the-bashful/pen/gOMzjqB
