### ISSUE TITLE
[Feature Request] VOverflowBtn option combobox

### ISSUE THREAD

**Issue by BaptisteCool** [vuetifyjs/vuetify#9945]
### Problem to solve
Add the possibility of the 'VOverflowBtn' in editable mode to add new item like the 'VCombobox' component.

### Proposed solution
new prop 'combo' => add new item in the 'items' list.

It's just an idea to simplify some design system with unique component for display a select/autocomplete/combobox.

**Comment by KaelWD** [comment]
That's what editable is supposed to do, it appears to be broken.
