### ISSUE TITLE
[Feature Request] Add isOpen on group.header slot properties

### ISSUE THREAD

**Issue by SkyaTura** [vuetifyjs/vuetify#9947]
### Problem to solve
Is not possible to determine whether the group is open or not when using the "group.header" slot to customize the default appearance.

### Proposed solution
Add the variable "isOpen" to the slot context.

**Comment by hjJunior** [comment]
I'd like to work on it, can I?

**Comment by SkyaTura** [comment]
Sorry @hjJunior , I already did it 🙈

**Comment by hjJunior** [comment]
Hahaa no probs :D

**Comment by Daanra** [comment]
Closed by https://github.com/vuetifyjs/vuetify/pull/9721

**Comment by SkyaTura** [comment]
Thank you

**Comment by jacekkarczmarczyk** [comment]
???

**Comment by SkyaTura** [comment]
@jacekkarczmarczyk ?

**Comment by jacekkarczmarczyk** [comment]
Nvm, confused with 2 PRs, ignore me
