### ISSUE TITLE
[Bug Report] Bug Date Picker Without Buttons Validation Rules

### ISSUE THREAD

**Issue by lucasrusso95** [vuetifyjs/vuetify#9948]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97, Firefox 60
**OS:** Linux x86_64

### Steps to reproduce
When you select the date, the error appears for a moment first time. After disappears.

It's with rules prop on v-text-field

### Expected Behavior
I expect that dont appear error

### Actual Behavior
Appearing error for a moment bug.

### Reproduction Link
<a href="https://codepen.io/lucasrusso/pen/oNgxJNz" target="_blank">https://codepen.io/lucasrusso/pen/oNgxJNz</a>

**Comment by roblugt** [comment]
I have the same issue.  We also see a permanent error message when using the date picker forward/back buttons to page through the dates.  I think the ideal solution for us is if the v-text-field validation does not kick-in while the DatePicker is open.

I have modified the codepen from @lucasrusso95 to remove rules while the menu is open, but I don't think this is the idea solution. https://codepen.io/rlguildford/pen/bGNBjoV

I think a better solution is for the v-text-field control to behave as if it continues to have the focus for the duration that the DatePicker is open (if this is possible).  This would also improve the behavior of the v-text-field label.

**Comment by Lisible** [comment]
Encountering the same issue, the workaround of removing rules temporarily is not really a viable solution since my form enables the submission button based on the form's v-model.

**Comment by mewtlu** [comment]
For anybody still facing this issue, I've finally managed to resolve it nicely by setting `disabled` on the v-text-field to the value of the v-model for the menu, and adding a watcher on the menu v-model which runs `.validate(true)` (seems to require the `force` parameter to be true) on a ref for the v-text-field when the value is false (menu is closed), ensuring the validation is still triggered on close of the menu.
