### ISSUE TITLE
[Bug Report] VPagination component is in tests not correctly rendered

### ISSUE THREAD

**Issue by dsvanidze** [vuetifyjs/vuetify#9949]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Mac OS 10.15.1

### Steps to reproduce
Look in reproduction Link

### Expected Behavior
```html
<ul class="v-pagination theme--light">
  <li><button type="button" class="v-pagination__navigation v-pagination__navigation--disabled">
    <i aria-hidden="true" class="v-icon notranslate mdi mdi-chevron-left theme--light">
    </i>
    </button>
  </li>
  <li><button type="button" class="v-pagination__item v-pagination__item--active primary">1</button></li>
  <li><button type="button" class="v-pagination__item">2</button></li>
  <li><button type="button" class="v-pagination__item">3</button></li>
  <li><button type="button" class="v-pagination__navigation">
    <i aria-hidden="true" class="v-icon notranslate mdi mdi-chevron-right theme--light">
    </i>
    </button>
  </li>
</ul>
```

### Actual Behavior
```html
<ul class="v-pagination theme--light">
  <li><button type="button" class="v-pagination__navigation v-pagination__navigation--disabled">
    <i aria-hidden="true" class="v-icon notranslate material-icons theme--light">
      $vuetify.icons.prev
    </i>
    </button>
  </li>
  <li><button type="button" class="v-pagination__item v-pagination__item--active primary">1</button></li>
  <li><span class="v-pagination__more">...</span></li>
  <li><span class="v-pagination__more">...</span></li>
  <li><button type="button" class="v-pagination__item">3</button></li>
  <li><button type="button" class="v-pagination__navigation">
    <i aria-hidden="true" class="v-icon notranslate material-icons theme--light">
      $vuetify.icons.next
    </i>
    </button>
  </li>
</ul>
```

### Reproduction Link
<a href="https://jsfiddle.net/fovcguL0/" target="_blank">https://jsfiddle.net/fovcguL0/</a>

### Other comments
I tried everything to render VPagination correctly: jest timers, await wrapper.vm.$nextTick(), await flushPromises() and also looked in the VPagination tests of vuetify self. Unfortunately, nothing has worked. I cannot give

**Comment by johnleider** [comment]
`v-pagination` uses the DOM to calculate what it can show. This will not work in JSDOM. In your test you can just overwrite the onResize method to return whatever values you want:

```
const wrapper = mount(VPagination, {
  methods: {
    onResize () { this.maxButtons = 20 }
}
```

This is where it is defined: https://github.com/vuetifyjs/vuetify/blob/1394b6c24b006596c49375d808210264fa9920ae/packages/vuetify/src/components/VPagination/VPagination.ts#L118

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by dsvanidze** [comment]
@johnleider Thank you. I asked on Discord, but I think, it helps others too if you answer here. How would you solve this problem if a VPagination component is deeply nested in a complex component. So, I cannot use anymore your solution. I tried to use .setMethods() on wrapper.find(".v-pagination").vm, but it does not have setMethods().
