### ISSUE TITLE
Once selected a value on autocomplete, you can't erase to type/search again

### ISSUE THREAD

**Issue by evaldobratti** [vuetifyjs/vuetify#995]
### Steps to reproduce
https://codepen.io/anon/pen/LLaBMd?editors=1010
1. type 'aabb' in the autocomplete
2. select a value 'aabbbb' or 'aabbcc'
3. once selected, focus the component again, and you can see the cursor blinking, you can type more characters, but you can't change the text of the value, I mean, you can't backspace/delete and search another value

https://vuetifyjs.com/components/selects
in the autocomplete example
search with 'ala' and select 'Alaska', then, try to backspace the end, 'ska', to filter and select 'Alabama'.

### Versions
0.13

### What is expected ?
On autocomplete, you should be able to erase the selected value and type to search for another.

### What is actually happening ?
You can only add more characters in the current select text, you can't erase.

### Reproduction Link
https://codepen.io/anon/pen/LLaBMd?editors=1010
you can reproduce it in docs in the autocomplete section
https://vuetifyjs.com/components/selects

**Comment by Fl0pZz** [comment]
I note that the select with the `editable` property of such a problem is not present

**Comment by evaldobratti** [comment]
adding `editable` kind of works,  but it changes the [component design](http://i.imgur.com/UI9klZW.png) and `item-text` and `item-value`  [gets messy](http://i.imgur.com/WMxvJnj.png)
my component is declared as follows
```
<v-select
          label="Categoria"
          :items="categorias"
          v-model="categoria"
          item-text="nome"
          item-value="id"
          autocomplete>
</v-select>
```

**Comment by johnleider** [comment]
You can still filter your selection and select another. What this issue tells me is that's not the expected behavior. Going to try and improve that.

**Comment by johnleider** [comment]
Updating this scenario hide the selections when using an autocomplete/editable non-multi select.

**Comment by Fl0pZz** [comment]
No, I believe that this is an incorrect fix error! It is necessary not to hide and make it editable!
![screenshot_20170716_100636](https://user-images.githubusercontent.com/9510124/28245404-86563a96-6a0e-11e7-86fd-805bf55c2b44.png)

**Comment by Piterden** [comment]
What is the value of v-model, when you'd hide it?
@johnleider

**Comment by johnleider** [comment]
It's the same? The search value is separate and internal.

**Comment by evaldobratti** [comment]
You can continue to filter, indeed, but it seems strange

![image](https://user-images.githubusercontent.com/1869525/28248722-7f63a762-6a1f-11e7-9a67-61a5cc628556.png)
I initially select California, but then I want to change and filter states with 'ala', then the input text gets 'California ala'. I think enabling the user to erase 'California' (then v-model would be null, or the filter text, maybe), and then type the next filter, would be better.
