### ISSUE TITLE
[Bug Report] VTextField old value appears again as prefix of new input after clicking on clearing button

### ISSUE THREAD

**Issue by Xiut** [vuetifyjs/vuetify#9952]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Android

### Steps to reproduce
1. use the default Samsung keyboard in version 2.1.03.7, but other keyboards might be affected as well
2. write "test" into the VTextField
3. press the button to clear the field or clear the variable which is bound to the VTextField via v-model 
4. the VTextField is empty
5. write "x" into the VTextField

### Expected Behavior
The VTextField should only contain an "x".

### Actual Behavior
The VTextField contains "testx" (the old content appears before the new input)

### Reproduction Link
<a href="https://jsfiddle.net/7j1shmed/1/" target="_blank">https://jsfiddle.net/7j1shmed/1/</a>

### Other comments
Interestingly, this error does not occur when the focus leaves the field after the field has been cleared and before you have written something again and then you focus the field again to write something. Then the old input no longer appears before the new one and only the new input is displayed.

In my opinion, it can't only be due to the keyboard, because this error does not occur with a simple input element and the error can be fixed by forcing a rerender of the VTextField after emptying the content.

**Comment by KaelWD** [comment]
Doesn't happen with gboard on miui 10.2

**Comment by KaelWD** [comment]
@Xiut can you please do it in https://codepen.io/kaelwd/pen/eYmzzKQ?editors=1111 and show the console output, and try with a different keyboard too.

**Comment by Xiut** [comment]
@KaelWD 
With Samsung Keyboard:
"input" "t"
"input" "te"
"input" "tes"
"input" "test"
"input" null
"input" "testx"

With gboard:
"input" "t"
"input" "te"
"input" "tes"
"input" "test"
"input" null
"input" "x"

With Samsung keyboard and an simple input element instead of a VTextField with clearing on click (so it does not lose focus):
"input" "t"
"input" "te"
"input" "tes"
"input" "test"
"input" null
"input" "x"

**Comment by KaelWD** [comment]
ok so it's the keyboard then. how are you clearing the basic input?

**Comment by Xiut** [comment]
@KaelWD  By setting the value of the with v-model binded variable in the @click to null. 

Correction: At the basic input element its "undefined" and not "null" in the console, because I log there at the events "e.data" and not just e. In case that makes a difference.

**Comment by KaelWD** [comment]
On click of what, the input itself?

**Comment by Xiut** [comment]
Yes, the click event of the input

**Comment by Xiut** [comment]
Maybe this helps: https://jsfiddle.net/wrntocL2/3/ 

Above the simple input element and below the VTextField componente. For me it looks the same in both cases, as far as emptying the input and binding the variable is concerned. 

With the input element the error does not occur, with the VTextField it does.

If I didn't miss anything, the VTextField component should be responsible for the error, shouldn't it? 

Probably the error only occurs with the Samsung keyboard or with very few keyboards, but since I can't estimate it, I thought I'd better report it once.

**Comment by KaelWD** [comment]
I can't install the samsung keyboard on my phone so I can't really debug this.

**Comment by johnleider** [comment]
This Pull Request is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
