### ISSUE TITLE
[Feature Request] Vuetify - autocomplete with multiple

### ISSUE THREAD

**Issue by nardevil** [vuetifyjs/vuetify#9954]
### Problem to solve
It would be great if there was a functionality when writing some text in the v-autocomplete (after it filters the options based on the input text) and on key press "enter" to select all filtered options. It is a nuisance to select them one by one

### Proposed solution
When clicking on "enter" get all filtered options and send them to the model.

**Comment by johnleider** [comment]
Here is an example of how to do that: https://vuetifyjs.com/en/components/selects#prepend-append-item-slots

It's on `v-select` but the same process applies.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
