### ISSUE TITLE
[Bug Report] Vuetify Calender Component not loading Events 

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#9955]
### Environment
**Vuetify Version:** 2.2.0-beta.1
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Not working with ISO Date

### Expected Behavior
It should display events provided in events array------  Date is in ISO format (mongoose database) however it expects date in YYYY-MM-DD HH:MM format.Is there any prop for the same so as to provide event start and end in different time format.

### Actual Behavior
Accepts date in YYYY-MM-DD HH:MM format only

### Reproduction Link
<a href="https://codepen.io/spider007/pen/RwNwvzM" target="_blank">https://codepen.io/spider007/pen/RwNwvzM</a>

**Comment by kunalahirrao** [comment]
Calender needs date in YYYY-MM-DD format but the response from database is in ISODate .Do i need to store response first and then make a event array with formatted date

**Comment by ClickerMonkey** [comment]
A prop could be added where the user provides a function to a prop which returns a string in a properly formatted structure or an object in a certain format.

Maybe `event-start-parser` and `event-end-parser` that gets passed an event object and expects a string or simplified VTimestamp object.

And/or we add `date-parser` which is used for all dates passed to a calendar (value, start, end, event start & end).

@kunalahirrao would these enhancements satisfy your needs?

**Comment by kunalahirrao** [comment]
Yes. Can we add support directly for ISO Date as Mongodb stores date ISO format.it will solve problem of conversion of dates and will make calender more efficient

**Comment by kunalahirrao** [comment]
It will allow user to directly  pass events without mutating/creating sepaeate event array

**Comment by kunalahirrao** [comment]
Passes events in "ISO Date HH:mm " format solved the issue.
