### ISSUE TITLE
[Bug Report] DataTable loads data twice in Paginate and sort server-side Example

### ISSUE THREAD

**Issue by knunery** [vuetifyjs/vuetify#9959]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 10

### Steps to reproduce
I added some console.log statements to the CodePen for the https://vuetifyjs.com/en/components/data-tables#paginate-and-sort-server-side sample. In the console you will see 
"mounted"
"getDataFromApi"
"handler"
"getDataFromApi".

### Expected Behavior
getDataFromApi should only be called once.

### Actual Behavior
getDataFromApi  is called twice.

### Reproduction Link
<a href="https://codepen.io/knunery/pen/WNbxgry?editors=1011" target="_blank">https://codepen.io/knunery/pen/WNbxgry?editors=1011</a>

**Comment by knunery** [comment]
Maybe the mounted code isn't really needed?

**Comment by Leespiker** [comment]
@knunery Your [reproduction](https://codepen.io/knunery/pen/WNbxgry) works fine for me now. Can you post a new one if it's still not working properly for you?

**Comment by jacekkarczmarczyk** [comment]
I can reproduce it in codepen, but not in playground

**Comment by johnleider** [comment]
From what I can see, this works as expected in the codepen:

![image](https://user-images.githubusercontent.com/9064066/84061424-81b2a580-a983-11ea-97ad-fdec5d8668fb.png)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
