### ISSUE TITLE
v-select :readonly bug

### ISSUE THREAD

**Issue by TheGinJiCode** [vuetifyjs/vuetify#996]
I have a bug in readonly in v-select. So i use :disabled instead :D

![image](https://user-images.githubusercontent.com/29909936/28236354-fcde5a4e-6956-11e7-954b-1a1154fe45b9.png)

![image](https://user-images.githubusercontent.com/29909936/28236357-13f9ef36-6957-11e7-9b08-abbd81b10ed6.png)

**Comment by nekosaur** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for us to properly address your issue. Please reopen this with the required information, including a codepen that reproduces the problem. Thank you.

**Comment by TheGinJiCode** [comment]
Sorry. Here is my codepen.
https://codepen.io/TheGinJiCode/pen/YQgdwB

**Comment by johnleider** [comment]
I don't want to undermine neko reopening this, but I firmly stick by when creating issues, you should follow the exact boilerplate given. Disregarding that simply should not be accepted, sorry. 

Please edit your issue with the provide boilerplate, or create a new issue, thank you.

**Comment by paganaye** [comment]
I firmly find this attitude rude.

**Comment by johnleider** [comment]
And that's okay, you don't have to agree. Please do not post arbitrarily on old tickets.
