### ISSUE TITLE
[Feature Request] Is there a shorter/cleaner way to access App.js than $root.$children[0] ?

### ISSUE THREAD

**Issue by sve-odoo** [vuetifyjs/vuetify#9964]
### Problem to solve
When you are in a special case where you need to access your root component instance, it looks like vuetify creates a root component above your own root component (App.vue), so what I found out to work was $root.$children[0] .
It seems to work well but is there another solution?

### Proposed solution
Maybe $vuetify.app ?

**Comment by KaelWD** [comment]
Vuetify doesn't do anything of the sort, that sounds like a vue question. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
