### ISSUE TITLE
[Bug Report] Incorrect vertical alignment of VCheckbox in table

### ISSUE THREAD

**Issue by ems1985** [vuetifyjs/vuetify#9965]
### Environment
**Vuetify Version:** 2.1.14
**Last working version:** 1.5.17
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 7

### Steps to reproduce
Put a VCheckbox with "hide-details" inside a TD element

### Expected Behavior
Checkbox is vertically centered, just like other text/elements

![image](https://user-images.githubusercontent.com/34405275/70793889-ae9f4a80-1d9c-11ea-8fbb-7360fb4d36cc.png)

### Actual Behavior
Checkbox appears at bottom of the TD

![image](https://user-images.githubusercontent.com/34405275/70791835-2e76e600-1d98-11ea-9275-fd00b6f01c49.png)

### Reproduction Link
<a href="https://codepen.io/esdlc/pen/LYEZojQ?&editable=true" target="_blank">https://codepen.io/esdlc/pen/LYEZojQ?&editable=true</a>

### Other comments
When you use a VSimpleCheckbox instead, it shows how it is supposed to look.

You can also fix it by adding "pa-0 ma-0" classes

**Comment by myleslee** [comment]
You can use `<v-simple-checkbox  class="red" />` to get the desired results. But you need to handle the `select` event.

<img width="242" alt="Screen Shot 2019-12-14 at 08 33 25" src="https://user-images.githubusercontent.com/108758/70840324-7eaf8000-1e4c-11ea-808a-8396e3cce116.png">

**Comment by johnleider** [comment]
We should either document `v-simple-checkbox` and specify it as what the dev should use in `v-data-table`. Otherwise we should apply the same style reset to `v-checkbox`. Ultimately up to you @nekosaur

**Comment by nekosaur** [comment]
v-simple-checkbox should be what is used. the documentation issue is tracked in https://github.com/vuetifyjs/vuetify/issues/8469 already.
