### ISSUE TITLE
[Feature Request] Replicate HTML Select hotkeys 

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetify#9967]
### Problem to solve
In a vanilla html select input, once the input is focused, we can access the different options by typing the first letters of an option. 

This **ONLY** highlight the option and not actually selected it (input's value is not changed). To actually select it we must then hit ENTER (or hit ESCAPE to go back).

In Vuetify v1 AND v2, whenever we type something, the value is selected (the input's value is modified before we hit ENTER.). This should not be the case.

https://codepen.io/smcolburn/pen/zLbXOy?editors=1010

### Proposed solution
`<v-select>` should emulate standard HTML inputs in this regard.

**Comment by johnleider** [comment]
As far as I can see, that is not how a vanilla html select works: https://codepen.io/johnjleider/pen/xxbJPYO

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ThomasKientz** [comment]
@johnleider With a vanilla select, you can highlight an option with the keyboard, then press ESCAPE. The value is discarded. Is not it ?

![out](https://user-images.githubusercontent.com/10157845/72423322-589b3980-3784-11ea-9308-e53cf91ed401.gif)

PS- I am using Chrome 79 on macOS 10.15.1

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/72426129-48637880-37dd-11ea-89cb-d134698780c4.png)
