### ISSUE TITLE
[Bug Report] v-banner does not display correctly when used with v-app-bar app/fixed props

### ISSUE THREAD

**Issue by r3d4rmy** [vuetifyjs/vuetify#9969]
### Environment
**Vuetify Version:** 2.1.14
**Last working version:** 2.1.13
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 10

### Steps to reproduce
1. Create a v-app-bar and use the app/fixed props
2. Create a v-banner underneath the v-app-bar

### Expected Behavior
The v-banner will be underneath the v-app-bar

### Actual Behavior
The v-banner is behind the v-app-bar

### Reproduction Link
<a href="https://codepen.io/R3d4rmy/pen/xxbERzP" target="_blank">https://codepen.io/R3d4rmy/pen/xxbERzP</a>

### Other comments
This worked in Vuetify 2.1.13

**Comment by dos077** [comment]
v-app-bar needs to work in tandem with v-content for app spacing to work correctly. Wrap the banner inside v-content tag and it will show correctly.

**Comment by johnleider** [comment]
This issue is resolved by https://github.com/vuetifyjs/vuetify/issues/9969#issuecomment-566342441

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
