### ISSUE TITLE
[Bug Report] justify-self not working in v-col

### ISSUE THREAD

**Issue by GorillaWarHead** [vuetifyjs/vuetify#9970]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.79
**OS:** Windows 10

### Steps to reproduce
 <v-row class="mb-6" justify="space-around"  align="center">
        <v-col  v-for="n in 4" :key="n" justify-self="center">
           <v-card width="100px" class="pa-2" tile outlined>
          col-{{ n === 1 ? 8 : 4 }}
        </v-card>
        </v-col>
      </v-row>

### Expected Behavior
v-col with justify-self most be justified to given option (center, end ...)

### Actual Behavior
v-col with justify-self doesn't do nothing 

### Reproduction Link
<a href="https://codepen.io/ThugMa/pen/mdyrRMd?&editable=true&editors=101" target="_blank">https://codepen.io/ThugMa/pen/mdyrRMd?&editable=true&editors=101</a>

### Other comments
i work arouned it by adding another v-row with justify options inside v-col

**Comment by KaelWD** [comment]
@sh7dm Adding a prop doesn't do anything if the class doesn't exist 1ba5f829cb727452343abc7db03b440da78a6357

**Comment by KaelWD** [comment]
#8883

> The old `v-flex` component had `justify-self` available. `v-col` doesn't have one.

No it didn't, and `justify-self` [is ignored in flexbox anyway](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self)

> In flexbox layouts, this property is *ignored*
