### ISSUE TITLE
[Bug Report] Fab v-btn still retains focus after click by default

### ISSUE THREAD

**Issue by milost1982** [vuetifyjs/vuetify#9972]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Use fab prop on v-btn component and click it.

### Expected Behavior
It should not retain focus on click just like other v-btn types.
Also setting property retain-focus-on-click="false" doesn't work.

### Actual Behavior
It retains focus after click.

### Reproduction Link
<a href="https://codepen.io/milost1982/pen/YzPGQpb?&editable=true&editors=101" target="_blank">https://codepen.io/milost1982/pen/YzPGQpb?&editable=true&editors=101</a>

**Comment by SuhwanCha** [comment]
I think it's intended

https://github.com/vuetifyjs/vuetify/blob/v2.2.0-beta.0/packages/vuetify/src/components/VBtn/VBtn.ts#L155

```ts
    click (e: MouseEvent): void {
      !this.retainFocusOnClick && !this.fab && e.detail && this.$el.blur()
      this.$emit('click', e)

      this.btnToggle && this.toggle()
    },
```

**Comment by SuhwanCha** [comment]
Isn't it intended?

https://github.com/vuetifyjs/vuetify/blob/v2.2.0-beta.0/packages/vuetify/src/components/VBtn/VBtn.ts


```ts
    click (e: MouseEvent): void {
      !this.retainFocusOnClick && !this.fab && e.detail && this.$el.blur()
      this.$emit('click', e)

      this.btnToggle && this.toggle()
    },
```

**Comment by johnleider** [comment]
This is not a bug.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by milost1982** [comment]
I tried asking on discord but didn't get the answer, so I will ask here:
Does  "retain-focus-on-click" prop works on "fab" buttons?
If I set: **retain-focus-on-click="false"** nothing seems to change and focus is still retained after click.

**Comment by michaelsogos** [comment]
Dear @johnleider 

I exactly same issue, this is my button:
```
<v-btn
    color="secondary"
    :style="{'z-index': '10000', left: '50%', bottom: '-25px', transform:'translateX(-50%)'}"
    dark
    absolute
    fab
    retain-focus-on-click
    @click="onAddCartItem">
    <v-icon>mdi-plus</v-icon>
</v-btn>
```

Once clicked on button it stay focused.

**Comment by sugoidesune** [comment]
> Dear @johnleider
> 
> I have exactly same issue, this is my button:
> 
> ```
> <v-btn
>     color="secondary"
>     :style="{'z-index': '10000', left: '50%', bottom: '-25px', transform:'translateX(-50%)'}"
>     dark
>     absolute
>     fab
>     **retain-focus-on-click**
>     @click="onAddCartItem">
>     <v-icon>mdi-plus</v-icon>
> </v-btn>
> ```
> 
> Once clicked on button it stay focused.

you have the flag retain-focus-on-click
Youre telling the button to retain it = keep focus

**Comment by sugoidesune** [comment]
I have the same problem.
NOT a fab button, but focus gets retained and i set
`:retain-focus-on-click="false"`
just to make sure.

**Comment by justinforlenza** [comment]
Same as @milost1982 I have a fab button that is still retaining focus after click, even if explicitly putting `:retain-focus-on-click="false"`.

**Comment by TaeyoonKwon** [comment]
`retain-focus-on-click` does not work.

Instead, you can solve this issue by adding this to global style.

```
@media screen and (max-device-width: 768px) {
  .v-btn:hover:before {
    opacity: 0 !important;
  }
}
```

Media query is needed because if not, it will remove hover effects on Desktop view.

**Comment by bryanvaz** [comment]
Since the issue is caused by the `@click` handler, I added the following code to the end of the event that fires in order to clear the focus (note, you can use $refs if you want to be more specific):
```JS
if (document.activeElement instanceof HTMLElement) document.activeElement.blur();
```

_Note that this aspect of `blur` is not documented and may change, if you want to super safe, you can programatically change focus to a known element that will have to impact on the UI (such as a line of text or an invisible pixel)_
