### ISSUE TITLE
[Feature Request] Convert CSS classes with IdnetName

### ISSUE THREAD

**Issue by KareemDa** [vuetifyjs/vuetify#9973]
### Problem to solve
reduce html size instead of loading huge class names such as this image

![image](https://user-images.githubusercontent.com/42810389/70847480-a105c580-1e6d-11ea-9e82-9bf451884814.png)

### Proposed solution
use css modules to make short identName of classes

**Comment by KaelWD** [comment]
Not really an option, this would be a big breaking change for people overriding CSS. Long classnames gzip just as well as short ones so there's no real benefit to this either.
