### ISSUE TITLE
[Bug Report] Form input rules fail only when string is returned

### ISSUE THREAD

**Issue by ThewBear** [vuetifyjs/vuetify#9976]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.11
**Browsers:** Google Chrome
**OS:** Windows

### Steps to reproduce
Returns `false` from rule function

### Expected Behavior
Form validation should be failed when rule function returns false as documented in https://vuetifyjs.com/en/components/forms
> If a function returns false or a string, validation has failed.

### Actual Behavior
Validation passed

### Reproduction Link
<a href="https://codepen.io/ThewBear/pen/abzBoXy" target="_blank">https://codepen.io/ThewBear/pen/abzBoXy</a>

**Comment by jacekkarczmarczyk** [comment]
You didn't apply rules to the second form

**Comment by ThewBear** [comment]
Just applied it and bug is still persisted.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/ba240890c9d8f9c176f3cf3956eb88ee5bbf793d#diff-90d299ef742d9833a884e656bb7d590cR224-R229
