### ISSUE TITLE
[Documentation] Website down

### ISSUE THREAD

**Issue by 0x62** [vuetifyjs/vuetify#9978]
### Environment
**Browsers:** Firefox 72.0
**OS:** Mac OS 10.14

### Steps to reproduce
Visit https://vuetifyjs.com

### Expected Behavior
Website loads

### Actual Behavior
Cloudflare 524 Timed out

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

### Other comments
v15.vuetifyjs.com is working correctly

**Comment by MajesticPotatoe** [comment]
We are aware of https://vuetifyjs.com/ being down and are looking into it. You can use https://dev.vuetifyjs.com/ for the time being until this is resolved. Feel free to monitor https://status.vuetifyjs.com/ for the current status of the site. Thank you for your patience.
