### ISSUE TITLE
[Documentation] exposed auth tokens due to documentation site throwing 500's

### ISSUE THREAD

**Issue by lrstanley** [vuetifyjs/vuetify#9979]
### Environment

**Browsers:** Chrome 79.0.3945.79, Other, Opera, Internet Explorer, Microsoft Edge, Safari, Mozilla Firefox, Google Chrome
**OS:** Windows 10, Windows, Android, iOS, Mac OSX, Linux

### Steps to reproduce
Not sure if the endpoint is still returning a 500, but I've truncated the auth token: https://imgur.com/a/C7DyFJg

This was an environment variable passed to the deployed app... among other environment variables passed to the app.

### Expected Behavior
n/a

### Actual Behavior
n/a

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/buttons#button-dropdown-variants" target="_blank">https://vuetifyjs.com/en/components/buttons#button-dropdown-variants</a>

### Other comments
n/a

**Comment by lrstanley** [comment]
If imgur fails to work:

![image](https://user-images.githubusercontent.com/1847365/70926237-c4aa4680-1ffa-11ea-9661-bc81a479abbd.png)

**Comment by MajesticPotatoe** [comment]
> per kaels comment in discord: it was just for the web host and appears to be either hashed or encrypted

resolved.
