### ISSUE TITLE
[Documentation] Documentation error

### ISSUE THREAD

**Issue by lucasromanojf** [vuetifyjs/vuetify#9980]
### Environment

**Browsers:** Chrome 79.0.3945.79
**OS:** Linux x86_64

### Steps to reproduce
1) Clear browser cache;
2) Enter the documentation URL on browser and an error page will appear.

### Expected Behavior
Documentation should show normally.

### Actual Behavior
An error page is shown when trying to access the docs.

### Reproduction Link
<a href="https://vuetifyjs.com/pt-BR/introduction/why-vuetify" target="_blank">https://vuetifyjs.com/pt-BR/introduction/why-vuetify</a>

**Comment by lrstanley** [comment]
See also: https://github.com/vuetifyjs/vuetify/issues/9979

**Comment by MajesticPotatoe** [comment]
resolved
