### ISSUE TITLE
[Feature Request] Validation rules for Chip groups

### ISSUE THREAD

**Issue by jonasrdm** [vuetifyjs/vuetify#9982]
### Problem to solve
Chip groups are groups of selectable chips, and since it is a "form" of input, maybe it should implement some validation engine like other input elements as well?

### Proposed solution
Implement "rules" like on other input components

**Comment by KaelWD** [comment]
This won't be added to chip-group itself, but custom validation is now available with the `v-validation` component and `v-input` is much more flexible if you want the same structure as the other built in inputs.
