### ISSUE TITLE
[Documentation] Date pickers typo

### ISSUE THREAD

**Issue by fadafez** [vuetifyjs/vuetify#9983]
### Environment

**Browsers:** Firefox 71.0
**OS:** Windows 10

### Steps to reproduce
Goto "Date pickers - Mutiple"

### Expected Behavior
Multiple 

### Actual Behavior
Mutiple

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/date-pickers" target="_blank">https://vuetifyjs.com/en/components/date-pickers</a>

### Other comments
Hi ... I'm reporting this little typo.
Plus, I don't know if it's an issue linked to me using the documentation offline, but the search engine seems a bit strange. I search for "save" and it fins words like "same", weird, isn't it? 

Anyway, your library is very well done, I've switched from ElementUI due to responsive lack in that lib...I'm really happy for the switch.
Actually the only thing that I miss, is the datetime picker, but you have done a wonderful work, really

Thanks
Federico Ricchiuto

**Comment by MajesticPotatoe** [comment]
fixed in 6871334
Search is like that in live as well. Its done by a third party. Chances are it didn't find anything particular in its crawler data for "save" so it went with a common similar word that came up frequently.
