### ISSUE TITLE
[Documentation] Collapsed drawer on desktop and app bar on mobile

### ISSUE THREAD

**Issue by RossComputerGuy** [vuetifyjs/vuetify#9987]
### Problem to solve
A navigation bar that works collapsed without the app bar on desktop and the navigation bar with the app bar on mobile.

### Proposed solution
A part of the documentation or an example that shows this being done with variables

**Comment by MajesticPotatoe** [comment]
If you could provide a codepen example of what you are trying to accomplish, We could considering adding the example, though may be something better for snips when its released as its more of a mesh of 2 components in specific scenario.

From what I can gather from your description seems like you are trying to have something like https://vuetifyjs.com/en/components/navigation-drawers#temporary when breakpoint is say `mdAndUp`, and then https://vuetifyjs.com/en/examples/layouts/baseline when `smAndDown`

**Comment by RossComputerGuy** [comment]
https://codepen.io/spaceboyross/pen/dyPNdBZ Something like this except I want the drawer to only be expandable when the screen is medium and up.
