### ISSUE TITLE
[Bug Report] Calender events next to preceding event shifting position 

### ISSUE THREAD

**Issue by kunalahirrao** [vuetifyjs/vuetify#9989]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.108
**OS:** Windows 10

### Steps to reproduce
Default example showing same

### Expected Behavior
Events should cover entire rectangle or (row*col space).

### Actual Behavior
Leaving blank space

### Reproduction Link
<a href="https://codepen.io/spider007/pen/RwNwvzM" target="_blank">https://codepen.io/spider007/pen/RwNwvzM</a>

### Other comments
Codepen for the same

**Comment by ClickerMonkey** [comment]
event-overlap-threshold is used to control how many minutes apart two event starts can be before their content is considered overlapping which results in the behavior seen.

The 2.2.0 release contains some useful event overlapping logic fixes, keep a lookout for that.

**Comment by ClickerMonkey** [comment]
Based on the example set event-overlap-threshold to 15 and it should be fine.
