### ISSUE TITLE
Tooltips next to a navigation drawer

### ISSUE THREAD

**Issue by swerrie** [vuetifyjs/vuetify#999]
### Versions
v0.13.1

### What is expected ?
The right tooltip should be visible next to a navigation drawer.

### What is actually happening ?
The right tooltip is hidden.

### Reproduction Link
https://codepen.io/SvenRedbull/pen/MoZGvB

**Comment by johnleider** [comment]
This will have to be taken care of with the tooltip refactor, won't be able to work with how they currently work.
