### ISSUE TITLE
[Bug Report] Input number triggers "0" string value to rules validator on Firefox

### ISSUE THREAD

**Issue by genygilles** [vuetifyjs/vuetify#9990]
### Environment
**Vuetify Version:** 2.1.14
**Vue Version:** 2.6.11
**Browsers:** Firefox 71.0
**OS:** Linux

### Steps to reproduce
An input number with the following attributes:
* `type="number"`
* `v-model.number` modifier
* `min="0"`
* `rules`

on Firefox (not on Chrome), decrement the number using the arrowdown key.

### Expected Behavior
Should not trigger any change as 0 as number is already in the model.

### Actual Behavior
When it reaches 0, trying to decrement once more triggers "0" string value to validation (and model?)

### Reproduction Link
<a href="https://codepen.io/genygilles/pen/LYEbgQL" target="_blank">https://codepen.io/genygilles/pen/LYEbgQL</a>

**Comment by johnleider** [comment]
I'm not sure why Firefox is allowing events to emit when the value can't change, but there's nothing we can do about this. Update your rule to convert the value to a number.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
