### ISSUE TITLE
[Bug Report] Nested dialogs

### ISSUE THREAD

**Issue by bajki** [vuetifyjs/vuetify#9991]
### Environment
**Vuetify Version:** 2.1.14
**Last working version:** 2.1.10
**Vue Version:** 2.6.11
**Browsers:** Chrome 78.0.3904.108
**OS:** Linux x86_64

### Steps to reproduce
Add dialog inside fullscreen dialog.

### Expected Behavior
When you close nested dialog, fullscreen dialog stays open.

### Actual Behavior
Both dialog closes.

### Reproduction Link
<a href="https://codepen.io/bajki/pen/VwYmRwd" target="_blank">https://codepen.io/bajki/pen/VwYmRwd</a>

**Comment by KaelWD** [comment]
Duplicate of #9907
