### ISSUE TITLE
[Bug Report] hide-on-scroll on Safari => works the reverse way

### ISSUE THREAD

**Issue by guillim** [vuetifyjs/vuetify#9993]
### Environment
**Vuetify Version:** 2.2.0-beta.0
**Vue Version:** 2.6.10
**Browsers:** Safari
**OS:** Mac OS 10.15.0

### Steps to reproduce
1 - Open Safari
2 - Go to the [official documentation Playground](https://vuetifyjs.com/en/components/app-bars#playground)
3 - Select Hide-on-scroll
4 - Scroll to the bottom and observe

### Expected Behavior
We expect the documentation behavior: _Hides the app-bar when scrolling. Will still show the extension slot._

### Actual Behavior
works the other way around:
- scrolling at the bottom, app-bar appears
- scrolling at the top, app-bar disappears

### Reproduction Link
<a href="https://codepen.io/guillim/full/qBEqwKB" target="_blank">https://codepen.io/guillim/full/qBEqwKB</a>

### Other comments
it is a problem since the behavior is opposite to other browsers

**Comment by KaelWD** [comment]
Unable to reproduce in safari 13 on Catalina

**Comment by guillim** [comment]
I just updated the CodePen to make it even more straightforward. 

Here is what I have on codePen when I use Safari
![Screenshot 2019-12-18 at 14 02 59](https://user-images.githubusercontent.com/13087916/71088662-40dd8f00-219f-11ea-92c4-1ef48ebacf14.png)

Here is what I have on codePen when I use Chrome
![Screenshot 2019-12-18 at 14 07 16](https://user-images.githubusercontent.com/13087916/71088861-cbbe8980-219f-11ea-90a3-2aca32b637d0.png)

Don't you have this on your side?

**Comment by KaelWD** [comment]
Nope, the toolbar is shown at first then hides when I scroll down. This is in browserstack though so maybe it's different on an actual mac. Can you make sure you don't have any extensions enabled?

**Comment by guillim** [comment]
> Nope, the toolbar is shown at first then hides when I scroll down. This is in browserstack though so maybe it's different on an actual mac. Can you make sure you don't have any extensions enabled?

There are no extension installed on my Safari browser on my mac (Catalina 10.15)

I can't access BrowserStack since it's a paid option for my configuration, there may be a bug with it for the reproduction

**Comment by CodeSkills** [comment]
I tested this on Mac OS Catalina on Macbook all updated to latest. The navbar is visible on load but when I try to scroll up and down, in Safari it stops working after 3-5 up/down scrolls and the navbar never shows up

![Screen-Recording-2019-12-19-at-20 56 40](https://user-images.githubusercontent.com/3975293/71205315-6ef7c780-22a2-11ea-9bfd-a061a3dff8f5.gif)

**Comment by KaelWD** [comment]
@CodeSkills what styles are being applied when it's broken?

**Comment by CodeSkills** [comment]
This one is when im on the top and its bugged -> not visible
<img width="1098" alt="Screenshot 2019-12-20 at 11 12 46" src="https://user-images.githubusercontent.com/3975293/71247822-d13fdf00-2319-11ea-848d-7f18750cd1c8.png">

If I try to scroll more top (like over the limit of 0) it changes to this
<img width="1266" alt="Screenshot 2019-12-20 at 11 13 03" src="https://user-images.githubusercontent.com/3975293/71247880-f0d70780-2319-11ea-9477-d6e695b7eecc.png">
But it instantly goes back to the first image and disappears when I stop scrolling.

**Comment by johnleider** [comment]
@KaelWD Are you still requesting information? If so, this issue should be closed.

**Comment by johnleider** [comment]
This issue is being closed due to:

- [ ] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

**Comment by KaelWD** [comment]
> Are you still requesting information?

No.

**Comment by guillim** [comment]
Anyone has some updates on this topic?

**Comment by guilhermewaess** [comment]
@guillim I'm also waiting for some update here.

**Comment by matthieusieben** [comment]
I have a similar issue in Chrome. Here is my workaround:

```vue
<template>
  <v-app v-scroll="onScroll">
    <v-app-bar ref="appBar" app hide-on-scroll>
      <!-- content -->
    </v-app-bar>
    <v-content>
      <!-- content -->
    </v-content>
  </v-app>
</template>

<script>
import { Scroll } from 'vuetify/lib/directives/scroll'

export default {
  directives: {
    Scroll
  },
  methods: {
    onScroll() {
      // @hack: https://github.com/vuetifyjs/vuetify/pull/11105
      const { appBar } = this.$refs
      if (appBar && appBar.currentScroll === 0) {
        this.$nextTick(() => {
          // Trigger after VAppBar's scroll handler
          appBar.isActive = true
        })
      }
    },
    // other methods ...
  }
}
</script>
```

**Comment by matthieusieben** [comment]
Adding the following watchers to `VAppBar` yield some strange results:

```js

    computedScrollThreshold: {
      handler(val) {
        console.error('computedScrollThreshold', val) // -9 (!!!!!)
      },
      immediate: true,
    },
    scrollThreshold: {
      handler(val) {
        console.error('scrollThreshold', val) // => undefined
      },
      immediate: true,
    },
```

Note that I am using this with NuxtJS with SSR (i see the -9 value both in server & client logs)

**Comment by marcgibbons** [comment]
As a workaround, I've created a new component by extending `VAppBar` and overriding the `thresholdMet()` method with this:

```js
// ...
if (this.hideOnScroll) {
  // this.isActive = this.isScrollingUp
  this.isActive = (
    this.isScrollingUp 
    || this.currentScroll < this.computedScrollThreshold
  );
}
```
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VAppBar/VAppBar.ts#L262

Seems to reliably prevents the app bar from hiding when scrolling into negative territory on iOS Safari.

**Comment by Tofandel** [comment]
This is still an issue, PR did not solve the problem

**Comment by msamara** [comment]
Still an issue, same exact behavior on Safari browsers, last 2 versions

**Comment by nekosaur** [comment]
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).
