### ISSUE TITLE
[Bug Report] Invalid CSS after "@content": expected selector, was "($material-light) {"

### ISSUE THREAD

**Issue by awsirkis** [vuetifyjs/vuetify#9998]
### Environment
**Vuetify Version:** 2.1.15
**Vue Version:** 2.6.11
**Browsers:** Edge 79.0.309.51
**OS:** Windows 10

### Steps to reproduce
Install the latest stable version of Vuetify and sass-loader ^7.3.1. Attempt to compile a project utilizing and Vuetify components.

### Expected Behavior
Complete compilation of client-side project (used to work before trying to use components)

### Actual Behavior
Receive following error:
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                            friendly-errors 21:21:39

@content($material-light)
       ^
      Invalid CSS after "@content": expected selector, was "($material-light) {"
      in C:\Users\USR_NAME\karate\node_modules\vuetify\src\styles\tools\_theme.sass (line 3, column 9)

### Reproduction Link
<a href="https://github.com/awsirkis/karate_test_site" target="_blank">https://github.com/awsirkis/karate_test_site</a>

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/introduction/frequently-asked-questions#invalid-css-after-content-expected-was-material-light
